### ISSUE TITLE
BaseRecalibrator should complain if knownSites and the reference have incompatible contigs

### ISSUE THREAD

**Issue by akiezun** [broadinstitute/gatk#1029]
If I run BaseRecalibrator on a reference with contigs [20,21] and knownSites only has  only sites from 17, then GATK3 blows up:
```
##### ERROR MESSAGE: Input files knownSites and reference have incompatible contigs: No overlapping contigs found.
##### ERROR   knownSites contigs = [17]
##### ERROR   reference contigs = [20, 21]
```

but gatk4 does not (and it should). This is the cause of the bogus tests in #1017 (they should have never been allowed to exist).

The commandline for GATK3 is
(the VCF has no sequence dictionary)
```
-T BaseRecalibrator -R src/test/resources/large/human_g1k_v37.20.21.fasta -I src/test/resources/org/broadinstitute/hellbender/tools/BQSR/CEUTrio.HiSeq.WGS.b37.ch20.1m-1m1k.NA12878.bam --out gatk3.3.recal.txt --knownSites src/test/resources/org/broadinstitute/hellbender/tools/BQSR/dbsnp_132.b37.excluding_sites_after_129.chr17_69k_70k.vcf
```

**Comment by droazen** [comment]
This is because GATK3 creates sequence dictionaries from VCF indices, and when an index is not present it creates one on-the-fly (see `RMDTrackBuilder.getFeatureSource()`). We could do the same in GATK4 (though we may not want to index vcfs on-the-fly if they're unindexed, as that is a source of race conditions -- safer to throw and make the user index the files).

**Comment by akiezun** [comment]
punting on this for alpha-1
