### ISSUE TITLE
Profile the Spark local runner

### ISSUE THREAD

**Issue by droazen** [broadinstitute/gatk#1047]
What kind of performance do we get when we run Spark tools locally compared to both the walker versions and the GATK3 versions? We should test apples-to-apples first (1 core for Spark), then test multithreaded Spark vs. single-threaded walkers. Should also use fairly large inputs.

@lbergelson 's initial tests on the Spark BQSR show that with 1 or 2 threads the Spark version is unusably slow locally, and with 8 threads (on a 4 core machine) it still loses by ~6x or ~7x to the walker version. This is regardless of joinStrategy = SHUFFLE or BROADCAST.

If the slowness above is confirmed, and we can identify ways to speed up Spark locally, we should create additional tickets to make those changes and assess whether they are realistic for the alpha milestone.

**Comment by droazen** [comment]
For @davidadamsphd when you get tired of validation tickets (if you don't have the bandwidth for this one, feel free to re-assign).

**Comment by droazen** [comment]
@tomwhite and @laserson could you also help out with this one?

**Comment by droazen** [comment]
Reassigned to @tomwhite, as discussed in person.

**Comment by tomwhite** [comment]
I started with Mark Duplicates and found that on the 76MB BAM file in resources, the walker took ~20 seconds, while local Spark took ~120s (with all cores). However, when I changed GATKRegistrator to use SAMRecordToGATKReadAdapterSerializer, local Spark took ~36s (all cores) or ~55s (1 core). Also, this is not writing a single file, since https://github.com/broadinstitute/gatk/issues/1015 has not been fixed yet.

So we should definitely use the better serializer - is there any reason not to do that now?

Spark performance running locally with a single core on small files is probably not going to match the walker implementations since the local runner is not tuned for that use case.

**Comment by tomwhite** [comment]
For Mark Duplicates, the timings after the latest Spark improvements (like https://github.com/broadinstitute/gatk/pull/1190) are
* Walker: 18s
* Spark: 36s (sharded BAM, all cores), 55s (sharded BAM, 1 core), 93s (single BAM, all cores), 105s (single BAM, 1 core)

I'm going to close this now since the runner itself is OK (and as I said before is not going to match hand tuned implementations typically). We can make further improvements to the different algorithms, e.g. in https://github.com/broadinstitute/gatk/issues/1100.
