### ISSUE TITLE
Make CRAM file comparison non-lenient in PrintReadsIntegrationTest

### ISSUE THREAD

**Issue by akiezun** [broadinstitute/gatk#1087]
due to a CRAM bug https://github.com/samtools/htsjdk/issues/364 we have to make a few tests lenient.

make them stringent when the cram bug is resolved

**Comment by cmnbroad** [comment]
Once #1084 is merged, AddOrReplaceReadGroupsIntegrationTest has two CRAM tests that are commented out due to this same problem.

**Comment by akiezun** [comment]
#1084 is merged but 2 tests in PrintReadsIntegrationTest are still using lenient comparison because NM tag gets lost (curiously spark version of printreads works fine)

**Comment by akiezun** [comment]
@cmnbroad for you - since you're collecting all things cram

**Comment by cmnbroad** [comment]
The missing NM tags are due to https://github.com/samtools/htsjdk/issues/455. PrintReadsSpark doesn't have this problem now because the tags are lost when going from BAM->CRAM, and the spark tools can't write CRAMs (yet). Once CRAM writing [is enabled](https://github.com/broadinstitute/gatk/tree/cn_spark_write_cram) the same problem happens on Spark.
