### ISSUE TITLE
Understand why Hadoop-BAM uses a guessing approach to find BGZF block boundaries instead of using the block lengths in the BGZF headers

### ISSUE THREAD

**Issue by droazen** [broadinstitute/gatk#1091]

**Comment by droazen** [comment]
May want to start by reading the original Hadoop-BAM paper (http://bioinformatics.oxfordjournals.org/content/28/6/876.full.pdf+html) before diving into the code itself.

**Comment by davidadamsphd** [comment]
OK. Section 4 of the SAM spec (https://samtools.github.io/hts-specs/SAMv1.pdf) talks about the BAM spec.
There is a header for each zipped block, however, it doesn't mention the location of the start of any of the BAM records within the block. This is an issue because a BAM record can span two zipped blocks. On the second block, there is no indication how much of the record is left to be read. That forces the bam reader to parse bytes until a valid bam record is found.

It's worth noting that we expect that guessing for the start location becomes a non-issue when you use the (normal) bam index, see section 4.1.1 of the SAM spec, as the header has all of the relevant information on where to start looking for the beginning of records. 

It is very likely that we (GATK) will require the existence of the (normal) header when reading BAMs from HDFS.

**Comment by tomwhite** [comment]
BAMSplitGuesser works by first finding the next BGZF block boundary (each block is no more than 64KB in size). Then it looks for the start of a BAM record within the BGZF block boundary. The latter is the part that uses heuristics to find the record start and for which we’ve fixed some bugs (https://github.com/HadoopGenomics/Hadoop-BAM/pull/25, https://github.com/HadoopGenomics/Hadoop-BAM/pull/29).

The guessing algorithm is discussed in some detail in http://bioinformatics.oxfordjournals.org/content/suppl/2013/05/10/bts054.DC1/supplement.pdf

Hadoop-BAM has the concept of a “splitting” index file (with extension .splitting-bai). It contains the virtual file offsets for every nth read in a BAM (where n is 4096 by default). The input format code then uses the index to get the next read (or at least the next one in the index) that starts after the HDFS block boundary for the split. As far as I can tell, the code for creating splitting index files isn’t easy to run on files in HDFS (SplittingBAMIndexer runs on local filesystem files), so it may be that splitting index files are not widely used. 

The standard BAM index (.bai) is not used by Hadoop-BAM for generating splits. ADAM has IndexedBamInputFormat (see https://github.com/bigdatagenomics/adam/pull/732 and https://github.com/bigdatagenomics/adam/issues/787), which seems to be focused on reading a subset of a file, since it doesn’t respect HDFS locality (mappers would not run on the machine hosting the input data).

It's not clear to me how we could use .bai files to get an even distribution of splits, and to get decent locality. Note that Matti Niemenmaa's thesis on Hadoop-BAM states

> Note that BAM and BCF can be, and commonly are, indexed. As the
> index contains the precise positions of many records in the file, one might
> think that it could be used for aligning splits accurately. Unfortunately
> their indexing schemes are not suitable for the task, due to at least all of
> the following reasons...

And the reasons are listed on p46 of https://aaltodoc.aalto.fi/bitstream/handle/123456789/11886/master_niemenmaa_matti_2013.pdf.
