### ISSUE TITLE
Evaluate the Hadoop BAM single bam writer

### ISSUE THREAD

**Issue by droazen** [broadinstitute/gatk#1094]
Apparently Hadoop BAM comes with a single BAM writer that is supposed to be fast. Let's evaluate it to determine whether it could solve https://github.com/broadinstitute/gatk/issues/1015

**Comment by droazen** [comment]
If it turns out that we can use this, we can mark https://github.com/broadinstitute/gatk/issues/1015 as resolved.

**Comment by droazen** [comment]
Who wants this ticket?

**Comment by droazen** [comment]
@akiezun Since you always have extra bandwidth due to being so fast with everything, I am giving this hot potato to you :)

**Comment by akiezun** [comment]
nice!

**Comment by droazen** [comment]
Do you think this should be an alpha ticket, or are we ok with this being targeted for beta?

**Comment by droazen** [comment]
Never mind -- since https://github.com/broadinstitute/gatk/issues/1015 is marked for alpha, this one should be too.

**Comment by laserson** [comment]
happy to review when you push a PR

**Comment by tomwhite** [comment]
It looks like Hadoop-BAM uses Hadoop's TotalOrderPartitioner to do the sort in parallel (i.e. using more than one reducer) in such a way as to have a total ordering, so that reads in partition _i_ are all less than those in _i+1_. Then the output files are concatenated. This will need some alterations to get it working in Spark, since TotalOrderPartitioner relies on the distributed cache (which Spark doesn't have).

I can take a look at this if you like, @akiezun.

**Comment by akiezun** [comment]
that would be great, thanks Tom

**Comment by tomwhite** [comment]
Fixed in #1174
