### ISSUE TITLE
(Re)write the GATKRead impl for ADAM

### ISSUE THREAD

**Issue by laserson** [broadinstitute/gatk#1189]
The current `BDGAlignmentRecordToGATKReadAdapter.java` really uses a `SAMRecord` inside, while it could be implemented as a bonafide implementation (and use the Avro serializer).

**Comment by akiezun** [comment]
when done BDGAlignmentRecordToGATKReadAdapter should not be a subclass of SAMRecordToGATKReadAdapter, please.

also, remember to add tests for deepCopy (see #1194)

**Comment by cmnbroad** [comment]
This really should be integrated with all the tests in GATKReadAdaptersUnitTest (currently its only integrated with the toString test), once it has equals, copy, deepCopy, getSAMString implementations, and can update its backing record,etc. Also, the sparkReadAdapter(final AlignmentRecord record) overload fails since the AlignmentRecordConverter always tries to dereference the (null) header that is passed in from that code path.

**Comment by droazen** [comment]
Not happening -- closing.
