### ISSUE TITLE
reading from a GA4GH Reads store

### ISSUE THREAD

**Issue by akiezun** [broadinstitute/gatk#1206]
We need to have the ability to read from a ga4gh compliant readstore. The task to is implement this and add tests for it (using reference reads store or google genomics - ideally both)

**Comment by akiezun** [comment]
@davidadamsphd can you comment on what infrastructure exits and what is still missing?

**Comment by davidadamsphd** [comment]
There is some example code (https://github.com/googlegenomics/spark-examples/tree/master/src/main/scala/com/google/cloud/genomics/spark/examples/rdd) in Scala here that does it. We'll want to use it as a template for our own purposes (at the very least, we'll want to put the result into a BAMRecord instead of a model read.

FYI, they recently upgraded the variant code to use gRPC (which is much faster than the previous method). When we get around to benchmarking, we can see if it's worth getting the reads-side upgraded too.

**Comment by lbergelson** [comment]
The readstore api has been turned off at google and GA4GH is moving to use hts-get instead, so closing this one.
