### ISSUE TITLE
reading CRAM on Spark needs a way to relax validation stringency

### ISSUE THREAD

**Issue by akiezun** [broadinstitute/gatk#1261]
see disabled test in ReadsSparkSourceUnitTest.readsSparkSourceTest

**Comment by cmnbroad** [comment]
This requires an upgrade to Hadoop-BAM the next time its released in order to pick up [this commit](https://github.com/HadoopGenomics/Hadoop-BAM/commit/85222f0d56f5a4294ff8fdff84c87b74b99413fc), plus changes in GATK to pass the validation stringency through. I have the necessary changes to GATK, but can't commit them as is because they're intertwined with other changes necessary for https://github.com/broadinstitute/gatk/issues/1346, which are in turn dependent on [other changes](https://github.com/cmnbroad/Hadoop-BAM/commit/07fc5560c2fabfab8c2d8344489efc47996cc597) that are not yet merged into Hadoop-BAM. They could be separated but hopefully will not have to be,

**Comment by cmnbroad** [comment]
Closed via #1469.
