### ISSUE TITLE
Tweak the --sparkRunner arg in gatk-launch

### ISSUE THREAD

**Issue by laserson** [broadinstitute/gatk#1329]
I find the `--sparkRunner` arg to be a bit confusing:

* `DIRECT` uses the local walker impl, and doesn't run Spark at all, so it probably shouldn't be a "sparkRunner".  I also initially thought this would use the Spark local runner.
* `SUBMIT` only makes sense to me because I use Spark, but also not as clear as could be.  Also it seems a bit non-obvious that this is the option to pick if you want to run Spark with the local runner.

I would propose

* `--runner LOCAL` or `--runner WALKER` (or `--runner DIRECT`, though I personally find this less clear) for the actual local impl that doesn't use Spark at all.
* `--runner SPARK` for anything that uses the `spark-submit` script, including running it in `local[*]` mode.  This is the only option that should accept `--sparkMaster`, or maybe just `--master` to be more in line with `spark-submit`
* `--runner GCS` for Google
* `--runner AWS` for Amazon in the future

Thoughts?

**Comment by droazen** [comment]
I agree that `--runner SPARK` is much better than `--sparkRunner SUBMIT` to someone unfamiliar with the existence of `spark-submit`.

`DIRECT` uses the in-memory Spark runner for Spark tools, though (as there is no way to run a Spark tool using the "walker" engine), so it does seem like a "Spark" runner to me?

**Comment by lbergelson** [comment]
So naming has been a debate with several revisions so far.  Definitely not happy with what we have at the moment.

Right now you can run the spark local runner without specifying `DIRECT` at all, but it seemed more symmetric to have runner option.

`DIRECT` is basically a no op for running with `--sparkMaster local[*]`  I added it as a separate option because I thought it seemed likely that we would want to pass spark options into it somehow, but I wasn't quite sure the right way to do it yet.    @laserson How do you pass them in by the way?  Can you set them as java system properties?

If you don't have a spark installation on your system, you can use the DIRECT runner to run the spark tools, using local[*], but you can't use spark-submit.  

I'm +1 for changing sparkRunner -> runner.  We could eliminate the DIRECT option.  It's fine if people run just `./gatk-launch CountReadsSpark -I flag_stat.bam  --sparkMaster 'local[1]'`

**Comment by droazen** [comment]
I would prefer to not require an extra `--sparkMaster` argument to run a Spark tool locally -- ie, `/gatk-launch CountReadsSpark -I flag_stat.bam` should run locally by default.

I think we should keep the name `sparkRunner` for symmetry with `sparkMaster`, and to make it clear it's a Spark argument and not a tool argument, but we should rename `SUBMIT` to `SPARK`.

**Comment by laserson** [comment]
Can we eliminate the extra `--sparkMaster` option entirely?

**Comment by lbergelson** [comment]
@laserson If we eliminate it, how will people specify how many cores they want to run?

**Comment by laserson** [comment]
I think that `DIRECT` should only give access to walker impls.  Anything Spark should use spark-submit or gcs.  So if you're running a local Spark tool, you would use `--runner SPARK --master local[3]`.

**Comment by lbergelson** [comment]
@laserson that doesn't work if you don't have a spark installation installed, and seems to crash for certain inputs with scary errors see #1315

**Comment by droazen** [comment]
Walkers should not need an explicit runner argument at all -- the syntax for running walkers needs to be consistent with GATK3 conventions.

Is there no benefit to exposing the ability to run Spark tools using the in-memory runner via `--sparkRunner LOCAL`? I think it's good to allow this, as long as there's also a way to run `spark-submit` locally.

**Comment by laserson** [comment]
@lbergelson Yes, but don't you have to have Spark available somewhere locally in order to run Spark locally?

@droazen I personally don't see a benefit, if it will do the same thing as `spark-submit --master local`.  As an alternative, we could have it so that `--runner` defaults to `DIRECT` and the walker impl is always the default unless someone explicitly asks to use a Spark runner.  This would make it more backwards compatbile with GATK3, no?
