### ISSUE TITLE
Consider making the LOCAL runner (previously DIRECT) only run walker impls

### ISSUE THREAD

**Issue by laserson** [broadinstitute/gatk#1361]
Opening this to continue discussion from #1315 for beta.

**Comment by droazen** [comment]
I think we want to be able to run Spark tools using the in-memory runner by default (the current behavior of `--sparkRunner LOCAL`), as it's faster than using `spark-submit` with `local[]`. Can you explain why you think we shouldn't be using the in-memory runner?

**Comment by laserson** [comment]
Maybe I am seriously confused.  I would think that the "runner" argument should really correspond to an actual runner, that being walker, spark-submit, or gcs.   Couldn't you make `--sparkRunner SPARK --sparkMaster local[*]` the default if that's what you want?

I guess I don't understand what the purpose of having `LOCAL` run via Spark in a non-standard way, when you should be able to accomplish the exact same thing with `SPARK` using the standard way of running Spark apps.

**Comment by droazen** [comment]
@laserson The walker and Spark implementations of a given tool are completely separate things. Eg., we have both `PrintReads` and `PrintReadsSpark`. This is why we don't need a "runner" argument to select the walker implementation -- it's selected via the tool name. The concept of "runner" is (currently) only meaningful for Spark tools.

The in-memory runner has a few advantages over `spark-submit` with `local[*]`, as far as I know: it runs faster, with less spammy output, and doesn't require the user to install Spark (since it uses the version bundled in the GATK jar).

**Comment by droazen** [comment]
Closing, since walkers do not actually have a spark runner.
