### ISSUE TITLE
SelectVariants should work correctly with non-diploids

### ISSUE THREAD

**Issue by vdauwera** [broadinstitute/gatk#1382]
_From @ronlevine on August 6, 2015 16:34_

SelectVariants only supports diploid genomes due to the method in ```GATKVariantContextUtils.getDiploidLikelihoodIndexes()``` : 
```GenotypeLikelihoods.GenotypeLikelihoodsAllelePair GenotypeLikelihoods.getAllelePair(nt PLindex)```

Creating a method such as ```ArrayList<Integer> getAlleles(int PLindex)``` and processing the return values should work for general-ploidy.

- [ ] When implemented, create issue in gsa-unstable to backport this. 

_Copied from original issue: broadinstitute/gsa-unstable#1122_

**Comment by akiezun** [comment]
@vdauwera  or @ronlevine can you provide an example input and desired output?

**Comment by ronlevine** [comment]
SelectVariants is diploid because of `GenotypeLikelihoods.GenotypeLikelihoodsAllelePair GenotypeLikelihoods.getAllelePair()`. It uses a diploid array of length 3 for the following genotypes (0/0, 0/1,1/1)
For the anyploid case, this method will not work properly. It should be replaced by:
`ArrayList<int> alleles = getAlleles(int PLindex)`
For the triploid case,
`alllele.size() == 3`

**Comment by ronlevine** [comment]
In a nutshell, `GenotypeLikelihoodsAllelePair GenotypeLikelihoods..getAllelePair(final int PLindex)` returns the cached alleles corresponding to the PLindex. This cache is diploid because the method that initializes it,  `GenotypeLikelihoodsAllelePair[] GenotypeLikelihoods.calculatePLcache(final int altAlleles)`,  uses a diploid number of likelihoods ( `numLikelihoods(1 + altAlleles, 2)`) and adds an allele pair each PLindex, instead of the ploidy number of allele indices. If the methods are generalized, they should return `ArrayList<int> ` instead of `GenotypeLikelihoodsAllelePair`.

**Comment by droazen** [comment]
@ronlevine, are you available to implement this in GATK4's SelectVariants?

**Comment by ronlevine** [comment]
@akiezun This is mostly an HTSJDK issue, the GATK part is trivial. I can do it after I complete https://github.com/broadinstitute/gsa-unstable/issues/1128.

**Comment by droazen** [comment]
Great, thank you!

**Comment by vdauwera** [comment]
@droazen What do we need to do to make issues here assignable directly to @ronlevine? Is this a github team / bits help kind of thing?

**Comment by droazen** [comment]
@vdauwera Yes, he needs to be added to the appropriate github team (one that gives him write access to the repo).

**Comment by vdauwera** [comment]
OK, thought so but I'm sick and my brain isn't working. Request sent to help.

**Comment by ronlevine** [comment]
GenotypeLikelihoods.calculatePLindex will have to be generalized for anyploid. The equation for the index of the value corresponding to the genotype in VCF 4.3 spec, section, 1.6.2 (Genotype Fields) should be implemented, instead of the diploid implementation (F(j/k) = (k*(k+1)/2)+j).

**Comment by ronlevine** [comment]
Depends on https://github.com/samtools/htsjdk/issues/437

**Comment by vdauwera** [comment]
When this is done, let user know in broadinstitute/dsde-docs#709

**Comment by chandrans** [comment]
Please also let user know from http://gatkforums.broadinstitute.org/gatk/discussion/7298/removealternates-not-working-on-haploid-vcfs
Thanks

**Comment by ronlevine** [comment]
Will do. Most of the work is done. I need to add unit and integration tests to make sure any hidden diploid assumptions are uncovered.

**Comment by ronlevine** [comment]
Tests are finding a lot of *hidden" diploid assumptions. :-(
Hopefully I've uncovered the last of them ...

**Comment by ronlevine** [comment]
Adding tests to SelectVariantsIntegrationTest and GATKVariantContextUtilsUnitTest. I haven't uncovered any missed diploid assumptions ... :-)

**Comment by chandrans** [comment]
Hi Ron. Can I close this and let users know SelectVariants works with non-diploids in the latest nightly?

**Comment by ronlevine** [comment]
This is for GATK4. SelectVariants works with non-diploids in the latest nightly because https://github.com/broadinstitute/gsa-unstable/issues/1122 is closed.

**Comment by ronlevine** [comment]
Closing because https://github.com/broadinstitute/gatk/pull/1845 was merged.
