### ISSUE TITLE
Ensure SplitNCigarReads produces valid bam files

### ISSUE THREAD

**Issue by vdauwera** [broadinstitute/gatk#1394]
Spin out of #1378 

The GATK3 implementation of this tool generates invalid bam files (because the mate pair info gets all screwed up). If possible to fix that within the tool itself that would be fabulous. Otherwise @yfarjoun has a Palantir ticket to look into a post-hoc fix with FixMateInformation. But it would be nicer to generate valid bams in the first place.

**Comment by lbergelson** [comment]
@vdauwera Is the fix to remove the mate information?  Or is there a way we can maintain it after the split?  I.e. should split reads be made into supplemental alignments?

**Comment by vdauwera** [comment]
I'm not sure -- this should be reviewed by methods to decide what is the
right thing to do.

**Comment by meganshand** [comment]
After talking about it with @yfarjoun, one possible solution would be to have each new split read point in an unbroken circle so that each read follows this rule: "RNEXT: Reference sequence name of the primary alignment of the NEXT read in the template. For the last read, the next read is the first read in the template." (From the SAM Spec) Where we are now thinking of a template as having more than two reads. Here's an example:

IGV shot before running SplitNCigarReads where the two reads that are highlighted in red are mates:
![screen shot 2016-06-16 at 11 05 54 am](https://cloud.githubusercontent.com/assets/13020550/16121787/9bec1ff8-33b2-11e6-873e-f3a35c6beb7b.png)

IGV shot of after running SplitNCigarReads with arrows pointing at what is currently being assigned as the mate of each read:
![screen shot 2016-06-16 at 11 08 57 am](https://cloud.githubusercontent.com/assets/13020550/16121821/bf282516-33b2-11e6-844b-710812dbd44c.png)

Proposed solution changes the arrows:
![screen shot 2016-06-16 at 11 10 25 am](https://cloud.githubusercontent.com/assets/13020550/16121879/f69e73e2-33b2-11e6-8a9d-c42328383bff.png)

This same solution would have to be applied to the general case where both reads in the original pair are split an arbitrary number of times. The concerns with this are that we aren't sure how this will effect downstream tools that may assume each template only has two reads (for example if a downstream tool checks a read for `!firstInPair` it assumes it must be the `secondInPair`). On that note we probably also want to change those two flags to something appropriate.

**Comment by jamesemery** [comment]
After a discussion with @lbergelson and @meganshand I have decided to implement the tool under the assumption that the input file is in query sorted order. This is because things become significantly more complicated if the sets of paired reads are not read in together by the tool. It is my understanding that this is a reasonable requirement given the RNA pipeline that this tool would be a part of. I will make an attempt to set the appropriate flags for the new output reads that relate to the other read in the pair.

There is still the question of what to do if the MC flag (which corresponds to the cigar string for this reads pairs) is set? I could repair these values according to the SAM spec but there is some question as to whether this flag will be useful given that paired reads may have been split into cycles.

**Comment by meganshand** [comment]
@vdauwera How do you think users would feel about having to sort their bams by query name before using this tool? We don't use this tool in our production pipeline and so having it be query name sorted isn't directly applicable (yet). It's unclear to me if people generally MarkDuplicates before this step, but if so and MarkDuplicates can output a query name sorted bam then this requirement doesn't seem like a huge deal.

@yfarjoun Where can we bring up the issue with the MC flag? Any thoughts on what we should output from this tool?

**Comment by vdauwera** [comment]
@meganshand Yes, this comes right after mark dups so wouldn't be a problem to require query and sort. Might want to check whether there is any sorting requirement in the next step(s) in the pipeline, though, and whether we need this tool to output in a different sort order.

**Comment by meganshand** [comment]
Officially the next step might be IndelRealigner? But more practically BQSR or HaplotypeCaller. We talked about adding an argument so the user could specify what order they'd like as output. @jamesemery Could you include that?

**Comment by yfarjoun** [comment]
You can look for discussion on hts-spec github.

not sure that indel-realigner will manage to work with a >2 segmented
template....

**Comment by lbergelson** [comment]
Will a modern RNA pipeline include indel realigner?

**Comment by meganshand** [comment]
Most likely not. We've validated that we don't need it for DNA, it's hard to imagine that would be different for RNA.

**Comment by vdauwera** [comment]
The RNA recommendation was already to drop indel realignment before we looked at dropping it for DNA. So hipster...

**Comment by meganshand** [comment]
@vdauwera The latest game plan for this ticket (which is being addressed in #2021) is to have SplitNCigarReads create a supplementary alignment from each split and soft clip the bases that align elsewhere. This allows the bam to be more usable by other tools (like BQSR) since the logic to handle supplementary reads already exists. This means that we need an additional argument to HaplotypeCaller so that allows using supplementary alignments (See #2043). 

My question is how can we document that SplitNCigarReads is not recommended for use with the changes to make the reads supplementary until #2043 is resolved? Is it possible to make the tool hidden in GATK4 or give it some tag that makes it clear it isn't ready for use yet?

**Comment by vdauwera** [comment]
Commented in #2043 -- it seems that in GATK3 supplementary alignments are already used by HC. Is that not the case in 4?

Technically GATK4 is alpha and therefore completely unsupported, so there is no strict obligation to document this. However I would recommend a conservative approach of not merging the branch with the changes until any changes that it depends on are implemented and merged. Is there any reason why this would need to be merged before the next piece of the workflow is ready?

**Comment by meganshand** [comment]
To reiterate here from #2043, HaplotypeCaller already looks at supplementary reads, so the new SplitNCigarReads should work out of the box, if the user includes --dontUseSoftClippedBases.

**Comment by meganshand** [comment]
Sorry, I meant if the user includes --dontUseSoftClippedBases in HaplotypeCaller.

**Comment by beginner984** [comment]
Sorry this command for me returns empty .bam file but why ?

java -jar $GATKjar -T SplitNCigarReads -R ./hs37d5.fa -I ./dupmarked.bam -o ./dupmarked_output.bam -U ALLOW_N_CIGAR_READS

Any suggestion please?

Thanks a lot

**Comment by jamesemery** [comment]
@beginner984 Could you explain what is happening in greater detail. I assume you mean that the .bam file was totally empty without even a header? Are you sure the task ran to completion? Do you have to command line output from the tool anywhere? What version of gatk are you running off of? 

I would suggest that you direct this and other questions of this nature to the [gatk forums](https://gatkforums.broadinstitute.org/gatk/categories/gatk-support-forum). There are people on there who can help you get your tools up an running with the gatk and its tools and might have answers to your problem. Thank You.
