### ISSUE TITLE
Hadoop-BAM: add support for efficiently loading a subset of a BAM

### ISSUE THREAD

**Issue by droazen** [broadinstitute/gatk#1399]
Relevant Hadoop-BAM ticket is https://github.com/HadoopGenomics/Hadoop-BAM/issues/34

We want to be able to provide Hadoop-BAM with a set of genomic intervals in `ReadsSparkSource`, and get back an `RDD` of just the reads overlapping those intervals. There should also be a way to request unmapped reads.

**Comment by droazen** [comment]
For alpha-1

**Comment by tomwhite** [comment]
I had a look at how close https://github.com/HadoopGenomics/Hadoop-BAM/pull/44 is to supporting genomic intervals in GATK. Some notes:
* There's a bug in the current PR (see comments there).
* It needs the ability to support multiple intervals (current PR only supports one) - we can do this as a follow-on if needed.
* There is a wider question about how to implement this efficiently. E.g. if there are lots of small intervals, should they be merged into a single split (which does filtering), rather than lots of small splits (which is less efficient for Spark). This could be a follow-on improvement too.

**Comment by tomwhite** [comment]
Here's my GATK branch: https://github.com/broadinstitute/gatk/compare/tw_hadoop_bam_intervals. The test passes with the work I've done in Hadoop-BAM in https://github.com/tomwhite/Hadoop-BAM/compare/paired-reads-in-same-split...tomwhite:use-bai.

**Comment by tomwhite** [comment]
Fixed in #1516.
