### ISSUE TITLE
spark tools with --shardedOutput should respect --numReducers

### ISSUE THREAD

**Issue by lbergelson** [broadinstitute/gatk#1455]
It looks like the new `--numReducers` argument is not always used when writing non sharded output.  This seems counterintuitive to me.  

For instance `PrintReadsSpark` seems to ignore `--numReducers`

**Comment by lbergelson** [comment]
@tomwhite It's possible that I'm misunderstanding this.  Is it intentional that it doesn't get propagated to non-shuffling tools that write output?

**Comment by droazen** [comment]
@tomwhite Could you comment on this? My impression from reviewing the PR in question was that this was intentional (that is, propagating `numReducers` to `writeReadsSingle()` and not `writeReadsSharded()`). This makes sense to me, since writing a single output file involves a reduce, whereas writing a sharded output file does not (unless you are re-partitioning to control the number of output shards, but that seems crazy to me, and unlikely to be something you'd ever want to do).

**Comment by tomwhite** [comment]
What @droazen says is correct. The `--numReducers` argument is not used when there is no shuffle. So `writeReadsSharded` should ignore it since it doesn't perform a shuffle (the output is already sharded either from the input partitioning, or from a shuffle in an earlier part of the the pipeline). Slightly counterintutively, `writeReadsSingle` does take the `--numReducers` argument since it does a shuffle to sort the reads in parallel, before stitching the files together.

Hope that makes sense.

**Comment by droazen** [comment]
Thanks @tomwhite for the explanation -- closing this ticket as invalid.

**Comment by lbergelson** [comment]
Thanks for the explanation.  I was interpreting it as "this will control the number of shards of output for anything that has output."
