### ISSUE TITLE
publish utils.test classes in separate artifact

### ISSUE THREAD

**Issue by lbergelson** [broadinstitute/gatk#1481]
Right now we publish test utils as part of the gatk artifact.  Since these are part of our main compilation unit it means we have several test libraries as compile dependencies instead of as test compile dependencies.  

If we separate our test utils into a separate group we can avoid having downstream tools gain various test dependencies if they don't want them.  (i.e. TestNG, MiniDFSCluster).

**Comment by lbergelson** [comment]
@magicDGS I have long wanted to do this, it's very sill to have TestNG in our uberJar...

**Comment by magicDGS** [comment]
There is any plan to do this soon? I'd love to contribute, but I'm not sure how to change the gradle.build to upload the artifacts properly....

**Comment by droazen** [comment]
The tickets we're planning to do soon are all tagged with the "beta" milestone -- this one is low priority with only very minor benefits, and so didn't make the cut. Unfortunately it's a task we'd have to take on ourselves, since it affects our maven artifacts. We can consider it for a future milestone after beta. Is this something that's causing an actual problem for you, or is it just a matter of principle that you don't want test dependencies in the main jar?

**Comment by magicDGS** [comment]
Thanks for the quick response, and I'm sorry that I cannot help this time.

I think that it may cause a problem in the future (that's why I opened the other issue), but currently it is fine.
