### ISSUE TITLE
IntelDeflater not used when gatk launched not from within gatk directory

### ISSUE THREAD

**Issue by akiezun** [broadinstitute/gatk#1692]
run from gatk directory
`./gatk-launch PrintReads -I src/test/resources/large/NA12878.RNAseq.bam -O tmp.bam`

you see `IntelDeflater`

now,  `cd ..`
`./gatk/gatk-launch PrintReads -I gatk/src/test/resources/large/NA12878.RNAseq.bam -O gatk/tmp.bam`

and you see `JdkDeflater`

**Comment by droazen** [comment]
`gatk-launch` is only designed to be used from within the gatk root directory -- perhaps it should error out if run from another location.

**Comment by droazen** [comment]
Also, we need a (separate) story for using `gatk-launch` with a fully-packaged jar.

**Comment by akiezun** [comment]
hmm, that's not good. I want to use `gatk-lanch` from anywhere

**Comment by lbergelson** [comment]
gatk-launch is intended to be invokable from anywhere, this is a bug

**Comment by droazen** [comment]
@lbergelson It is? Doesn't it rely on relative paths?

**Comment by lbergelson** [comment]
No. I fixed that as far as I can tell.  I have it in my path and I can invoke it from anywhere.  The problem here is that inteldeflator is being specified through a hardcoded system property baked into the gradle launch scripts.   We can fix it in gatk-launch by overriding it, or we can fix it properly by having the loader look in the classpath in the right place for it.

**Comment by akiezun** [comment]
this will be fixed by loading from the classpath #1903. keeping this ticket open so that we confirm that the problem is fixed.

**Comment by droazen** [comment]
@akiezun Is this one fixed now?

**Comment by akiezun** [comment]
it is fixed!
