### ISSUE TITLE
why is coveralls badge reporting 13%

### ISSUE THREAD

**Issue by akiezun** [broadinstitute/gatk#1749]
since a few weeks ago coveralls reports have become pretty useless ("increases coverage by  70%" or "decreased by 70%" etc) and the badge now shows 13% coverage. What's going on?

![image](https://cloud.githubusercontent.com/assets/1993519/14709629/a0dbf144-079f-11e6-9eb2-43de2f63d865.png)

**Comment by lbergelson** [comment]
Coveralls gets the coverage updates in pieces because travis does 2 separate builds. The main test build has something like 83% coverage and the CLOUD build only has 13% coverage.  Collectively they hit ~84%.  
Coveralls reports the most recent builds, but if both of them haven't finished yet, or if one of them failed to report coverage it will only show the partial coverage.

I don't know how to fix this exactly.  We could have the smaller build not report coverage data, but then we'd be missing the small but real additional coverage it includes.  

Travis only updates coveralls when a build finishes, and coveralls doesn't have any way of knowing how many builds there will be.  It can only react when it's updated.  It would be good if it had a system like github where travis reports "I'm building 2 things, wait for my updates" which would let it know when coverage data was ready or if it was still waiting, but I don't think we can implement that.  We can message the coverall's people and see if they have a solution but I think it's unlikely that they will.

**Comment by lbergelson** [comment]
Seems like other people have the same issue with no resolution 
https://github.com/lemurheavy/coveralls-public/issues/491
https://github.com/lemurheavy/coveralls-public/issues/156

**Comment by lbergelson** [comment]
Filed a feature request here:  https://github.com/lemurheavy/coveralls-public/issues/761

**Comment by droazen** [comment]
Solved by switching to codecov -- closing.
