### ISSUE TITLE
Safely parallelize the gatk and gatk-protected test suites

### ISSUE THREAD

**Issue by droazen** [broadinstitute/gatk#1769]
Travis test suites runtimes have been creeping upwards in both gatk and gatk-protected, and have now reached painful levels. Let's parallelize the test suite in a safe way that won't require us to make all test classes thread-safe. In the past, we successfully parallelized by test class, with one process per test class, and aggregated the results at the end.

**Comment by lbergelson** [comment]
@droazen Didn't we try this before and start getting intermittently failing tests?

**Comment by akiezun** [comment]
maybe it was FTZ ;)

**Comment by droazen** [comment]
@lbergelson Back in the GATK3 days, we had a plan in Bamboo that could run the test suite in parallel, with one job per test class, and aggregate the results at the end. This ran in ~15 minutes instead of 2-3 hours, but was prone to intermittent cluster-related failures. I'm wondering if there is a way in travis to do the same thing (or something similar), but in a more reliable way.

**Comment by lbergelson** [comment]
We can split the tests up into a bunch of build units, but we get rapidly diminishing returns since we spend minutes installing things and building the artifacts for every vm.  Travis doesn't have any notion of a build pipeline, so we can't say "build the artifact on 1 vm and then share it and run the tests on these 10 vms".  Since we have a hard limit of the number of VMs we can use at a time for DSDE ( currently 15) being less efficient is very bad news. ( We could of course pay for more...  I recently asked travis support if we could switch to an unlimited pay for usage model and they said no. )   We could also try optimizing wasted vm time by prebuilding dockers to run in, but that's additional complication.  (maybe not to much, might be worth it)

We also would need a scheme for dividing tests evenly between VM's.  I tried writing a testng test listener to distribute them between N nodes based on the hashcode of the test class, for use on circleci, but it fell over and exploded for some reason that I never debugged.  We could either debug it, or possibly split the tests by splitting the list of test files and then passing those in specifically.  (May run into character limits for command lines... )

Balancing it is going to be tricky though in any case since the tests are very unevenly expensive.  (We could probably manually balance it since there are a small number of slow tests and the rest are so fast they don't really matter)  

The easiest thing would be to set the test to run in parallel on their existing vm.  I can try turning it on again.  I remember it caused problems before though, which I assume we haven't addressed.  Each vm has 2 cores, so we might see some speedup.  I suspect we may be using both cores to some degree already, since performance nearly doubled when we switched from the 1 core to 2 core build machines.

We could probably build a more efficient pipeline on jenkins if we wanted since it does have a notion of pipelines.

**Comment by droazen** [comment]
Discussed in person with @lbergelson -- we decided to ask Broad IT to add more travis slots to our plan, and to use more jobs per build to bring test suite runtime down below 10 minutes.

**Comment by droazen** [comment]
Also, we should check that the maven dependencies are being cached properly per-branch (they don't seem to be at the moment)

**Comment by droazen** [comment]
An examination of the current test suite runtimes shows that the test suite could be split quite evenly along the utils/tools boundary.

**Comment by droazen** [comment]
We've resolved this by increasing our travis quota and adding additional matrix entries. We can parallelize the test suite further using this technique if we wish. Closing!

**Comment by droazen** [comment]
Related to https://github.com/broadinstitute/gatk/issues/969

**Comment by lbergelson** [comment]
As a note to future viewers.  As it currently stands enabling process-parallel tests on travis VM's doesn't work well because we don't have enough memory to run 2 simultaneous gatk instances.
