### ISSUE TITLE
Determine why FTZ gets unset during integration tests

### ISSUE THREAD

**Issue by droazen** [broadinstitute/gatk#1771]
We recently determined that the FTZ setting gets cleared during integration tests for unknown reasons. We temporarily fixed this by explicitly turning FTZ on in every call to `jniComputeLikelihoods()` (https://github.com/broadinstitute/gatk/pull/1764), but this might be inefficient, and even if it isn't it would be good to understand what's going on.

Without the fix in https://github.com/broadinstitute/gatk/pull/1764, if you run `HaplotypeCallerIntegrationTest`, the "consistent with past results" tests will either succeed or fail depending on whether they run first or not, and the failure is definitely due to FTZ somehow getting unset between tests.

**Comment by droazen** [comment]
For @gspowley. I can provide a means of reproducing this issue -- feel free to stop by my desk sometime and I'll show you.

**Comment by droazen** [comment]
@gspowley Steps to replicate:

1. Check out the `dr_runnable_haplotypecaller` branch (in this repo -- this would be too painful to reproduce with the version in gatk-protected).

2. Revert the change in https://github.com/broadinstitute/gatk/pull/1764

3. Run `HaplotypeCallerIntegrationTest`, watch it fail due to a mismatch on a single QUAL field (we've confirmed this is due to FTZ vs. no FTZ).

4. Rename one of the failing tests with a prefix like `aaa` so that TestNG will run it first, and watch it pass.

**Comment by gspowley** [comment]
@akiezun @droazen @lbergelson Found the issue with FTZ being cleared. The FTZ setting only applies to the thread where FTZ is set. When running tests in gradle/testng, each test is run in a new thread. However, the pairHMM native library is only loaded for the first HaplotypeCaller test, since code in `VectorLoglessPairHMM.java` prevents the library from being loaded more than once in the same JVM. This means only the first test uses FTZ.

A code change that loads the pairHMM native library for each test resolves the issue, and all `HaplotypeCallerIntegrationTest` tests pass. Another option to explore is setting FTZ in `main`.

**Comment by akiezun** [comment]
@gspowley can this be closed now?

**Comment by droazen** [comment]
If we close it, we'll have to add another ticket for setting FTZ in `main`

**Comment by akiezun** [comment]
Fine either way, as long as it's clear what remains to be done

**Comment by gspowley** [comment]
Right, we need to set FTZ in `main`. We will add code to GKL to set and check FTZ from Java.

**Comment by droazen** [comment]
Closing this one, since we have https://github.com/broadinstitute/gatk/issues/1572 to track the remaining work of setting FTZ in main()
