### ISSUE TITLE
SplitNCigarReads attempts to write reads out of order

### ISSUE THREAD

**Issue by meganshand** [broadinstitute/gatk#1865]
The output bam from SplitNCigarReads should be coordinate sorted, but when we have a read pair with one mapped read and one unmapped read, they can get out of order. It doesn't output the incorrect bam, but when the reads attempt to get written HTSJDK throws a an IllegalArgumentException for the out of order reads.

**Comment by lbergelson** [comment]
@meganshand I think this should be a trivial fix.  Try changing the call to `ReadUtils.createCommonSAMWriter` on line 120 so that presorted = false.

**Comment by meganshand** [comment]
You're right! I've made this change in #1853 and it seems to be working.

**Comment by lbergelson** [comment]
I suspect it will also make things substantially slower.  It will end up doing essentially a full sort of the bam file I believe.  Since we really only need local sorting to fix the problem this is a bit overkill.  If this is a bottleneck we can likely improve it, but it would be more work than just flipping the single flag.

**Comment by meganshand** [comment]
Since the simple fix is merged for now, can we close this ticket and open a new one if the speed ends up being a problem?

**Comment by lbergelson** [comment]
👍
