### ISSUE TITLE
Add support for command line arguments for annotations

### ISSUE THREAD

**Issue by akiezun** [broadinstitute/gatk#1880]
eg, `AS_InbreedingCoeff` needs a set of founders. Currently there's no way to provide it on the commandline and pass to the annotation. In gatk3, annotations had an initialize method. In gatk4, we initialize all annotations at creation. RankSum annotations have a similar problem with the --dither parameter.

**Comment by droazen** [comment]
For @cmnbroad and the 4.0 release milestone

**Comment by magicDGS** [comment]
I can contribute to this one too if I have time, because I will need it too. My suggestion is to create a plugin for the annotation engine. There are also some issues that will be nice to address/discuss too before I start contributing:

* __Allow custom packages for Annotations in VariantAnnotatorEngine__ (https://github.com/broadinstitute/gatk/issues/2155): I think that `VariantAnnotatorEngine` should be modify directly to use annotation classes and let the plugin deal with the reflection code to pick the instances for each String. This will help in my work trying to use `VariantAnnotatorEngine` with custom annotation classes, and let the package constraint to the plugin itself (and at some point, to the GATK configuration).
* __GenotypeAnnotations require GT, but some of them are computable without them__(https://github.com/broadinstitute/gatk/issues/1730): some of this annotations are useful for my work, which does not include samples with genotypes. Nevertheless, I cannot use them unless I hack my `Genotype` object beforehand. I think that this could be solved by setting a flag in the plugin and set the genotype annotation with it, to allow the computation for non-called samples.
* It would be nice to have in the plugin an argument collection (similar to #2355), allowing other implementations for the arg parsing part.

I will appreciate if these things are included/addressed at the same time, and I would love to contribute with some code to help you and be a beta-tester from the API point of view.

**Comment by droazen** [comment]
Agree that we should do the equivalent of what we did for read filters for annotations using the new plugin framework. Thanks for offering to help out on this one @magicDGS -- any contributions you're able to make here are very much appreciated!

**Comment by lbergelson** [comment]
I definitely agree that we need some sort of argument collection that can be used for the sorts of things that have default values + user defined values.  It's complicated and we don't want different behaviors for read filters, read transformers, annotations, etc.

**Comment by droazen** [comment]
Would probably be solved by https://github.com/broadinstitute/gatk/issues/3287

**Comment by droazen** [comment]
@jamesemery @ldgauthier suggests that the annotations that accept founder IDs should take a pedigree (.ped) file as an argument, and use the ped file to generate the founder IDs itself, instead of requiring the user to create a file with the founder IDs manually.

**Comment by droazen** [comment]
This was done -- closing.
