### ISSUE TITLE
jbwa updates 

### ISSUE THREAD

**Issue by yhcheng** [broadinstitute/gatk#1914]
Please update jbwa with the current github version. A patch for PPC64 is merged with jbwa now. Thanks!

**Comment by akiezun** [comment]
thanks @yhcheng - I think you should work with the developer of jbwa to create a packaged, pre-compiled binary (on all platforms supported) and put it on maven central so that gatk (and others) will be able to reference it. We will not be able to build it on all the platforms (we made 1 snapshot on linux+mac to unblock ourselves but the real solution is for jbwa to be hosted on maven central and have pre-build binaries. It would greatly help also if jbwa depended on https://github.com/broadinstitute/gatk-native-bindings and implemented the NativeLibrary interface). 

@droazen wdyt?

**Comment by droazen** [comment]
Yes, agreed @akiezun -- and as mentioned at group meeting this week, we can meet with you guys to provide guidance in setting this up in a way that GATK can easily use after we meet our June deadlines.

**Comment by lbergelson** [comment]
closed by #2078
