### ISSUE TITLE
Try out Intel PAT on dataproc

### ISSUE THREAD

**Issue by droazen** [broadinstitute/gatk#1986]

**Comment by jamesemery** [comment]
In order to get it running though you will need to install the following things on each machine using apt-get: gawk, sysstat, and perf-tools-unstable. Additionally as root, you will have to set the /proc/sys/kernel/perf_event_paranoid variable from 1 to 0. For these tasks it might be possible to automate these steps by updating the system image that is used to setup dataproc clusters.

In order to actually run and install PAT, you will need to download it from [here](https://github.com/intel-hadoop/PAT/tree/master/PAT) and add all the machines and ssh ports (including the master) in your cluster to the "ALL_NODES" setting in the config.template -> config file. You will also have to setup an SSH key to root on the cluster, which can be done with the command `gcloud compute ssh` and set the "SSH_KEY" variable in the config file to point to the google_compute_engine file in roots .ssh directory (public keys should have automatically been distributed to the other nodes). 

At this point you need simply input the command line command you wish to run into the "CMD_PATH" variable and run ./pat run. I recommend running a spark-submit job using yarn-client as master.

NOTE: the output will be a directory containing an excel spreadsheet and a bunch of data for each cluster. You will need to open the spreadsheet on a windows copy of excel and use "control+q" to run the macros that load the data.

**Comment by lbergelson** [comment]
A wiki entry describing how to do this in more detail is here: https://github.com/broadinstitute/gatk/wiki/Running-Intel-PAT-on-Dataproc
