### ISSUE TITLE
Create Spark partitioner that can efficiently load records for overlapping genomic regions

### ISSUE THREAD

**Issue by droazen** [broadinstitute/gatk#1988]
We have a somewhat urgent need for a Spark partitioner (or something similar) that can handle loading of records for regions that overlap. For example, we'd like to be able to have a partition with all reads in `1:900-2100`, and a separate partition with reads in `1:1900-3100`, and some reads in the overlapping regions would appear in both partitions. 

Such a partitioner is needed for several current GATK projects, including:

https://github.com/broadinstitute/gatk/issues/1639 Spark version of HaplotypeCaller (the prototype currently uses an inefficient `groupBy` operation to accomplish this)

https://github.com/broadinstitute/gatk/issues/1558 Make pileups in parallel on Spark 

It also might be needed for avoiding boundary artifacts in the SV caller.

**Comment by droazen** [comment]
@tomwhite Would you be able to work on this as your primary GATK ticket for alpha-3?

**Comment by tomwhite** [comment]
@droazen yes.

> the prototype currently uses an inefficient `groupBy` operation

Can you point me in the direction of the code for this please, @lbergelson?

**Comment by tomwhite** [comment]
Here's the work I've done so far to implement an overlaps partitioner: https://github.com/broadinstitute/gatk/compare/tw_overlap_partitioner.

The idea is to coalesce neighbouring partitions so that the task processing them can see (but not process) reads from neighbouring partitions. E.g. the task processing partition _i_ can see reads from partition _i-1_ and partition _i+1_. This is done using Spark 2's _coalesce_ method that takes a PartitionCoalescer: http://spark.apache.org/docs/latest/api/java/org/apache/spark/rdd/RDD.html#coalesce(int,%20boolean,%20scala.Option,%20scala.math.Ordering). In this PR I backported some of that logic so it works with Spark 1.6.

It turns out that this is not faster than the groupByKey, primarily since it has to scan over the input twice: first to find the extents of the reads in each partition, second to process each (coalesced) partition. It should be possible to avoid the first scan by just reading the first read in each partition and using a sequence dictionary to find the end points of contigs. This is a bit more involved, although it should be faster than groupByKey. (I tried caching the input to see if this helped, but it didn't.)

**Comment by tomwhite** [comment]
I was mistaken about this not being faster - I was using a counting function that Spark can optimise by pulling onto the map side so that the records don't go through the shuffle. I changed this to simply dump the processed reads so they have to go through the shuffle, and I got the following timings when processing a 121GB BAM file.

* With shuffle: 27 min
* No shuffle (two scans over input): 24.7 min (8% saving)
* No shuffle (one scan over input): 17 min (37% saving)

The version that does two scans is faster, but not hugely so. Removing a scan is possible, but requires the use of a sequence dictionary to find the end points of contigs. I've done this in the latest version of my branch (https://github.com/broadinstitute/gatk/compare/tw_overlap_partitioner), but there are more edge cases to test. Before I do this, however, it would be worth trying this approach with the Haplotype Caller to see if it works, and if it is appreciably faster. If the number of reads is filtered significantly so only a fraction go through the shuffle, then the performance gains will be smaller, and may not in fact be worth the increase in code complexity. @droazen, what do you think?

**Comment by jean-philippe-martin** [comment]
For what it's worth, if we go forward with NIO then we'll need the splitting index and then we should be able to offer this functionality for little additional effort (since we'd be writing a partitioner anyways to work with the splitting index). 
The naive (least-work) approach would read each partition independently so we wouldn't save on reads (but we'd still save from not having to go through a shuffle).
An optimized approach would be to read & parse the overlapping reads only once (since parsing is currently a non-trivial expense), but that'd be more work.

**Comment by tomwhite** [comment]
Fixed in #2190.
