### ISSUE TITLE
BwaSpark too verbose logging coming from jbwa

### ISSUE THREAD

**Issue by akiezun** [broadinstitute/gatk#2054]
when you run BwaSpark, a lot of logging info is produced, like this:

```
[M::mem_pestat] analyzing insert size distribution for orientation RR...
[M::mem_pestat] (25, 50, 75) percentile: (37, 57, 86)
[M::mem_pestat] low and high boundaries for computing mean and std.dev: (1, 184)
[M::mem_pestat] mean and std.dev: (63.93, 37.92)
[M::mem_pestat] low and high boundaries for proper pairs: (1, 233)
[M::mem_process_seqs] Processed 1316 reads in 1.312 CPU sec, 0.182 real sec
[M::mem_process_seqs] Processed 1316 reads in 1.365 CPU sec, 0.188 real sec
[M::mem_process_seqs] Processed 1316 reads in 1.479 CPU sec, 0.204 real sec
[M::mem_process_seqs] Processed 1316 reads in 1.721 CPU sec, 0.237 real sec
[M::mem_pestat] # candidate unique pairs for (FF, FR, RF, RR): (272, 0, 0, 329)
[M::mem_pestat] analyzing insert size distribution for orientation FF...
[M::mem_pestat] (25, 50, 75) percentile: (34, 57, 81)
[M::mem_pestat] low and high boundaries for computing mean and std.dev: (1, 175)
[M::mem_pestat] mean and std.dev: (59.82, 33.44)
[M::mem_pestat] low and high boundaries for proper pairs: (1, 222)
[M::mem_pestat] skip orientation FR as there are not enough pairs
[M::mem_pestat] skip orientation RF as there are not enough pairs
```

this should be reduced or removed or controllable somehow

**Comment by pgrosu** [comment]
Hi Adam,

That is the verbosity level that is performed by `bwa`.  So since [BWASpark](https://github.com/broadinstitute/gatk/blob/c9807a1a94a60b69e8184c1fcf3083516bb0a78b/src/main/java/org/broadinstitute/hellbender/tools/spark/bwa/BwaSpark.java#L47) launches `BwaSparkEngine` as follows:

```
final BwaSparkEngine engine = new BwaSparkEngine(bwaArgs.numThreads, bwaArgs.fixedChunkSize, referenceFileName);
```

and launches the alignment as follows:

```
final JavaRDD<GATKRead> reads = engine.alignWithBWA(ctx, unalignedReads, readsHeader);
```

That in turn calls the `align()` method within [BwaSparkEngine.java](https://github.com/broadinstitute/gatk/blob/9fb4d756afbbad58a7e709e2e9fd308983ad255b/src/main/java/org/broadinstitute/hellbender/tools/spark/bwa/BwaSparkEngine.java#L72):

```
final JavaRDD<String> samLines = align(shortReadPairs);
```

which then instantiates a new [BwaMem](https://github.com/broadinstitute/gatk/blob/9fb4d756afbbad58a7e709e2e9fd308983ad255b/src/main/java/org/broadinstitute/hellbender/tools/spark/bwa/BwaSparkEngine.java#L101) object:

```
final BwaMem mem = new BwaMem(index);
```

Since the BWA implementation at [lindenb/jbwa](https://github.com/lindenb/jbwa) is basically a direct call to Heng's BWA as a library, the BWA option for verbosity is set by the `-v` argument as noted [here](http://bio-bwa.sourceforge.net/bwa.shtml#3):

```
-v INT 	Control the verbose level of the output. This option has not been fully supported 
        throughout BWA. Ideally, a value 0 for disabling all the output to stderr; 1 for 
        outputting errors only; 2 for warnings and errors; 3 for all normal messages; 4 or 
        higher for debugging. When this option takes value 4, the output is not SAM. [3] 
```

This is used in Heng's [bwamem.c](https://github.com/lh3/bwa/blob/5961611c358e480110793bbf241523a3cfac049b/bwamem.c#L1224-L1226) file - and several other places - which generates the printout you see, as follows:

```
	if (bwa_verbose >= 3)
		fprintf(stderr, "[M::%s] Processed %d reads in %.3f CPU sec, %.3f real sec\n", __func__, n, cputime() - ctime, realtime() - rtime);
}
```

So I would just adjust the verbosity via the arguments to the level that is preferable.

Hope it helps,
Paul

**Comment by akiezun** [comment]
Thanks @pgrosu - I added a setter for verbosity to jbwa, see https://github.com/lindenb/jbwa/pull/12

**Comment by pgrosu** [comment]
@akiezun All roads lead to Rome :)

**Comment by lbergelson** [comment]
So it turns out that the changes that Adam made are not sufficient to set the verbosity properly.  In order to instantiate a BwaMem object we need to create the index object, which causes verbose output.  I believe the solution is to make set_verbosity static and call it before doing any jbwa operations.

**Comment by droazen** [comment]
Closing as obsolete, since we're no longer using jbwa.
