### ISSUE TITLE
Work with palantir and/or short variants team to validate GATK4 version of VQSR

### ISSUE THREAD

**Issue by droazen** [broadinstitute/gatk#2065]

**Comment by cmnbroad** [comment]
There is a [branch here](https://github.com/broadinstitute/gatk/pull/2182) that contains a temporary command line argument which forces VQSR to use the same initial random number generator condition as gatk3, so that it will produce the same results as gatk3 on the same inputs. However, once [this PR](https://github.com/broadinstitute/gatk/pull/2235) goes in, GATK4 will be out of sync with GATK3 even if this flag is used, at least until such a time as the PR is back ported to gatk3.

**Comment by cmnbroad** [comment]
Closing. Results from [PR](https://github.com/broadinstitute/palantir/pull/447) are [here](https://github.com/broadinstitute/palantir/tree/master/Analysis/vqsr_3_4_tie_out).
