### ISSUE TITLE
Validate GenotypeGVCFs walker for production use (with palantir and/or short variants team help)

### ISSUE THREAD

**Issue by droazen** [broadinstitute/gatk#2071]

**Comment by droazen** [comment]
@meganshand is handling this

**Comment by meganshand** [comment]
Some notes:

- Allele subsetting utils might account for some of these changes (I'll open a ticket for this)
- ExcessHet calculation might be the same but it's getting changed after the fact
- Some RankSums are being calculated in GATK4 where it's not in GATK3
- We should turn off jitter for QD to make sure they are the same

**Comment by meganshand** [comment]
Two follow ups from our meeting:

- Word count on the two output VCFs matches, so I'm hopeful that the sites are identical (this is mostly confirmed by GenotypeConcordance as well)

- I double checked the number of things in the ALT field (as a separate thing from my VariantsToTable version of AC) with cut and awk. After putting the results back into R I get an identical table to the one we saw before with AC:

![image](https://cloud.githubusercontent.com/assets/13020550/25764447/d0a42c02-31b5-11e7-90b1-2b68edd0d877.png)

**Comment by meganshand** [comment]
Rerunning with the OldQual vs OldQual (instead of NewQual vs NewQual) helped immensely (although there are still differences). Now none of the genotype calls change between GATK3 vs GATK4.

InbreedingCoefficient still has a large number of differences. The RankSums still have some NAs. Other than those two cases, most of the annotations still have differences just in smaller numbers than before.

I'll keep looking into the differences to see if they are significant (maybe some of them aren't). 

This does mean that when we want to switch to the NewQual in production we will have to compare the output between GATK4 Old Qual and GATK4 New Qual to make sure all of the changes are desirable.

**Comment by meganshand** [comment]
Things look mostly tied out at this point. There are two annotations that don't match which I'll open separate issues for: QUAL and InbreedingCoeff. QUAL also effects some QD values. Neither of these seem like significant differences:

![image](https://cloud.githubusercontent.com/assets/13020550/26456169/493ed796-413a-11e7-8fd3-66b61a61ca3b.png)

![image](https://cloud.githubusercontent.com/assets/13020550/26456152/3f23a282-413a-11e7-9305-55bdb1e0f7ec.png)

I'll write a full report in palantir and provide a link here. I'll document the bugs we've accounted for there.

**Comment by droazen** [comment]
Woohoo, thanks @meganshand !

**Comment by droazen** [comment]
@meganshand How close are we to being able to close this ticket?

**Comment by lbergelson** [comment]
Tied out for old qual!  Woo!  New qual still needs work.
