### ISSUE TITLE
HaplotypeCaller/Mutect2: vcf header missing the sequence dictionary

### ISSUE THREAD

**Issue by takutosato** [broadinstitute/gatk#2202]

**Comment by droazen** [comment]
@cmnbroad Could you have a quick look at this one? The problem is that the output vcf for HaplotypeCaller/Mutect2 is missing a sequence dictionary in the header, even though the input bam(s) have a full dictionary.

First place to check is `HaplotypeCallerEngine.makeVCFWriter()` in gatk-protected (and the equivalent method for Mutect2), to make sure the reads dictionary is getting propagated to the VCF/GVCF writer properly.

**Comment by droazen** [comment]
(moderately urgent, by the way)

**Comment by cmnbroad** [comment]
Looks like we're just not propagating the reads dictionary to the header. PR is [here](https://github.com/broadinstitute/gatk-protected/pull/740).

**Comment by droazen** [comment]
Closing, fixed in https://github.com/broadinstitute/gatk-protected/pull/740
