### ISSUE TITLE
Upgrade to Spark 2.0.2

### ISSUE THREAD

**Issue by droazen** [broadinstitute/gatk#2277]
This release potentially fixes a bug that the SV team (specifically @SHuang-Broad) encountered.

**Comment by droazen** [comment]
Note that we can't actually run on dataproc with 2.0.2 until Google creates an image with it. Looks like even the "preview" image doesn't have 2.0.2 yet.

**Comment by SHuang-Broad** [comment]
Update:
The problem seemingly was caused by the logging part in Spark (thanks to Carlos H. Andrade Costa from IBM for pointing this out).

So a temporary solution that works for now is to add the following lines in the initialization script for spinning up the cluster to turn off logging, 

```bash
sudo sed -i -- 's/log4j.rootCategory=INFO, console/log4j.rootCategory=OFF, console/g'\
                     /etc/spark/conf/log4j.properties
sudo sed -i -- 's/log4j.logger.org.apache.spark=WARN/log4j.logger.org.apache.spark=OFF/g'\
                     /etc/spark/conf/log4j.properties
sudo sed -i -- 's/hadoop.root.logger=INFO,console/hadoop.root.logger=OFF,console/g'\
                    /etc/hadoop/conf/log4j.properties
```

assuming the cluster was created with 

    --image-version preview


I test run the tool where I observed the bug (`FindBreakpointEvidenceSpark`) twice on a cluster created & initialized this way and didn't observe any `ConcurrentModificationException`.

**Comment by SHuang-Broad** [comment]
@droazen I think we could still leave this open and when Google updates the preview image on dataproc to 2.0.2, I'll go back and test it again without messing the logging level.

**Comment by SHuang-Broad** [comment]
Update:

Dataproc's preview image was just updated to use Spark 2.0.2. 
The specific `CocurrentModificationException` is gone after this upgrade, but a new IO exception emerges, which might be related to the problem described [here](http://stackoverflow.com/questions/29781489/apache-spark-network-errors-between-executors).
Needs more testing.

**Comment by lbergelson** [comment]
this was is done by #2294
