### ISSUE TITLE
Need additional VQSR integration tests

### ISSUE THREAD

**Issue by cmnbroad** [broadinstitute/gatk#2290]
We should try to add tests for:

- mixed-mode (SNP and Indel)
- a test that uses more than one input file (this could be the same as the mixed mode test)
- a test that uses an aggregate input

**Comment by ldgauthier** [comment]
So I've encountered users that supply VariantRecalibrator with multiple inputs (which I didn't know it could do), and I have a branch with a new test for that, but I've never seen anyone use the `--aggregate` argument.  That argument has weird behavior in that, since those are not "driving variants", sites that appear in that file that do not appear in the input aren't used.  @droazen what do I have to do to get a +1 do remove that arg?

**Comment by droazen** [comment]
@ldgauthier If you can certify that none of our production pipelines use `--aggregate`, and that you don't know of any users who rely on it, and that the intended functionality provided by the argument doesn't fill an important use case, then +1 to removing it

**Comment by ldgauthier** [comment]
#6570 addresses BOTH mode and multiple inputs

The only thing we aggregate in production is bams.  I can't find any post on the forum that mentions using the --aggregate arg, so I think we can take it out -- see #6809

**Comment by ldgauthier** [comment]
I was wrong, there is a test for --aggregate because I broke it after I took out the arg.  :-D  In that case, let's leave the arg and this issue is resolved.
