### ISSUE TITLE
Implement short-running dataproc regression tests on travis

### ISSUE THREAD

**Issue by droazen** [broadinstitute/gatk#2298]
We need some short-running regression tests that run on dataproc in travis, to supplement the large-scale tests in gatk-jenkins.

**Comment by droazen** [comment]
@davidbernick Since you set up the jenkins tests for us, would you be able to help us out with this ticket? We've gotten weary of catching Spark regressions post-merge with jenkins, and want to set up fast dataproc-based tests in travis that run on every pull request, and just run simple Spark tools like PrintReadsSpark to try to catch at least the most basic kinds of breakage before a branch is merged.

**Comment by davidbernick** [comment]
I haven't worked with Travis much -- so it'll be slower for me. I'd rather do this in Jenkins if that's ok. To do "fast" dataproc tests, I need a script that will run fast. For our current tests, I have:  

1. Grab gatk and make a docker. That takes about 10 minutes. It needs to be a "fresh" docker to match the PR.   

2. 
```
./gatk-launch MarkDuplicatesSpark \
          --shardedOutput true \
          -O /scratch/tmp.md.bam \
          --numReducers 0 \
          --apiKey $APIKEY \
          -I  $bamIn \
          -- \
          --sparkRunner GCS \
          --driver-memory 8G \
          --cluster $CLUSTERNAME \
          --executor-cores 3 \
          --executor-memory 25G \
          --conf spark.yarn.executor.memoryOverhead=2500"
```
That's what I currently launch for Spark Tests. If you give me something that you know will run faster (with data locations to run it against to make sure it runs faster), I can have a per-PR test that runs in Jenkins in 10 minutes (docker)+however-long-the-command-takes.

**Comment by droazen** [comment]
@davidbernick It needs to be done in travis, I'm afraid, otherwise it's not going to solve our problem of people not noticing regressions until after merge.

I'll craft a fast-running test case for you and post it here.

**Comment by davidbernick** [comment]
Well I just did a test for @LeeTL1220 that prevents merge until it passes the Jenkins test.

**Comment by droazen** [comment]
We'd prefer something tightly integrated with our main test suite in travis, and reserve jenkins for long-running/nightly tests. Having to deal with two CI environments for pull requests is too cumbersome.

**Comment by droazen** [comment]
I'll add: I suspect that this could get done pretty quickly/painlessly if @lbergelson (our travis expert) and yourself (who has set up tests like this before many times) got together in a room and hashed it out. Recommend setting up a meeting with @lbergelson at a time that's convenient in the next week or two. I'll post command lines here by early next week.

**Comment by davidbernick** [comment]
There are two issues with running this on Travis:
1. Spinning up Dataproc requires access to a bunch of secrets -- namely API Keys and Google Service accounts (usually in the form of a JSON). Travis allows for encrypted Secrets, so I'm okay with them existing there,  but they are ONLY available to PRs that originate from the repo (ie, no forked PRs have access to them). So doing this in Travis would only work from your local PR. Is that acceptable? If not, no Travis that I can think of.

2. We don't want ANYONE to just come in and launch these tests as they are $ expensive (spinning up clusters in Google). If this activates with any PR that comes in, then we can easily run up a bill by any malicious A-hole who feels like launching a bunch of PRs. I know that when I was 14 or so I would have probably done that if I discovered it. Jenkins has some mechnaisms to prevent run away PR tests. Does Travis? I didn't find any info on that...

Happy to hash it out in a room (and sorry it took this long to get to. Pester Banks if you need my attention faster otherwise Workbench and Security get first dibs). But be aware of these issues with Travis and running dataproc.

**Comment by droazen** [comment]
The tests would be very short-running, so each run should be cheap. Most of the runtime will be just spinning up the cluster. If someone malicious opened up a crazy number of PRs, he would at least quickly hit our travis quota limit which would slow him down considerably. We can look into whether other mechanisms exist on travis to deal with this sort of hypothetical situation.

We do ideally want these tests to work with forked PRs, but if that's simply not going to be possible on travis then we'll obviously have to choose between having these tests in the same place as all of our other PR-related tests on travis and just skipping them for forked PRs, vs. having them in jenkins and requiring those making and reviewing PRs to deal with/check both CI environments. Let's meet early next week to chat about this issue and come to a decision.

**Comment by droazen** [comment]
Or, alternatively, keep the cluster-based tests in jenkins, but make the jenkins tests more visible on github.

**Comment by droazen** [comment]
This is done -- closing.
