### ISSUE TITLE
Allow sane combinations of enable/disable plugin arguments, disallow insane combinations

### ISSUE THREAD

**Issue by droazen** [broadinstitute/gatk#2377]
We should audit the plugin system (and add tests) to ensure that crazy combinations of enable/disable arguments (like `--readFilter` and `--disableReadFilter`) are disallowed, while useful combinations are permitted. Here's my attempt at an initial proposal:

`--enable X --disable X`: crazy, should be an error

`--enable X --enable X`: error

`--disable X --disable X`: error

`--enable X when X is already on by default in the tool`: warning, but should be allowed -- this is useful for pipeline authors to guarantee that a particular filter will be on, even if tool defaults change over time. We should make sure that the filter is only actually applied ONCE, however.

`--disable X when X is not enabled by default in the tool`: warning, but should be allowed -- this is useful for pipeline authors to guarantee that a particular filter will be off, even if tool defaults change over time.

**Comment by droazen** [comment]
For @cmnbroad. The current behavior may or may not be consistent with the above -- even if it is, we should add tests to ensure it stays that way.

**Comment by magicDGS** [comment]
This is the purpose of all my work here. The current behavior is the following (if already there, links point to the code):

- `--enable X --disable X` [throws `CommandLineException`](https://github.com/broadinstitute/gatk/blob/master/src/main/java/org/broadinstitute/hellbender/cmdline/GATKPlugin/GATKReadFilterPluginDescriptor.java#L208-L214) as expected. There is also a test covering this in [`ReadFilterPluginUnitTest`](https://github.com/broadinstitute/gatk/blob/35b1253510c5a63c90fd28aff4f2753cdf9e5071/src/test/java/org/broadinstitute/hellbender/engine/filters/ReadFilterPluginUnitTest.java#L267-L274))
- `--enable X --enable X` does not throw anything yet. I did a PR last week for fix (test included): #2373 
- `--disable X --disable X` does not throw anything yet. I can add this behavior to the PR for enabling twice the same filter
- `--enable X when X is already on by default in the tool` [log a warning](https://github.com/broadinstitute/gatk/blob/master/src/main/java/org/broadinstitute/hellbender/cmdline/GATKPlugin/GATKReadFilterPluginDescriptor.java#L223-L229). There is a [test exercising this path](https://github.com/broadinstitute/gatk/blob/35b1253510c5a63c90fd28aff4f2753cdf9e5071/src/test/java/org/broadinstitute/hellbender/engine/filters/ReadFilterPluginUnitTest.java#L401-L409).
- `--disable X when X is not enabled by default in the tool` [log a warning](https://github.com/broadinstitute/gatk/blob/master/src/main/java/org/broadinstitute/hellbender/cmdline/GATKPlugin/GATKReadFilterPluginDescriptor.java#L216-L221). There is no test for this path, but I included one in #2360

**Comment by magicDGS** [comment]
I want to point out a bug regarding the read plugin that I reported in #357 (and fix with in #2359): disable a default filter with arguments blows up as a `CommandLineException` as if the user provided the arguments for a disabled filter. This is quite important in this regard of insane combinations.

**Comment by magicDGS** [comment]
I realized that the `--disable X --disable X` cannot blow up because the argument is a `Set`. Every repeated argument is hidden from the plugin. Either the signature should change to throw the exception or ignore that issue.

**Comment by cmnbroad** [comment]
I don't see any reason that we need to make redundant disable be an error, since there is no harm in it. (We chose to throw for redundant **enable** because it has a small perf ramification; also, we can't just prune it out since if the redundant filter has args there will be ambiguity).

**Comment by lbergelson** [comment]
@cmnbroad We seem to have a bit of a bug where you can disable a read filter that doesn't exist and get a warning instead of an error:

@droazen This is why that command line was working in the wdl.

`--disableReadFilter asdfasdf`  -> `Disabled filter (asdfasdf) is not enabled by this tool`

I opened #2397  to track it.

**Comment by magicDGS** [comment]
I will do a big PR with a commit for each of the issues that we found in the plugin, and including tests. Although the plugin interface is going to change in Barclay, I think that before that the PR should setup all the tests for the issues to ensura that the change does not broke anything. Any opinion on this, @cmnbroad, @droazen, @lbergelson?

**Comment by cmnbroad** [comment]
@magicDGS Yes, I think it would be much simpler if we had one PR with all of the fixes for the validation rules (and related help issues). The extensibility changes we've been discussing should be a separate PR.

**Comment by cmnbroad** [comment]
Summary of the set of rules (implemented in @magicDGS branch):

Throw if:

- any filter is enabled or disabled by the user more than once
- any filter is enabled *and* disabled by the user
- a non-existent filter is disabled by the user
- a non-existent filter is enabled by the user
- arguments are provided for a filter that is also disabled (exception for the case where the argument is for a default filter; due to https://github.com/broadinstitute/barclay/issues/23, we temporarily only warn)

Warn if:

- a filter (that exists) is disabled by the user, but is not enabled by the tool
- a filter is enabled by the user but the tool enables it by default
- arguments are provided for a default filter that is also disabled (this should throw, but due to https://github.com/broadinstitute/barclay/issues/23, we temporarily only warn)

**Comment by cmnbroad** [comment]
Closed via #2401.
