### ISSUE TITLE
Remove all code paths in engine (and tests) that use an explicit Google API key

### ISSUE THREAD

**Issue by droazen** [broadinstitute/gatk#2402]
NIO uses the gcloud system authentication, so we shouldn't need this anymore.

**Comment by droazen** [comment]
For @jean-philippe-martin

**Comment by jean-philippe-martin** [comment]
Unless, that is, we want to use the API key to allow non-logged-in access to public data?

**Comment by droazen** [comment]
I don't think so -- using the API key introduces all sorts of security issues with sanitizing command lines. I think we just want to rely on the default Google credentials.

**Comment by lbergelson** [comment]
👍 to removing the api key.  We're leaking them all over the place...  We could optionally go back to accepting a key file as a form of authentication which is much less dangerous.

**Comment by jean-philippe-martin** [comment]
OK. So my understanding of the plan here is that 
today we read BAM files 3 different ways:
1. Using hadoop when on hdfs and using Spark
2. google-genomic's `BAMIO` with Spark for BQSR and related code
3. `NIO` -> gatk `ReadsDataSource` -> htsjdk BAM reader, for non-Spark tools

The code in 2. uses `AuthHolder` which in turn takes in an API key. In order to get rid of the API key we're changing the code in 2. to use the method from 3. to read the BAM files on the cloud.

**Comment by jean-philippe-martin** [comment]
In particular that means we're leaving in the code that talks to the Google Genomics Reference API (the `ReferenceAPISource` class), which also uses the API key. So at least in this stage we're not going to literally remove all instances of the API key (as the issue description suggests).

**Comment by droazen** [comment]
@jean-philippe-martin Is this one done (modulo the `ReferenceAPISource class)?

**Comment by jean-philippe-martin** [comment]
[I see dead code](http://www.imdb.com/title/tt0167404/quotes?item=qt0249072), still. There's more work to do. For example `MetricsUtils.saveMetrics` takes in an authHolder but then doesn't use it - I need to remove that and transitively remove it from all the functions that only take one in to pass it there.
