### ISSUE TITLE
Run NIO benchmarks on single-core instances

### ISSUE THREAD

**Issue by droazen** [broadinstitute/gatk#2424]
As discussed at methods meeting

**Comment by droazen** [comment]
Note that the single-core instances might have hyper-threading (we should find this out as part of this ticket).

**Comment by droazen** [comment]
For @jean-philippe-martin

**Comment by jean-philippe-martin** [comment]
The n1-standard-1 instance we'll be using has a single hyper-thread available to it from either a
2.6 GHz Intel Xeon E5 (Sandy Bridge), 2.5 GHz Intel Xeon E5 v2 (Ivy Bridge), 2.3 GHz Intel Xeon E5 v3 (Haswell), or 2.2 GHz Intel Xeon E5 v4 (Broadwell). [Source](https://cloud.google.com/compute/docs/machine-types)

**Comment by jean-philippe-martin** [comment]
Done. Full results are on the internal presentation slides. The summary table follows:

| speedup vs async on a 1-core machine | slice | whole | intervals |
|-------------|----------|---------|----------|
| vcf | 0.91| 1.40| 0.57|
| bam (exome)| 40.42| 1.06| 1.02|
| bam (wgs)| 111.18| 1.21| 0.99|

This table compares the execution time of a single machine running PrintReads or SelectVariants, getting its input either directly from the Google bucket (NIO), or by first copying it with gsutil and then running off the local disk (with the async option turned on, allowing eager decompression of the stream - a feature the NIO code does not have). Each experiment is run four times, and each number here represents the ratio of two such experiments. Numbers larger than 1 indicate that NIO was faster.

Each row is a different input file: vcf, small bam (exome), large bam (whole genome).

Each column is a selection of what to read from the file (via the `-L` argument): a megabase slice, the whole file, or a long list of intervals.

The NIO code relies heavily on prefetching, so it doesn't perform well with the many disjoint accesses of the right column. When processing only a small part of the (already small) vcf file, NIO loses out to copy + local processing. Everywhere else the direct-to-bucket "NIO" code performs quite well, up to 111x faster than the "copy then process" approach.

I also ran the full set with async disabled. It makes a difference but NIO still wins and loses at the same places by similar margins (in particular the 111x win remains).

**Comment by lbergelson** [comment]
Thanks JP.  This is really Interesting.

Unfortunately I think the vcf slice is the major motivating use case.  How
large was that vcf?  Do you think there's anything we can do to get some
speedup with NIO for small files when we only have 1 core?  I'm not totally
clear on how data transfer over a network interacts with thread waiting.
If we are receiving data over the internet does that need cpu time or is
that handled asynchronously by the network card?  I.e. if we're prefetching
in on thread, can that thread be asleep or is it consuming cpu time the
whole time a transfer is in progress?

I suspect that the immediate next question people are going to have is "4
cores are inefficient, 1 core is slow, how about 2 cores...".

I'm curious about async and vcf.  The updated slides show vcf with async on
being ~40% slower than with async off.  That's
setting use_async_io_write_tribble on / off?  It looks like we should just
disable it if we're on a single core, but by default we have it on.

**Comment by jean-philippe-martin** [comment]
The VCF input I used is dbsnp_138.b37.excluding_sites_after_129.vcf, at 2.3 GB.
It takes 0.47min to copy over. The local computation itself is only a few seconds:
 0.04min on the 4-cpu machine,
 0.05min on the 1-cpu machine,
 0.07min on the 1-cpu machine when ASYNC is on.

Running with NIO takes:
 0.21min on the 4-cpu machine,
 0.59min on the 1-cpu machine,

A lot of the IO is done by the network card or operating system, so while we're prefetching on that thread, other threads can make progress. Not all of it, of course, so we pay a little bit of a cost as we have to switch between threads. The best scenario is one where there is both a lot of IO and a lot of computation, so we win most by overlapping them. The VCF case here is borderline because there is so little computation.

The fact that we can make progress during IO is confirmed by the "whole file" case, where doing the reading and computation in parallel is faster than doing the copy first, then compute - even on a single-core VM.

You're asking about `use_async_io_write_tribble`. I didn't set it explicitly and my logs show it was turned off in every experiment:
`INFO  SelectVariants - Defaults.USE_ASYNC_IO_WRITE_FOR_TRIBBLE : false`

I can certainly run more experiments if you'd like; let's start a private discussion for that.

**Comment by jean-philippe-martin** [comment]
After running new experiments: 

For the vcf input, if we disable the caching (for the slice case) or reduce it (for the other two) then we get better results, to the point that NIO is faster than copy+local for the slice and whole cases.
