### ISSUE TITLE
Update Protocol Buffer dependency to 3.0.0

### ISSUE THREAD

**Issue by kdatta** [broadinstitute/gatk#2437]
GATK4 depends on a beta release of Protocol Buffer 3.0.0, specifically "3.0.0-beta-1" because other versions break the tests depending on hadoop.dfs.minicluster.utils. Eventually, we must move up to a stable version of protocol buffers i.e. either .3.0.0 or higher.

**Comment by droazen** [comment]
@tomwhite Have time to look at this one? Not urgent at all.

**Comment by lbergelson** [comment]
I remember there being discussion about this when it was included.  It was added by @jean-philippe-martin, I think there was a conflict between the version of protobuffers used by hadoop and the version used by the NIO dependency and this was the only one that worked for both.  I could be misremembering though, and it's possible that since we're using the shaded NIO now that the proto buffer dependency in it is shaded and we no longer need to force any version.

**Comment by droazen** [comment]
@jean-philippe-martin Care to weigh in?

**Comment by jean-philippe-martin** [comment]
Louis is right. At the time I think I only had 3.0.0-beta-2 as the other option and that made Hadoop break, so I had to go with 3.0.0-beta-1. There may now be a more recent version of Hadoop we can switch to, perhaps, that depends on a more recent version of protobuf ?

**Comment by lbergelson** [comment]
It looks like hadoop is on version 2.5.0, and it doesn't look like either of the upcoming hadoop version, 2.8 or 3.0.0 is going to change it.  https://github.com/apache/hadoop/blob/release-2.8.0-RC1/hadoop-project/pom.xml
