### ISSUE TITLE
VariantsSparkSinkUnitTest hanging

### ISSUE THREAD

**Issue by tedsharpe** [broadinstitute/gatk#2490]
On my Mac, and on my Linux desktop machine at home, but not on Travis, I consistently fail to run unit tests.  The precise location of the failure varies somewhat, but it's always in this vicinity:

```Test: Test method testWritingToFileURL[0](~me/IdeaProjects/gatk/src/test/resources/Homo_sapiens_assembly19.dbsnp135.chr1_1M.exome_intervals.vcf, .vcf)(org.broadinstitute.hellbender.engine.spark.datasources.VariantsSparkSinkUnitTest) produced standard out/err: 14:49 DEBUG: [kryo] Write object reference 809: INFO```

The failing test makes my poor little machine's fan run like mad for a while, and then everything gets very quiet, but the test never returns.

**Comment by droazen** [comment]
Hmm, @cmnbroad is this similar to what you've been seeing lately?

**Comment by cmnbroad** [comment]
Yes, this looks very similar to what I'm seeing. The VariantSparkSinkUnitTests run fine on their own. When the whole test suite is run though, an OOM error is thrown when VariantSparkSinkUnitTests run:

java.lang.OutOfMemoryError: GC overhead limit exceeded
        at org.gradle.internal.remote.internal.hub.MethodInvocationSerializer$MethodInvocationReader.read(MethodInvocationSerializer.java:120)
        at org.gradle.internal.remote.internal.hub.MethodInvocationSerializer$MethodInvocationReader.read(MethodInvocationSerializer.java:99)
        at org.gradle.internal.serialize.kryo.TypeSafeSerializer$1.read(TypeSafeSerializer.java:34)
        at org.gradle.internal.remote.internal.hub.InterHubMessageSerializer$MessageReader.read(InterHubMessageSerializer.java:66)
        at org.gradle.internal.remote.internal.hub.InterHubMessageSerializer$MessageReader.read(InterHubMessageSerializer.java:52)
        at org.gradle.internal.remote.internal.inet.SocketConnection.receive(SocketConnection.java:78)
        at org.gradle.internal.remote.internal.hub.MessageHub$ConnectionReceive.run(MessageHub.java:250)
        at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:54)
        at org.gradle.internal.concurrent.StoppableExecutorImpl$1.run(StoppableExecutorImpl.java:40)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)
    13:37 DEBUG: [kryo] Read object reference 986: reference=GRCh37.3
Test: Test method testWritingToFileURL[0](/Users/cnorman/projects/gatk/src/test/resources/Homo_sapiens_assembly19.dbsnp135.chr1_1M.exome_intervals.vcf, .vcf)(org.broadinstitute.hellbender.engine.spark.datasources.VariantsSparkSinkUnitTest) produced standard out/err: 13:37 DEBUG: [kryo] Read object reference 203: contig=<ID=20,length=63025520,assembly=b37>

**Comment by cmnbroad** [comment]
@gspowley Can you take a look. This problem started happening with https://github.com/broadinstitute/gatk/commit/dfa9cf1a420490285b7be7917082222a07e2b042. I can pretty reliably move back to the previous commit and it goes away. It always surfaces in the VariantSparkSinkUnitTests, but it seems to be the result of a cumulative effect since AFAICT it only happens when running the full test suite via "./gradlew clean test".

I tried changing the default values of useJdkInflater and useJdkDeflater to true, and I still get the same problem. Interestingly, disabling all of the tests in IntelInflaterDeflaterIntegrationTest seems to reliably fix it (even with useJdkInflater/Deflater set to false), so I'd start there. If thats the culprit, it might explain why we don't see this in travis since we run the unit tests and integration tests separately there.

**Comment by gspowley** [comment]
Thanks for the details @cmnbroad. I'm looking into it.

**Comment by gspowley** [comment]
I reproduced various out of memory errors in a Linux VM with 4G of RAM, both with the `IntelInflaterDeflaterIntegrationTest` enabled and disabled.

Most resulted in the kernel killing the Java process, like this one (from `dmesg`):
```
[38425.759992] Out of memory: Kill process 10295 (java) score 747 or sacrifice child
[38425.759998] Killed process 10295 (java) total-vm:7885212kB, anon-rss:3250892kB, file-rss:0kB
```

Some were caught by the JVM, like this one:
```
#
# There is insufficient memory for the Java Runtime Environment to continue.
# Native memory allocation (mmap) failed to map 90177536 bytes for committing reserved memory.
# Possible reasons:
#   The system is out of physical RAM or swap space
#   In 32 bit mode, the process size limit was hit
# Possible solutions:
#   Reduce memory load on the system
#   Increase physical memory or swap space
#   Check if swap backing store is full
#   Use 64 bit Java on a 64 bit OS
#   Decrease Java heap size (-Xmx/-Xms)
#   Decrease number of Java threads
#   Decrease Java thread stack sizes (-Xss)
#   Set larger code cache with -XX:ReservedCodeCacheSize=
# This output file may be truncated or incomplete.
#
#  Out of Memory Error (os_linux.cpp:2627), pid=20484, tid=139679452493568
#
# JRE version: Java(TM) SE Runtime Environment (8.0_72-b15) (build 1.8.0_72-b15)
# Java VM: Java HotSpot(TM) 64-Bit Server VM (25.72-b15 mixed mode linux-amd64 compressed oops)
# Failed to write core dump. Core dumps have been disabled. To enable core dumping, try "ulimit -c unlimited" before starting Java again
#
```

Here's my theory of what's happening. The `maxHeapSize` for test JVMs is set to 4G in `build.gradle`:
```
    maxHeapSize = "4G"
```

A 4G max heap size is too high for systems with 4G of RAM, because the Java heap grows until the system runs out of memory. If we decrease `maxHeapSize`, the GC should prevent the Java heap from growing too large, with the trade-off of more GC calls.

I changed the `maxHeapSize` to `2G` and all of the tests completed on my same VM with 4G of RAM.

BTW, I did check for GKL related memory issues, but didn't find anything. I think we will always hit this issue as the test suite grows.

Thoughts?

**Comment by droazen** [comment]
@cmnbroad @tedsharpe Do you guys have only 4 GB of physical memory on the machines where you saw the failures?

**Comment by tedsharpe** [comment]
16 on my Mac. 12 on my Linux desktop.  Nonetheless, I think @gspowley is probably onto something.

**Comment by gspowley** [comment]
For more data, I ran some experiments on gcloud today. These instances are only running GATK tests, so they should have more free memory available compared to a laptop or desktop.

| VM memory | maxHeapSize | Out Of Memory? |
|:---------:|:---------------:|:------------------:|
| 13 GB | 4 GB | No |
| 7.5 GB | 4 GB | No |
| 3.75 GB | 4 GB | Yes |

Setup and test script:
```bash
# install JDK
sudo apt install -y default-jdk

# install git lfs
curl -s https://packagecloud.io/install/repositories/github/git-lfs/script.deb.sh | sudo bash
sudo apt install -y git-lfs
git lfs install

# install R
sudo apt install -y r-base r-base-dev

# clone GATK, build, and test
git clone https://github.com/broadinstitute/gatk.git
cd gatk
./gradlew clean test |& tee test.log
```

**Comment by cmnbroad** [comment]
@gspowley Thanks for looking into this. I suppose its possible that we've just gone over some threshold in the normal course of things, but I'm still a bit skeptical. I'm going to do a bit more analysis/testing and see if I can get any more insight.

**Comment by gspowley** [comment]
@cmnbroad Can you please try your tests with this snapshot of GKL:

https://oss.sonatype.org/content/repositories/snapshots/com/intel/gkl/gkl/0.4.1-SNAPSHOT/

This fixes the GC issues in `IntelInflater` and `IntelDeflater` we discussed today.

**Comment by cmnbroad** [comment]
Sure - will give it a try.

**Comment by cmnbroad** [comment]
@gspowley The first test run seems to still produce the original problem (the tests hang in the same spot). The change may have fixed #2535 , but I'll do a couple more some more test runs and see what other results I get.

**Comment by cmnbroad** [comment]
I've run on two separate machines with the snapshot - still seeing the hanging while running gradle tests. Haven't seen #2535 though.

**Comment by gspowley** [comment]
Glad to hear the GC fix helps with #2535.

If I could reproduce the hang, I would try to narrow in on @cmnbroad's observation above "_disabling all of the tests in IntelInflaterDeflaterIntegrationTest seems to reliably fix it_."

- Is the problem caused by `IntelInflaterDeflaterIntegrationTest.testIntelInflaterDeflaterWithPrintReads` only?
- If so, what happens if we removed the `setDefault*Factory` calls?
- What happens if we don't call `assertSamsEqual`?

At some point in these experiments, the test is not useful, but hopefully it will tell us where to look for the problem.

**Comment by gspowley** [comment]
I was able to reproduce a hang in `VariantsSparkSinkUnitTest` by running a test group with only `IntelInflaterDeflaterIntegrationTest` and `VariantsSparkSinkUnitTest`.

Removing this line in `testIntelInflaterDeflaterWithPrintReads` resolved the hang on my system:
```java
   args.add("--verbosity"); args.add("DEBUG");
```

After setting the verbosity to DEBUG here, all subsequent tests use the same level of verbosity. This generated >1G of log information during `VariantsSparkSinkUnitTest` before hanging.

@cmnbroad, can you please try running on your system with the verbosity setting removed in `IntelInflaterDeflaterIntegrationTest.testIntelInflaterDeflaterWithPrintReads`?

**Comment by cmnbroad** [comment]
@gspowley That seems to do it (I also needed to use the GKL snapshot library, otherwise I see the malloc bug more frequently), but I was able to run the whole test suite on both of my laptops with this.

**Comment by gspowley** [comment]
Great! We'll make a PR to bump the GKL version and remove the DEBUG log level setting.

**Comment by droazen** [comment]
Whew -- glad this was something simple!
