### ISSUE TITLE
GenotypingEngine.isVcCoveredByDeletion() is stateful (modifies upstreamDeletionsLoc) and should not be

### ISSUE THREAD

**Issue by droazen** [broadinstitute/gatk#2537]
It's bad practice to have predicate/boolean-valued methods modify state, and the fact that this method modifies `upstreamDeletionsLoc` is not even documented anywhere. We should try to make this a method with no side effects.

**Comment by droazen** [comment]
@davidbenjamin Would you be able to look at this for 4.0?

**Comment by davidbenjamin** [comment]
yes

**Comment by davidbenjamin** [comment]
Copying in some discussion about my initial, incorrect, effort in PR #2547:

David Roazen:
As discussed in person, we fully support the mission of making this class less stateful (and particularly making it so that `isVcCoveredByDeletion()` does not modify state, which was the original ticket), but we're concerned that this method `calculateOutputAlleleSubset()` was intended to be stateful, and to accumulate deletions across calls. It's also not well covered by tests, so this change could easily break the method.

Can you think about this issue and reply here once you've looked into it, davidbenjamin ? Also at-mentioning ronlevine to solicit his comments, since he appears to have added `upstreamDeletionsLoc` to this class in the first place.

Ron Levine
droazen Is correct. It was intended to maintain state for upstream deletions. Make sure the upstream spanning deletion does not span shard barriers, then there will be problems with the book keeping. AFAIK, shards overlap genome locations but for a large spanning deletion, the size might not be sufficient.

davidbenjamin Here is the motivation for the change: https://github.com/broadinstitute/gsa-unstable/issues/1188 and accompanying pull request, [Removed spanning deletions if the deletion was removed](https://github.com/broadinstitute/gsa-unstable/pull/1417). I am not convinced the [integration test](https://github.com/broadinstitute/gsa-unstable/pull/1417/files#diff-b60a90bdf249d0dbb8636427be0a5dd7) from the pull request will give the desired results with this implementation.
