### ISSUE TITLE
fix FS annotation difference with GATK3

### ISSUE THREAD

**Issue by lbergelson** [broadinstitute/gatk#2586]
The FS annotation is still different than GATK3 in some cases.  
The task is to:
1. identify which version of the annotation is correct, if either
2. fix it in either gatk4 or gatk3.

**Comment by meganshand** [comment]
It seems that there are some small numerical differences in apache commons Math3 Hypergeometric distribution.

In GATK3 we call the Hypergeometric distribution to get the probability directly, in GATK4 we call the Hypergeometric distribution to get the log of the probability. In these cases there are sometimes some very small rounding errors in the 15th or so least significant digit. The problem is that we either add these numbers to the p-value or not by checking if they are less than or equal to some threshold. In this case these rounding errors can have a large impact (especially when the number of reads is relatively small) on the final p-value.

R seems to have more digits and therefore usually reports that they are the same values, so in this case neither GATK3 or GATK4 match R. I haven't tried other implementations.

**Comment by meganshand** [comment]
On second thought there is an incredibly simple solution that R uses by including everything past 10e-7 as equal or more extreme.
