### ISSUE TITLE
The custom R library installation can be moved into the docker base image (gatkbase), if desired

### ISSUE THREAD

**Issue by LeeTL1220** [broadinstitute/gatk#2699]
Once #2457 is merged, the gatkbase docker image will be the basis for GATK4 docker images.  However, gatkbase depends on no files in the GATK4 repo.  However, we *might* want to move the installation of R libraries into gatkbase.  Currently the custom R installation script takes a substantial portion of time in the GATK4 docker image build.  The question is whether we expect the R libraries to change much.  Once we answer this question, we can decide whether this issue should be addressed.

**Comment by lbergelson** [comment]
I would support pre-installing the R libraries into the base image.  Installing R libraries is slow and tend to fail at random because CRAN isn't as reliable as our other dependencies.  We just need keep the docker file for the base image around so we can rebuild it with new libraries if we need to.

**Comment by davidbenjamin** [comment]
Looks to me like this has since moved to gatkbase.
