### ISSUE TITLE
Investigate 0,0,1 PLs that result in GQ 0

### ISSUE THREAD

**Issue by lbergelson** [broadinstitute/gatk#2712]
We've identified a site that has a genotype with pls of 0,0,1 and reports GQ0.

GVCF is `/humgen/gsa-hpprojects/dev/mshand/palantir/Analysis/535_GenotypeGVCFs/shard-314.vcf.gz` which cannot be made available publicly.

site is 43291092

Gatk3 outputs a GQ0 hom-ref call while gatk4 outputs a no call.  From discussion with @ldgauthier it seems like the no-call is a reasonable output, but it's strange that a) we have GQ0 when the pl difference is 1, and b) that there's a difference between gatk3 and 4

| | `GT:AD:DP:GQ:PGT:PID:PL` | 
| ----|------|
| gatk3 | `0/0:18,0:18:0:.:.:0,0,1 ` |
| gatk4 | `./.:18,0:18:.:.:.:0,0,1 ` |

**Comment by meganshand** [comment]
This only seems to happen if the PL is 0,0,1. Other GQ0 genotypes remain HomRef in both GATK3 and GATK4 (for example the PL 0,0,14). I also haven't seen it happen at multi-allelic sites.

**Comment by sooheelee** [comment]
Remember that the PL of the genotype that is called is zero.
So the two PLs in question that determine the genotype call are the lowest
PLs (so 0 and 0 from 0,0,1).



Soo Hee Lee, Ph.D.
Science Technical Writer

**Comment by lbergelson** [comment]
@sooheelee Thanks for pointing that out, temporary brain failure I think.   There's still something weird about these sites though I think.  
@meganshand That's also strange...

**Comment by lbergelson** [comment]
Another thing to point out, is that this is also happening for sites with more than 3 pls like 0,0,0,1,0,0.

**Comment by sooheelee** [comment]
I looked at the gene locus and it is the 3'UTR of 3-Hydroxy-3-Methylglutaryl-CoA Synthase 1, an enzyme I used to work on!

**Comment by sooheelee** [comment]
For this calling, was `--standard_min_confidence_threshold_for_calling` changed from the default?

**Comment by meganshand** [comment]
A comment from @ldgauthier:

The threshold for PLs to be considered uninformative is the same between GATK3 and 4, but the stack when it gets called is a little bit different. It might be changes in subsetting again because the methods that evaluate the "informativeness" in GATK3 are called updateGenotypeAfterSubsetting and createGenotypesWithSubsettedLikelihoods, which appear to have been refactored into AlleleSubsettingUtils in GATK4. I could see how if we calculate the sum before subsetting in GATK4 then it's smaller and uninformative, but that's speculation.

**Comment by ldgauthier** [comment]
I think this is just expected numerical fluctuation within tolerance -- the no-call is a 0,0,0 and the 0,0,1 is very nearly the same.
