### ISSUE TITLE
NPE in GenomicsDBImport

### ISSUE THREAD

**Issue by kcibul** [broadinstitute/gatk#2713]
Running this command:
`
[May 14, 2017 12:54:35 AM UTC] org.broadinstitute.hellbender.tools.genomicsdb.GenomicsDBImport  --genomicsDBWorkspace genomicsdb --batchSize 100 --sampleNameMap inputs.list --intervals chr1:391755-820848 --interval_padding 500  --genomicsDBSegmentSize 1048576 --genomicsDBVCFBufferSize 16384 --overwriteExistingGenomicsDBWorkspace false --consolidate false --interval_set_rule UNION --interval_exclusion_padding 0 --readValidationStringency SILENT --secondsBetweenProgressUpdates 10.0 --disableSequenceDictionaryValidation false --createOutputBamIndex true --createOutputBamMD5 false --createOutputVariantIndex true --createOutputVariantMD5 false --lenient false --addOutputSAMProgramRecord true --cloudPrefetchBuffer 2 --cloudIndexPrefetchBuffer 2 --disableBamIndexCaching false --help false --version false --showHidden false --verbosity INFO --QUIET false --use_jdk_deflater false --use_jdk_inflater false --disableToolDefaultReadFilters false`

Yields this NPE (which appears to be on a background thread because the program exits normally)

```
[May 14, 2017 1:01:51 AM UTC] org.broadinstitute.hellbender.tools.genomicsdb.GenomicsDBImport done. Elapsed time: 7.26 minutes.
Runtime.totalMemory()=5187305472
java.lang.NullPointerException
	at com.intel.genomicsdb.GenomicsDBImporter.<init>(GenomicsDBImporter.java:479)
	at com.intel.genomicsdb.GenomicsDBImporter.<init>(GenomicsDBImporter.java:417)
	at com.intel.genomicsdb.GenomicsDBImporter.<init>(GenomicsDBImporter.java:382)
	at com.intel.genomicsdb.GenomicsDBImporter.<init>(GenomicsDBImporter.java:347)
	at com.intel.genomicsdb.GenomicsDBImporter.<init>(GenomicsDBImporter.java:524)
	at com.intel.genomicsdb.GenomicsDBImporter.<init>(GenomicsDBImporter.java:585)
	at org.broadinstitute.hellbender.tools.genomicsdb.GenomicsDBImport.traverse(GenomicsDBImport.java:355)
	at org.broadinstitute.hellbender.engine.GATKTool.doWork(GATKTool.java:740)
	at org.broadinstitute.hellbender.cmdline.CommandLineProgram.runTool(CommandLineProgram.java:116)
	at org.broadinstitute.hellbender.cmdline.CommandLineProgram.instanceMainPostParseArgs(CommandLineProgram.java:179)
	at org.broadinstitute.hellbender.cmdline.CommandLineProgram.instanceMain(CommandLineProgram.java:198)
	at org.broadinstitute.hellbender.Main.runCommandLineProgram(Main.java:121)
	at org.broadinstitute.hellbender.Main.mainEntry(Main.java:142)
	at org.broadinstitute.hellbender.Main.main(Main.java:220)
```

**Comment by kcibul** [comment]
@droazen @lbergelson -- this is blocking the JG run.  I can get you access to the underlying data if necessary but hoping the stack trace will point to something obvious

**Comment by droazen** [comment]
@kcibul That NPE suggests that GenomicsDBImporter is failing to find a reader for a particular sample name. One possible cause of this is disagreement between the samples in your `--sampleNameMap` file and the sample names in the VCF headers.

Due to a bug that I noticed just now (https://github.com/broadinstitute/gatk/issues/2714), the `GenomicsDBImporter` class in GenomicsDB unnecessarily uses the actual VCF headers to construct a list of sample names internally, which it then uses to query a map of `sample -> reader` that was (in your case) populated using the contents of the `--sampleNameMap` file.

I've asked Intel to fix that bug in GenomicsDB (ie., use the sample names passed in to it instead of going back to the VCF headers), but it will probably take them 1-2 days, since a new GenomicsDB release will be required. In the meantime @kcibul, I suggest you try running without the `--sampleNameMap` argument and see if the problem goes away. It will likely be a bit slower, since it will download all VCF headers up-front, but it seems to me to greatly decrease the opportunity for this particular NPE to occur. While you're at it, it would also be good to check the contents of your `--sampleNameMap` file against the sample name in each VCF header.

**Comment by kcibul** [comment]
Just confirmed -- bypassing the sample map and supplying the GVCFs directly runs successfully

**Comment by kcibul** [comment]
if there is a mismatch between  VCF header name and sample map name... an helpful error message would be nice.  Checking 1000s of VCFs to find an error would be a pain

**Comment by droazen** [comment]
Yep, I created https://github.com/broadinstitute/gatk/issues/2715 this morning to ask Intel to add a helpful error message in this case.

Glad to hear that you can work around the issue for now by using `-V`!

**Comment by droazen** [comment]
Closing -- this issue is supplanted by https://github.com/broadinstitute/gatk/issues/2715 and https://github.com/broadinstitute/gatk/issues/2714
