### ISSUE TITLE
Error: Cannot rename fragment directory; Directory not empty.

### ISSUE THREAD

**Issue by lbergelson** [broadinstitute/gatk#2743]
Confusing error from GenomicsDBImport:

```
$ ./gatk-launch GenomicsDBImport --genomicsDBWorkspace /tmp/gendb --intervals chr20:1-64444167 --batchSize 300 --genomicsDBSegmentSize 1048576 --overwriteExistingGenomicsDBWorkspace true --cloudPrefetchBuffer 2 --cloudIndexPrefetchBuffer 2 --variant gs://hellbender/test/resources/large/gvcfs/NA19625.g.vcf.gz
(...)
[TileDB::Fragment] Error: Cannot rename fragment directory; Directory not empty.
```

/tmp/gendb is empty before my call to GenomicsDBImport.

**Comment by kgururaj** [comment]
Do you see this consistently or intermittently? This occurs right at the very end of an import when the fragment is renamed (the 'atomic'  [definitely not atomic] operation by the filesystem we were talking about today morning). If the rename fails due to lack of disk space etc, then this error is seen.

**Comment by kgururaj** [comment]
Does this happen anymore? I couldn't reproduce it.

**Comment by lbergelson** [comment]
I can't reproduce this anymore.  Seems fixed.
