### ISSUE TITLE
CalculateTargetCoverage command line printed in header of output is incorrect.

### ISSUE THREAD

**Issue by droazen** [broadinstitute/gatk#2885]
@samuelklee commented on [Thu Sep 01 2016](https://github.com/broadinstitute/gatk-protected/issues/663)

--groupBy parameter is output in lowercase, but is required to be input as uppercase.  Thus, if one tries to rerun the printed command line, an exception will be thrown.

**Comment by cmnbroad** [comment]
I randomly came across this ticket - this is happening because the GroupBy enum in CalculateTargetCoverage [overrides toString](https://github.com/broadinstitute/gatk/blob/b58baa5ff8d69e69ae4ac28c863a4126529cf094/src/main/java/org/broadinstitute/hellbender/tools/exome/CalculateTargetCoverage.java#L675) for some reason, and returns a lower cased string. Sending to @davidbenjamin for routing since he looks like the main contributor for that file.

**Comment by cmnbroad** [comment]
Loos good to me.

**Comment by davidbenjamin** [comment]
Closed by #3314.
