### ISSUE TITLE
See if CountSet can be replaced with an existing set implementation

### ISSUE THREAD

**Issue by droazen** [broadinstitute/gatk#2890]
@lbergelson commented on [Fri Sep 09 2016](https://github.com/broadinstitute/gatk-protected/issues/698)

`CountSet` is a small class that is only used in 1 place.  Investigate if it can be replaced with a set from one of our many collection libraries.  It needs to implement an efficient max and min operation.

**Comment by davidbenjamin** [comment]
@lbergelson  I think it doesn't actually need to implement max and min at all because those are only used in unit tests.  Furthermore, the `kmerCounts` in `AssemblyResultSet` themselves are only used in such methods i.e. they don't need to be members at all.  You could delete `CountSet` entirely without replacing it.  And even if you keep it there it is definitely not crucial for performance and could easily be any old `SortedSet`.

So, the options are 1) replace with `TreeSet` or whatever; 2) delete entirely.  Which would you like?
