### ISSUE TITLE
Tool for determining bin filters from coverage data.

### ISSUE THREAD

**Issue by droazen** [broadinstitute/gatk#2992]
@mbabadi commented on [Thu May 18 2017](https://github.com/broadinstitute/gatk-protected/issues/1055)

At the moment, we:
- Remove targets with possibly bad (NaN, infinity, negative) values
- Remove targets that have uniformly low coverage across all samples

Perhaps we should consider adding more filters:
- Remove targets with very high and very low GC content (can be done in the CalculateTargetCoverage step)
- Remove targets with lots of repeats and anomalously low mappability (can be done in the CalculateTargetCoverage step)
- In the learning mode, remove a target if _too many_ are masked across the samples (in that case, max likelihood parameter estimation is unreliable)

This must be done after careful evaluations, i.e. only if certain features makes a target prone to bad calls no matter what.

**Comment by samuelklee** [comment]
Some filters are implemented in the ModelSegments CreatePoN code (since these filters were directly ported from GATK CNV).  Other filters were implemented as external python scripts by @mbabadi for GPC2 validation.  We should extract and productionize if possible.  Ideally, the tool would take several coverage files (collected over identical bins) and filtering parameters as input, and output a filtered list of bins.  Downstream tools would subset the original coverage files to these bins accordingly.
