### ISSUE TITLE
Add ExperimentalFeature and InternalFeature annotations to barclay

### ISSUE THREAD

**Issue by droazen** [broadinstitute/gatk#3040]
We need these additional labels to supplement `BetaFeature`. Currently the comms team is embedding "experimental" and "internal" in the text of the docs themselves, which is not ideal.

For @cmnbroad

**Comment by magicDGS** [comment]
I have two ideas to make this more general instead of adding more and more annotations to Barclay:

* `BetaFeature` could have an `String` field specifying the "type" of beta: experimental, internal, with default being "beta".
* In the same way as the `ProgramGroup` in the `CommandLineProgramProperties`, a documented feature may require a field with the type of feature.

If you would like, I can contribute with one or the other...

**Comment by droazen** [comment]
We added `ExperimentalFeature`, which is sufficient for now -- closing.
