### ISSUE TITLE
Choose library to use for GATK configuration storage

### ISSUE THREAD

**Issue by droazen** [broadinstitute/gatk#3078]
Needs to:

-support overriding config settings via a simple mechanism (like providing an override config file)
-use a simple, easy-to-edit file format like Java Properties (name = value)
-be widely used in the Java community & well-maintained.

**Comment by droazen** [comment]
First candidate is Apache Configuration.

**Comment by magicDGS** [comment]
For the second point (file format) I would prefer something different than Java Properties, because for lists will be a bit messy (separated by comma in Apache Configuration). Maybe YML or JSON will be better for this purpose?

**Comment by droazen** [comment]
Have to disagree with you on that point, @magicDGS. Comma-separated values for lists seems like the most straightforward/simple/human-editable approach, whereas the other options seem more complex (and therefore more messy/error-prone).

(Unless it turns out that we need nested lists, which I'm hoping is not the case!)

**Comment by lbergelson** [comment]
@magicDGS Do you have an example of something you need to configure that doesn't work well with java properties?

**Comment by magicDGS** [comment]
I'm thinking about lists such as filters packages (in the filter plugin): I can imagine a list with long package names separated by commas, which might be complicated to read due to the repetition of the same organization name.

I think that it might be also more organize if the configuration file is an YML with sections for the different configurations: this will make the file more readable and easier to modify. Something like the codecov configuration will be interesting, separating configurations for spark, plugins, feature codecs, etc. For example, if I want to use a custom codec for BED files while including the HTSJDK codec packages, I would find a problem. Doing it in a granular level may be interesting for having something like:

```yml
- codecs:
    - packages:
        - htsjdk.variant
        - htsjdk.tribble
            - exclude: bed.BEDCodec
        - org.broadinstitute.hellbender.utils.codecs
        - org.magicdgs.htsjdk.codecs
```

**Comment by droazen** [comment]
As a result of @jonn-smith 's initial survey of the available libraries, we are going to test out Owner (https://github.com/lviggiano/owner), which appears to satisfy all of our requirements in an elegant and straightforward way.
