### ISSUE TITLE
VariantRecalibrator needs option to sample sites for massive callsets

### ISSUE THREAD

**Issue by eitanbanks** [broadinstitute/gatk#3230]
VariantRecalibrator works by accumulating every single variant in the input set into memory and then using some subset of that data for training purposes.  The problem is that for large callsets, that's a hell of a lot of variants to keep in memory.  As an example, for the 11K sample callset, we're well over 200M variants.  It's going to be much more for the 20K callset and I shudder to think what the 65K will look like.

The problems we're hitting are that:
1. this tool requires SO much memory to run.  It's currently asking for 60GB because it failed with less for the 11K.  I don't think we can get a machine big enough for the 65K, and I'm even worried about the 20K.
2. It's also REALLY slow because whenever the ArrayList fills up it needs to reallocate and memcopy ALL of the existing data.

I think that it needs an option for massive callsets to have it sample sites from the input.  So e.g. "--sample_every_Nth_variant 10" would only accumulate 1 of every 10 variants in the input, still leaving us with well over 20M variants for the 11K.  Of course, if you can think of a more elegant solution than this, that would be fine too.  :)

We do need to make the 20K relatively soon, so I think this is fairly high priority.  As such I'm going to ask @ldgauthier to take a look (pretty please!).

**Comment by samuelklee** [comment]
Just throwing out there that the GMM EM algorithm could be changed to use minibatches.  (However, being a bit more clever about accumulating and preallocating memory for variants is a separate---but probably easier---problem.)

**Comment by eitanbanks** [comment]
@samuelklee the problem is that I need something pretty quickly here.  I'm guessing that changing the GMM algorithm is going to require a ton of validation...

**Comment by ldgauthier** [comment]
Maybe I'm making this overly complicated, but I think just the sampling won't do it because we need to output VQSLODs for _all_ the variants and we can't do that in one pass this way.  But! We can do it with the model serialization that @lucidtronix did. I propose we run a first pass of VariantRecalibrator with `--sample_every_Nth_variant 10` and then output the model.  Then we run it again, scattering 10 ways (or thereabouts), read in the model, apply the model and cat the scattered .recal files back together.  Then ApplyRecalibration as usual.  I've done a lot of work with the serialization and reading that Sam did and I'm confident it works.  Most of it still needs to be ported from GATK3 though.

**Comment by droazen** [comment]
@eitanbanks Can this be closed given the changes in https://github.com/broadinstitute/gatk/pull/3255?
