### ISSUE TITLE
Bash completion should probably not be sensitive to @DocumentedFeature

### ISSUE THREAD

**Issue by droazen** [broadinstitute/gatk#3596]
Currently tools not marked as `@DocumentedFeature` don't auto-complete in bash, which seems wrong. We should ideally allow the auto-completion to work with all runnable tools, not just those annotated as `@DocumentedFeature`

**Comment by cmnbroad** [comment]
I'm not sure I see the value of this separation - it seems like a bunch of work without much benefit. In practice I don't think the result would be any different once everything is correctly annotated with DocumentedFeature. It would require changes in both Barclay and GATK, with Barclay delegating back to the GATK to allow it to filter out things like example tools.

**Comment by droazen** [comment]
If a tool exists and is runnable, but is not documented, it should be accessible via tab-completion. Otherwise people can't depend on tab-completion to give a complete list of all tools that can be run.

**Comment by droazen** [comment]
If it's a difficult/non-trivial change, though, then it may not be worth fixing. I thought it would be a simple change.

**Comment by magicDGS** [comment]
Apart of the amount of work in both Barclay and GATK, I think that this shouldn't be implemented for 2 reasons:

* After #3486, some tools are hidden from the command line (and they will be most likely undocumented too). If the bash-completion works with undocumented tools that are hidden from the command line, there will appear anyway after pressing tab-tab. If that tools are treated in a different way, then it requires even more work - Barclay does not use the omitFromCommandLine at all, and that means that GATK should extend the bash-completion to take it into account.
* If a tool can bash-complete but it does not show in the online help pages (the main source for help, taking into account that in the CLI is a bit messy when the parameter space grows), then it will be really difficult to really understand how the tool work. Even if it shows the parameters with tab-tab, the only way of checking what the meaning of each of them is look at the CLI help.

Because the bash-completion is a sub-type of help-doclet, it should require the `@DocumentedFeature` annotation: that is the marker interface in Barclay for mark classes as parsed/added to the "help" generated by doclets....

**Comment by droazen** [comment]
Closing, since there is universal opposition to this proposal.
