### ISSUE TITLE
Load a conda environment from GATK

### ISSUE THREAD

**Issue by lucidtronix** [broadinstitute/gatk#3692]
The Python scripts called by the PythonScriptExecutor will require python dependencies which can be managed within a conda environment.  Is there a way to load the appropriate conda environment from GATK so that users and unit tests can run the PythonScriptExecutor without worrying about wrangling python libraries. @samuelklee @mbabadi @cmnbroad Any ideas?

**Comment by droazen** [comment]
@cmnbroad Could you look into our options here, when you get a chance?

**Comment by cmnbroad** [comment]
@lucidtronix @mbabadi Update on this: There is a branch [here](https://github.com/broadinstitute/gatk/commits/cn_python_environment) that updates the docker image that we build on travis to include a full anaconda installation. That may be overkill in the long run but for now gives us a base environment for running integration tests on Travis. The environment managers I've looked at (conda and virtualenv) both appear to work by activating a shell environment. Ideally, we wouldn't need an intermediate shell between the Java code and the Python code, but thats still TBD. In parallel, I'm working on a streaming I/O solution for using input/output streams over standard I/O as the next incarnation of the PythonScriptExecutor for https://github.com/broadinstitute/gatk/issues/3698.

**Comment by cmnbroad** [comment]
@lucidtronix @mbabadi @samuelklee I think the best solution would be to establish a single, common Python environment, with a single set of dependencies, that all GATK Python tools depend on. We would establish a single docker image that has all of these dependencies pip installed, and could also include a conda env for the GATK environment for users who don't want to use the docker image.

If we could do that, it would eliminate the need load per-tool conda environments. From what I've seen so far based on existing branches, the two environments we need (gCNV and CNN-VQSR) don't look that far apart in terms of dependencies. gCNV is using Theano, and CNN Tensorflow, but the rest looks [pretty close](https://docs.google.com/a/broadinstitute.org/spreadsheets/d/1RV7--uBQ0ctlXzMH09cmr0VimpZYIU68DdxJzE60y-c/edit?usp=sharing).

So a strawman proposal for the main components for a common environment would be:

Python           3.6
Numpy           >= 1.13.1
Scipy             1.0.0
Theano         .0.9.0
Tensorflow    1.4.0
Pymc3           3.1
Keras             2.1.1

Can you all chime on on whether you think we can converge in a single environment ? If so, it would greatly simplify things, and we can start with getting a docker image built for running travis tests.

**Comment by samuelklee** [comment]
This sounds good to start.  I think a common environment will make things much easier for users as well.  We may get into a scenario where we are forced to manage environments in the future, but we can punt until then.

Would be great if we can get this up and running on Travis as soon as possible, as I have some gCNV WDL tests that are a bit of a pain to run locally.

**Comment by cmnbroad** [comment]
@lucidtronix Does the above outlined proposal for establishing a common environment work for you ? I think there are a bunch of other dependencies we need to include for one or the other of the tools, but I think this lists the common ones (plus Theano/Tensorflow).

**Comment by samuelklee** [comment]
@mbabadi Can you comment on which version of mkl-service we'll need to remove that Theano warning in gCNV?

**Comment by cmnbroad** [comment]
The other issue we need to resolve is the one @samuelklee mentioned [here](https://github.com/broadinstitute/gatk/pull/3838#issuecomment-348073948), which is how to install/distribute our own Python packages (i.e., gCNV kernel and CNN-vqsr). Assuming the common environment doesn't change frequently, it can probably be baked right into the base docker image, but since we want the Python code to live in the GATK repo, we need to be able to test PRs with modified Python code directly in travis on the image we build for testing.

Is there any reason we can't/shouldn't just pip install them on the generated docker right from source, or from a locally built archive ? Its seems like an option, at least for just getting a CPU enabled distribution running. We'll probably still need a separate a solution like a conda env for non-docker users, and longer term we'll have to address GPU enabling, but for now a local install seems like an option.

**Comment by droazen** [comment]
@cmnbroad Can this one be closed?

**Comment by cmnbroad** [comment]
Closed via https://github.com/broadinstitute/gatk/pull/3912.
