### ISSUE TITLE
VCF header: FLOAT vs INTEGER causing issues

### ISSUE THREAD

**Issue by chandrans** [broadinstitute/gatk#3734]
It seems a lot of users use bcftools on their VCFs, and it sometimes converts floats to integers. For example MQ=31.0 to MQ=31. This change causes GATK tools to error. Is it possible to relax this validation?

----
User Report
----

Hi,

Every time I had this message, this was due to bcftools which can change some float values to an integer representation : (e.g : before bcftools : MQ=31.0; after bcftools : MQ=31). 

The fact that GATK is very strict on that subject (40.0 is considered as a float while 40 is not) have some advantages and some drawbacks. I hope this problem will be resolved in GATK4 because bcftools is really useful and widely used when dealing with vcf files.

This Issue was generated from your [forums] 
[forums]: https://gatkforums.broadinstitute.org/gatk/discussion/comment/43270#Comment_43270

**Comment by lbergelson** [comment]
@chandrans I briefly looked into this, and it looks like this is likely a problem with the gatk3 implementation of median which is very brittle to type issues.  I don't think gatk4 suffers from this problem.  It's up to @vdauwera I guess if we want to fix it in gatk3, but I'm going to close the issue here.  Feel free to reopen if someone encounters it in gatk4.  I suspect that changing the header may not fix the problem in gatk3, it's more likely that it's an issue with the htsjdk parsing that assumes anything that doesn't have a `.` should be treated as an int, while neighboring values are treated as doubles.

**Comment by chandrans** [comment]
Oh Thanks Louis. Great to hear it is not an issue in GATK4. I was thinking it is an issue in GATK4 as well as GATK3. No need to fix in GATK3.
