### ISSUE TITLE
Funcotator - implement GC content annotation.

### ISSUE THREAD

**Issue by jonn-smith** [broadinstitute/gatk#3859]
Need to implement the GC content annotation.

This is calculated by taking the region consisting of a window 200 bases to either side of a variant locus and calculating the percentage of bases in that window that are G or C.

**Comment by samuelklee** [comment]
Note that there is an AnnotateIntervals tool in the CNV pipeline (awaiting review in sl_denoising) that will output a TSV with column headers CONTIG, START, END, and  GC_CONTENT.  It takes -L, which can do the padding for you.

If this doesn't exactly fit the bill for you, then it's probably best if you roll your own implementation rather than modify or refactor that code---should be easy enough.

**Comment by jonn-smith** [comment]
Interesting.  I'll take a quick look at it.

**Comment by samuelklee** [comment]
Actually, oops---I forgot that we enforce no padding via -L, since we have a separate tool in the pipeline, PreprocessIntervals, that is responsible for the padding; i.e., PreprocessIntervals -> AnnotateIntervals -> ... is at the beginning of our pipelines.
