### ISSUE TITLE
Is the GATK resource bundle data outdated?

### ISSUE THREAD

**Issue by P4sm** [broadinstitute/gatk#3870]
The version of dbSNP at the research bundle is 138 for hg19 (updated 8.12.2013), but the latest dbSNP version is 150: [https://www.ncbi.nlm.nih.gov/projects/SNP/snp_summary.cgi?view+summary=view+summary&build_id=150](url) . Is it going to affect my results much if I use 138 instead of 150?

**Comment by lbergelson** [comment]
@P4sm That's a good question, but you should ask it at the [gatk forums](https://gatkforums.broadinstitute.org/gatk/) instead of here. 

This issue tracker is only for gatk4 development and bug reports.   The forum is intended for more general questions like this.  Someone there should be able to help you.
