### ISSUE TITLE
GATK4beta6 CalculateContamination gives >100% results

### ISSUE THREAD

**Issue by slw287r** [broadinstitute/gatk#3889]
Note that matched sample is also supplied (-matched)

The following QQ plot shows the contamination results of both GATK3.8 and GATK4beta6

![gatk34](https://user-images.githubusercontent.com/4134899/33425113-b726b62c-d5f8-11e7-860e-bef2de1de2c6.png)

**Comment by lbergelson** [comment]
@davidbenjamin Could you take a look at this or pass it to whoever is the best person?

**Comment by davidbenjamin** [comment]
@slw287r @lbergelson Contamination estimation has two distinct goals: 1) QC to flag a bam if contamination is too high.  If contamination is > 10% or even 5% the bam is pretty useless for most somatic variant calling and so we're not really concerned about getting the exact value.  2) If the contamination is low, get a precise value in order to know which low variant allele fraction calls should be filtered.

In light of 1) I  think the best way to fix this is to cap the estimate at 100%.  It's not quantitative but at that level of contamination it doesn't really matter.

By the way, a bigger problem is a we recently discovered that throws off results when there is sufficiently low coverage.  This is a big issue that I will certainly fix before the January 9 release.

**Comment by slw287r** [comment]
thanks a lot.

**Comment by davidbenjamin** [comment]
Fixed in #4466.
