### ISSUE TITLE
Make SimpleAnnotatedGenomicRegion able to produce and consume the SequenceDictionary

### ISSUE THREAD

**Issue by LeeTL1220** [broadinstitute/gatk#3995]
Should probably implement the LocatableMetadata or SampleLocatableMetadata

**Comment by samuelklee** [comment]
Use SampleLocatableMetadata if you want CombineSegmentBreakpoints to only operate on segment files form a single sample.  It's conceivable that you want it to be more flexible, in which case I would use LocatableMetadata.

Also, go ahead and move the collection class into the collection package, rather than expose the abstract classes.

**Comment by LeeTL1220** [comment]
I also need it to work with seg files that have no header.

**Comment by LeeTL1220** [comment]
I figure:  
- Create a `SimpleAnnotatedGenomicRegionCollection`
- It will allow the sequence dictionary to be null.  I need to be able to support random tsv files (that have locatable data).

**Comment by samuelklee** [comment]
Let's discuss further before you get too far along.  The design of the Collections code was intended to ensure that very strict file formats are adhered to within the CNV pipeline.  Making it more flexible to accommodate TSVs with arbitrary column headers, relax requirements for sequence dictionaries, etc. undermines that goal.

There are also two other issues to consider:

1) It looks like @jonn-smith has also been putting considerable effort into building a TSV framework for Funcotator.  Perhaps CombineSegmentBreakpoints should consider using that framework instead, if it is more appropriate.  We can also discuss bringing the CNV pipeline over into that framework, but this should definitely wait until after release.  The end goal is for CNV team to spend as little time as possible writing or maintaining any code related to TSV parsing.

2) @mbabadi has put together some python evaluation code for the new gCNV, which makes use of the IntervalTree python package and PyVCF.  Perhaps we could implement a similar approach purely in Java by making use of the IntervalTree implementation in htsjdk.

I think for now we should treat CombineSegmentBreakpoints as a one-off tool to be used for internal validations.  After release, we should design a more generic evaluation tool.  This tool could take as input multiple collections of annotated locatables, with a few rigidly defined formats allowed (e.g., VCF, CNV Collection TSVs, perhaps some TSVs from other tools, etc.), with one designated as ground truth.  The regions for evaluation could also be specified via -L (since it is possible this might not completely specified by the ground-truth collection).  The appropriate intersections and lookups could then be performed.

**Comment by samuelklee** [comment]
Another though: germline tagging should be handled by `VariantFiltration`.
