### ISSUE TITLE
NDArray error from GermlineCNVCaller

### ISSUE THREAD

**Issue by stefandiederich** [broadinstitute/gatk#3996]
Hi, 

I am testing the GATK beta 4.6 at the moment. It's a great improvement in time used to analyse data. Similarly I am interested in calling germline CNV events. I tried out the workflow with only two samples, just to find the right tools and see how it behaves. 
First I used `gatk-launch CalculateTargetCoverage` and `gatk-launch TargetCoverageSexGenotyper` and used the resulting files as input for `gatk-launch GermlineCNVCaller`. Unfortunatelly I got the following error when calling GermlineCNVCaller:

`A USER ERROR has occurred: Couldn't read file /media/Berechnungen/GATKTest/CN_transition_matrix_autosomal.tsvx. Error was: Could not read NDArray tsv file`

I found out that this error has something to do with Numpy. I have installed Numpy 1.13.1. 
Have you seen some error like this before?

Thanks in advance
Stefan

**Comment by samuelklee** [comment]
Hi Stefan,

If there is no obvious error (e.g., is `/media/Berechnungen/GATKTest/CN_transition_matrix_autosomal.tsvx` the correct filename, rather `than /media/Berechnungen/GATKTest/CN_transition_matrix_autosomal.tsv`?  Does the file exist and is it correctly formatted?), then I would guess that this is likely an error with your nd4j configuration.

Just to let you know, we have significantly revamped the both somatic and germline CNV pipelines for the release in January.  If you would like a preview of the germline tool, you may want to look at this branch: https://github.com/broadinstitute/gatk/tree/sl_gcnv_ploidy_cli  However, be aware that it is still under development.

**Comment by stefandiederich** [comment]
Thanks a lot for your detailed information. 
I just had a look into the branch you told me, but it looks quite complicated to me at this time. I think I will wait until the official release in January and hope for some kind of best practise guidelines to come up.

**Comment by samuelklee** [comment]
That sounds prudent.  The new version of the GermlineCNVCaller workflow will be available at release; I think you'll find the workflow itself to be quite streamlined and hopefully easy to use.  However, because the model is relatively sophisticated, there are some parameters and model priors that may need to be set appropriately to generate optimal results.  We plan on spending some time shortly after release doing internal evaluations to determine some best-practices guidelines for data generated at the Broad.
