### ISSUE TITLE
SparkGenomeReadCounts

### ISSUE THREAD

**Issue by svedziok** [broadinstitute/gatk#4185]
Hello,
I am missing the SparkGenomeReadCounts tool in the new release which was included in the beta. Will it be included again soon? What was the reason for removing it? Is there an alternative tool in the new release?

Best
ST

**Comment by droazen** [comment]
This tool was part of the legacy CNV pipeline that was deleted in https://github.com/broadinstitute/gatk/pull/3935. @samuelklee can point you to the appropriate replacement tool.

**Comment by samuelklee** [comment]
@svedziok The new CNV pipelines use the tool CollectFragmentCounts to collect coverage for both WES and WGS analysis.  You should first use the tool PreprocessIntervals to specify padding (for WES) or bin size (for WGS) to create bins over which coverage will be collected.

More generally, you can see how the tools are used in the CNV pipelines by studying the WDLs in scripts/cnv_wdl.

**Comment by svedziok** [comment]
Hi, thanks for answers. Do you plan to provide a spark version too? SparkGenomeReadCounts ran much faster for large BAM files. And is it possible to deactivate the filtering steps in CollectFragmentCounts somehow? If I ran without filter, it ignores lots of reads... which seems to be odd

**Comment by samuelklee** [comment]
We decided to replace SparkGenomeReadCounts with a relatively simple ReadWalker to avoid various bugs we were running into (some of which were due to Hadoop-BAM).  We found that these bugs gave rise to a relatively high failure rate---roughly 1 in 50 TCGA BAMs.

Like any ReadWalker, you can specify custom read filters using GATK engine arguments such as `--disable-default-read-filters` and `--read-filter ...`  However, because we count fragment centers (rather than read starts, as in SparkGenomeReadCounts), disabling filters which check that reads are properly paired may lead to unexpected behavior.

In principle, we could write a similar ReadWalkerSpark version of the tool.  However, our experience running the tool showed that CollectFragmentCounts was already faster than SparkGenomeReadCounts in Spark local mode, sometimes by a factor of ~5 (and, more importantly, it didn't run into Hadoop-BAM failures).  We may do some more careful profiling and roll a ReadWalkerSpark version in the future, but these aren't too high priority at the moment.
