### ISSUE TITLE
ApplyBQSRSpark creates splitting-bai file

### ISSUE THREAD

**Issue by micknudsen** [broadinstitute/gatk#4219]
Hi,

When I run `ApplyBQSR`, the output is an indexed BAM file (`foo.bam` and `foo.bam.bai`). However, when I run the `ApplyBQSRSpark` tool, I get something called `foo.bam.splitting-bai` instead.

I have not been able to find any info about splitting-bai in the documentation. Is this the intended behavior?

**Comment by lbergelson** [comment]
@micknudsen The splitting-bai is a different index from the bai.  It's used to determine where spark should split the bam into shards when it's distributing work across the cluster.  It doesn't provide random access support to the file, so it's a supplement to the bai instead of a replacement.  Ideally we'd also output a normal bai as well, but due to the way the work is sharded it's not trivial to do so.  

You can create the bai with `samtools index` if you use samtools, or `CreateHadoopBamSplittingIndex` has an option to output a bai. 

The spark tools really should be creating it on the fly but we haven't gotten a chance to implement it yet.   I opened a new ticket to track that since I didn't see one anywhere #4226

**Comment by lbergelson** [comment]
I spoke too soon, there's already a ticket for this #1480.

**Comment by micknudsen** [comment]
Thanks. Is the splitting-bai only of use for the tools that generates it (in this case ApplyBQSR), or should it be kept around for other tools (e.g. Mutect2) in a downstream analysis?

**Comment by lbergelson** [comment]
explain what the splitting index  is a bit better and then it will make more sense I think.  Spark works by splitting files up into similar sized chunks and passing those chunks to different worker machines. 
Bam files are hard to split nicely into chunks.  The way they're structured makes it hard to identify where safe boundaries are to split on.  If you don't have a splitting index, we have an algorithm to start reading at essentially random locations and look for safe splitting points, but we've had some issues in the past where you can misidentify a split (which results in a crash) or miss good splits.  The splitting index is a precomputed list of split points, which works around the problem of having to find the splits again next time.  It's only used by spark tools that load bams, so it won't benefit Mutect2 because that's not built on spark.  

We should add some documentation about this somewhere... #4235

**Comment by micknudsen** [comment]
Thanks for the explanation!

**Comment by lbergelson** [comment]
No problem, I hadn't thought about how confusing it must be until you opened this ticket.
