### ISSUE TITLE
Detecting misencoded base quality reads

### ISSUE THREAD

**Issue by acesnik** [broadinstitute/gatk#4242]
I'm wondering if you have a recommended way of detecting misencoded base quality reads. If I run FixMisencodedBaseQualityReads, I do get a USER ERROR message that I could possibly detect by checking the logs, but I would rather use another tool to check for the error in a script, or store an emitted value from the tool to check for the error. As far as I can tell, I don't see such a tool or value.

I have tried the following in a bash commandline interface:
```
acesnik@DESKTOP$ var=$(gatk FixMisencodedBaseQualityReads -I input.bam -O output.bam)
acesnik@DESKTOP$ echo $var # this echos nothing, indicating there's no emitted value
```

**Comment by droazen** [comment]
You can detect whether a tool has failed in bash by checking whether the exit status code is non-zero. In bash, the exit status code of the last command run is stored in the variable `$?`
 
In general, you should ask questions like these on the GATK forum (https://gatkforums.broadinstitute.org/gatk) instead of here, however -- this is for bug reports rather than support requests.

**Comment by acesnik** [comment]
Got it. Thanks for the help!

I'll use the forum in the future.
