### ISSUE TITLE
Somatic CNV case WDL needs to allocate space for PoN in DenoiseReadCounts task.

### ISSUE THREAD

**Issue by samuelklee** [broadinstitute/gatk#4737]
Currently only the counts file is included in the allocation.

**Comment by samuelklee** [comment]
@jsotobroad @meganshand do you guys have any conventions that you follow for this sort of disk-space allocation?  Any reason why this can't be more automated, eventually?

**Comment by meganshand** [comment]
What do you mean by more automated? It looks like you're allocating space based on the input file sizes and some padding, which is already more automated than the user adjusting disk size by hand. Do you mean that Cromwell should allocate space appropriately given the inputs? The issue is that you also need space for the outputs, which is harder to predict unless you have a sense of what the task is doing.

**Comment by samuelklee** [comment]
Automatic allocation based on inputs would be great.  Not sure if it's really possible in practice, though---I guess you would also have to make provisions for streaming inputs.

At the very least, if we ever automate the generation of WDL for tasks (based on some template/conventions given the command-line options for a tool), we should make sure this sort of allocation is part of it.

**Comment by samuelklee** [comment]
I must've been looking at an old version of the WDL when I filed this...
