### ISSUE TITLE
missing transcript in hg19 gencode

### ISSUE THREAD

**Issue by lbergelson** [broadinstitute/gatk#4739]
The hg19 gencode is missing the transcript `ENST00000515683.1`.   It appears in the gtf, but not in the fasta.  Using `funcotator_dataSources.v1.2.20180329`

```
A USER ERROR has occurred: Bad input: Unable to find the given Transcript ID in our transcript list (not in given transcript FASTA file): ENST00000515683.1
```
```
 gatk Funcotator --output-file-format VCF \
--ref-version hg19 --data-sources-path ~/data/funcotator/funcotator_dataSources.v1.2.20180329/ \
-R ~/data/Homo_sapiens_assembly19.fasta -V 0816201804HC0_R01C01.vcf.gz \
-O 0816201804HC0_R01C01.funcotated.vcf
```

The error is triggered somewhere near the position`4:60143686`

**Comment by jonn-smith** [comment]
This is an issue with the Gencode files chosen for the datasources.  The Fasta file we use currently is a subset of the total genes in Gencode, so this is an expected error (though it shouldn't be a user error).

We have 2 options:
1) changing the code to throw a warning and ignore variants in transcripts not in the Fasta.
2) Download a larger set of sequences from Gencode and make sure all transcripts are represented in the Fasta file.

My choice is 2 because it is a relatively seamless update (though the data sources will need to be updated, and this will add about 1.6 GB to the data sources).

@LeeTL1220 Thoughts?

**Comment by LeeTL1220** [comment]
Option 2, for sure

**Comment by jonn-smith** [comment]
@lbergelson @LeeTL1220 This may not be as straightforward as I thought - the `ALL` transcript files do not have the same metadata about where the UTRs are in the coding sequences, which means there would not be enough information to do the UTR annotations.

**Comment by jonn-smith** [comment]
If the transcript doesn't occur in the FASTA then we should put `COULD_NOT_DETERMINE` as the VariantClassification.
