### ISSUE TITLE
VariantRecalibrator htsjdk.tribble.TribbleException

### ISSUE THREAD

**Issue by EvanTheB** [broadinstitute/gatk#4761]
(https://github.com/samtools/htsjdk/issues/1115)
I am getting an error using gatk's VariantRecalibrator:

`htsjdk.tribble.TribbleException: Line 104: there aren't enough columns for line entrainScore=0.7203;HW=4.306476E-6 (we expected 9 tokens, and saw 1 ), for input source: file:///share/ScratchGeneral/evaben/cromwell/cromwell-executions/JointGenotyping/2ce78a09-433b-48eb-83d0-1fa1771d1181/call-SNPsVariantRecalibratorCreateModel/inputs/share/ClusterShare/biodata/contrib/evaben/hs37d5x/vcf/1000G_omni2.5.b37.vcf`

I am having trouble getting to the bottom of the issue. I cannot find the string 'entrainScore=0.7203;HW=4.306476E-6' in the vcf file, and Line 104 is part of the header (I think Line 104 refers to tribble source though). Gatks ValidateVariants does not have any issues with the vcf file, and looking visually with bcftools I cannot see an issue either. 

Can anyone suggest further diagnosis steps? Should I take this to GATK issue tracker?

The VCF file is here: ftp://gsapubftp-anonymous@ftp.broadinstitute.org/bundle/b37/1000G_omni2.5.b37.vcf

Here is the gatk command line: 
```
gatk --java-options "-Xmx100g -Xms100g" \
    VariantRecalibrator \
    -V /share/ScratchGeneral/evaben/cromwell/cromwell-executions/JointGenotyping/2ce78a09-433b-48eb-83d0-1fa1771d1181/call-SNPsVariantRecalibratorCreateModel/inputs/share/ScratchGeneral/evaben/cromwell/cromwell-executions/JointGenotyping/2ce78a09-433b-48eb-83d0-1fa1771d1181/call-SitesOnlyGatherVcf/execution/NA12878.sites_only.vcf.gz \
    -O NA12878.snps.recal \
    --tranches-file NA12878.snps.tranches \
    -trust-all-polymorphic \
    -tranche 100.0 -tranche 99.95 -tranche 99.9 -tranche 99.8 -tranche 99.6 -tranche 99.5 -tranche 99.4 -tranche 99.3 -tranche 99.0 -tranche 98.0 -tranche 97.0 -tranche 90.0 \
    -an QD -an MQRankSum -an ReadPosRankSum -an FS -an MQ -an SOR -an DP \
    -mode SNP \
    -sample-every 10 \
    --output-model NA12878.snps.model.report \
    --max-gaussians 6 \
    -resource hapmap,known=false,training=true,truth=true,prior=15:/share/ScratchGeneral/evaben/cromwell/cromwell-executions/JointGenotyping/2ce78a09-433b-48eb-83d0-1fa1771d1181/call-SNPsVariantRecalibratorCreateModel/inputs/share/ClusterShare/biodata/contrib/evaben/hs37d5x/vcf/hapmap_3.3.b37.vcf \
    -resource omni,known=false,training=true,truth=true,prior=12:/share/ScratchGeneral/evaben/cromwell/cromwell-executions/JointGenotyping/2ce78a09-433b-48eb-83d0-1fa1771d1181/call-SNPsVariantRecalibratorCreateModel/inputs/share/ClusterShare/biodata/contrib/evaben/hs37d5x/vcf/1000G_omni2.5.b37.vcf \
    -resource 1000G,known=false,training=true,truth=false,prior=10:/share/ScratchGeneral/evaben/cromwell/cromwell-executions/JointGenotyping/2ce78a09-433b-48eb-83d0-1fa1771d1181/call-SNPsVariantRecalibratorCreateModel/inputs/share/ClusterShare/biodata/contrib/evaben/hs37d5x/vcf/1000G_phase1.snps.high_confidence.b37.vcf \
    -resource dbsnp,known=true,training=false,truth=false,prior=7:/share/ScratchGeneral/evaben/cromwell/cromwell-executions/JointGenotyping/2ce78a09-433b-48eb-83d0-1fa1771d1181/call-SNPsVariantRecalibratorCreateModel/inputs/share/ClusterShare/biodata/contrib/evaben/hs37d5x/vcf/dbsnp_138.b37.vcf
```

Versions: gatk-4.0.4.0

**Comment by EvanTheB** [comment]
It looks like all the indexes are present: 
1000G_omni2.5.b37.vcf
1000G_omni2.5.b37.vcf.idx
1000G_phase1.snps.high_confidence.b37.vcf
1000G_phase1.snps.high_confidence.b37.vcf.idx
dbsnp_138.b37.vcf
dbsnp_138.b37.vcf.idx
hapmap_3.3.b37.vcf
hapmap_3.3.b37.vcf.idx

Maybe the vcf files need a different format, bcf or vcf.gz? I think there is also a different index format iirc. I will trial those next week.

**Comment by lbergelson** [comment]
@EvanTheB Thanks for moving over to the gatk tracker, I think it make more sense to start here and you'll get more eyes on it.  We can always push it back down to htsjdk if we determine that's definitely where the problem is.  

I downloaded that vcf, I noticed that the actual download link for it is  
ftp://gsapubftp-anonymous@ftp.broadinstitute.org/bundle/b37/1000G_omni2.5.b37.vcf **.gz** .

In zipped form it's a gzip file, but not a bgzip file which is what's required for tribble indexing to work.  If you downloaded and unzipped it to just plain old vcf it should be fine though.  

I haven't been able to reproduce the issue yet.  It looks like to me like line 104 is the first non-header line of the vcf, and I do see that string it's reporting on line 242.  Is it possible there's a mix up between files?
```
882033  rs2272756       G       A       .       PASS    CR=99.79803;GentrainScore=0.7203;HW=4.306476E-6
```

It sounds a lot like some sort of indexing bug.  I don't think it should be #4224 because you're using a vcf instead of a vcf.gz.  Hopefully there isn't a different index bug lurking out there...

One weird thing I did notice, is that if I regenerate the .idx file, I get a different file from what comes with the vcf from the ftp site.  Indexes aren't necessarily unique to a file, but I wonder if the one on the website is corrupted in some way.  Could you try running `gatk IndexFeatureFile -F 1000G_omni2.5.b37.vcf` and then re-running your command with the newly generated index.  I'm hoping that will fix it.  If not we'll have to dig in more.

**Comment by EvanTheB** [comment]
I 'bgzip'-ed and 'bcftools index -t'-ed my .vcf files, and re-ran VariantRecalibrator. (just with the vcf.gz and vcf.gz.tbi files present) And it seems to be working fine. TIL there seem to be a lot of different VCF index formats;
```
bcftools index: 1000G_omni2.5.b37.vcf.gz.csi
bcftools index -t: 1000G_omni2.5.b37.vcf.gz.tbi
bgzip -i: 1000G_omni2.5.b37.vcf.gz.gzi
```
As well as the '.idx' files (what are those?) that are included on the broad ftp linked above. I couldn't find an explanation or comparison of these formats with google, can anyone link one? 

I think a quick fix here would be to just mention the index file in that stack trace, I would have worked it out for myself with that clue. I suppose that note could be added to htslib or added in gatk. I notice the docs don't mention which index formats are used or preferred, just:
```
--read-index | [] | Indices to use for the read inputs. If specified, an index must  be provided for every read input and in the same order as the read  inputs. If this argument is not specified, the path to the index for  each input will be inferred automatically.
```

Thanks for your help
