### ISSUE TITLE
Adaptive assembly graph pruning

### ISSUE THREAD

**Issue by davidbenjamin** [broadinstitute/gatk#4867]
In high-depth calling (eg @meganshand's work with mitochondria) it is necessary to tweak the `min-pruning` argument.  If it is too low, base errors render the assembly graph nearly dense,  causing a loss of sensitivity when the assembly engine essentially chooses random haplotypes.  If it is too high, we also lose sensitivity because true variants are pruned.

Setting the command line argument differently for each sample is not only cumbersome.  It also doesn't solve the problem because depth varies within the same bam.  Thus, pruning must adapt to each assembly region.

**Comment by sarahcalvo** [comment]
I would like to put in a plug to prioritize this issue -- so that I can use Mutect2 for calling variants in RNA-seq!  Looking for somatic (eg tissue-specific) variants in RNA data is an area of huge growing interest (as there's a ton of existing RNA-seq data), and Mutect2 would be perfect for this application now that we've shown how awesome it is for calling low variant-allele-fraction variants in high-depth regions.  

As an example, in one of my muscle RNA-seq samples, one gene in the mitochondrial genome has 200,000x coverage and the neighboring gene has 100x coverage.  Currently Mutect2's --min_pruning argument would be useless, and a dynamic method is needed.
