### ISSUE TITLE
Mutect multi-sample calling

### ISSUE THREAD

**Issue by davidbenjamin** [broadinstitute/gatk#4887]
That is, multiple samples of the same tumor in space or time, a tumor and a metastasis, a tumor and its cfDNA etc.

First we have to ask collaborators and the community what features they would like and what problems they want to solve.

**Comment by fpbarthel** [comment]
I am very interested in this feature. In my current workflow I am using `freebayes` (and in an older version simply `pileup`) to query mutation sites on a cohort level and would be very interested in a GATK naive approach.

**Comment by ldgauthier** [comment]
Since we're using Mutect2 for our mitochondrial variant calling pipeline that's in development, and we want to joint call mitochondria, I'm working on "somatic joint calling".  It won't have a joint likelihood model (yet?) the way that germline SNP and indel joint calling does, but it will be able to give you a "squared-off" matrix of calls for each sample at each site that's variant in any sample.

**Comment by davidbenjamin** [comment]
Closed by #5560.
