### ISSUE TITLE
-new-qual error issue

### ISSUE THREAD

**Issue by prasundutta87** [broadinstitute/gatk#5000]
So how has the -new-qual error modified? I have used gatk 4.0.4.0 for all my analysis. How badly should I have to re-analyse with the new version of GATK? Is it really important?

__(edited to remove distracting boilerplate text - lbergelson)__

**Comment by lbergelson** [comment]
@davidbenjamin This sounds like a question for you.

**Comment by davidbenjamin** [comment]
@prasundutta87 Since 4.0.4.0 the changes to new qual are: 1) some sites with QUAL = 0 were genotyped instead of being put in reference confidence blocks in GVCF mode and 2) spanning deletions no longer count towards variant quality.  Also, while doing 2) I introduced a bug in 4.0.5.0, which was quickly fixed.

Of these, 1) has no effect once you run `GenotypeGVCFs` and 2) is an edge case.  I would not re-run your analyses.

**Comment by prasundutta87** [comment]
Thanks a lot David. It's a relief then. Anyway, is it possible to get a document to know more about -new-qual and how is it different from the old QUAL algorithm? I was using it because I was advised it being calculated faster than the old QUAL. But I would like to know what is the actual difference. I did not find a suitable document in the GATK website and was pointed to an issue post in GitHub itself.

**Comment by davidbenjamin** [comment]
@prasundutta87 Uh oh, putting the new qual docs in the repo must have slipped my mind.  I just submitted a PR for this, where you can see a pdf describing the new model: https://github.com/broadinstitute/gatk/pull/5008

Thank you for pointing this out.

**Comment by prasundutta87** [comment]
Thanks a lot David. Will let you know if I have any doubts.
