### ISSUE TITLE
Code coverage down by 20%

### ISSUE THREAD

**Issue by lbergelson** [broadinstitute/gatk#5001]
Somehow our code coverage has dropped by 20% since the changes to shrink the docker image.  I'm not sure if the issue is that we're not running a chunk of our tests or if we're not reporting coverage for some of them, but either way there is a problem.

**Comment by jamesemery** [comment]
To clarify, the tests are being run. It appears to be a bug in how we have configured the jacocoTestReport job that gets executed inside the docker image which seems to result some missing xml files that codeCoverage uses to build its reports. Since we have our integration and cloud tests outside of the docker image the coverage didn't drop to zero. I am looking into reconfiguring the jacocoTestReport task to behave correctly.
