### ISSUE TITLE
Test report URL is not accurate for testOnPackagedReleaseJar.

### ISSUE THREAD

**Issue by samuelklee** [broadinstitute/gatk#5029]
These get put into tests/testOnPackagedReleaseJar rather than tests/test.

**Comment by jamesemery** [comment]
Hey @samuelklee. That is true, the default location for a gradle test output is tests/#taskname#. I'm not sure what the problem is however. If you look at the gradle test logs there is a line pointing to where the reports live: " Test report will be written to  https://storage.googleapis.com/hellbender-test-logs/build_reports/master_20802.3/tests/test/index.html." Those links seem to work on the latest master. We fix this by simply renaming the files before we upload them however. Is this explanation adequate or would you like the build system changed?

**Comment by samuelklee** [comment]
Whoops, you're right!  I think I got confused because I was looking at a build where the test report did not get generated and I missed the bit about renaming files in the build.  Mea culpa!
