### ISSUE TITLE
Understanding -nct and -nt

### ISSUE THREAD

**Issue by wenjuanZHU2018** [broadinstitute/gatk#5035]
-nt 8 means you use 8 cores
-nct 8 means you use 8 threads within a single core

In this website, https://gatkforums.broadinstitute.org/gatk/discussion/9283/understanding-nct-and-nt
Geraldine_VdAuwera who belongs to GATK team said it is correct.  However, I think the meaning of -nct and -nt had been mixed. 

-nt 8 should mean  that  we 8 threads within a single core
-nct 8 should mean that we use 8 CPU to deal with our data.  
am I right?  Thanks.

**Comment by wenjuanZHU2018** [comment]
by the way, GATK send the confirmation email to me. However, I cannot open that website link after trying many times. It always tell me that Site was not found.  It is very strange.

**Comment by magicDGS** [comment]
@wenjuanZHU2018 - I think that this should be asked on the GATK forum. This repository contains GATK from version 4 onwards, which does not support anymore parallelization using those arguments.

**Comment by wenjuanZHU2018** [comment]
@magicDGS  Thanks for your reply. I would like to ask GATK forum on gatk official website.  However, the confirmation email GATK send to me cannot be opened.  Therefore, I cannot post a question on GATK official website.  That is very strange.

**Comment by davidbenjamin** [comment]
`-nt` is data threads, that is, threads on a single core.  This is not true CPU-level parallelism but can save significant time because different threads need not be delayed by each other's memory fetches and I/O.  That is, it is data parallelism but not processor parallelism.

`-nct` is CPU parallelism and means multiple cores.

I'm closing this issue, but feel free to re-open if I have not answered clearly.
