### ISSUE TITLE
Somatic CNV output files cannot be read by IGV

### ISSUE THREAD

**Issue by LeeTL1220** [broadinstitute/gatk#5037]
### Tool(s) or class(es) involved
Somatic CNV

### Description
The output of the Somatic CNV tools cannot be read by IGV.  Previous CNV versions generated  readable output seg files.

Two possible solutions:
- Solicit support from IGV.  This may be hard, since the extension is the same.
- Provide a conversion tool.
- Change the output format itself.

**Comment by samuelklee** [comment]
Already some discussion in #2853 and we've met with Helga from the IGV team.  Do you want allele-fraction and credible-interval plotting as well, or just copy-ratio mean as before?

**Comment by LeeTL1220** [comment]
@samuelklee I would want all, but copy-ratio being the most important.

**Comment by samuelklee** [comment]
As discussed elsewhere, all IGV does is ignore the column headers and take the last column, see https://software.broadinstitute.org/software/igv/SEG

Let's have ModelSegments output two LegacySegmentCollection files with CBS-style column headers, one for CR_50 (*.cr.igv.seg) and the other for MAF_50 (*af.igv.seg).  Methods can be added to ModeledSegmentCollection to create these LegacySegmentCollections.  LegacySegmentCollection can probably just inherit directly from AbstractRecordCollection (technically it is a AbstractSampleLocatableCollection, but methods would have to be overridden to suppress the SAM-style header and the missing sequence dictionary makes the file representation incomplete.)

Should be no more than a day's work.  @LeeTL1220 feel free to take this one if you have time, otherwise I'm happy to take care of it after some more high priority issues.

**Comment by LeeTL1220** [comment]
Do you mean " Methods can be added to ModeledSegmentCollection to create these LegacySegmentCollections" or "Methods can be added to ModelSegments to create these LegacySegmentCollections" ?

**Comment by samuelklee** [comment]
We can either add `to*LegacySegmentCollection` methods to ModeledSegmentCollection or add static utility methods to ModelSegments.  No real preference here as the coupling is minimal.
