### ISSUE TITLE
FilterMutectCalls generates different results for multiallelic

### ISSUE THREAD

**Issue by RyanBio** [broadinstitute/gatk#5052]
### Affected tool(s) or class(es)
FilterMutectCalls 

### Description 
I split multiallelic to multiple lines through bcftools norm, the FilterMutectCalls generate different results with the same command. Some examples
multiallelic in one line: 

     chr1    156842471       .       CTT     C,CT,CTTT,CTTTT .       clustered_events;multiallelic
     chr2    234580453       .       ATT     A,AT    .       PASS
     chr21   39951749        .       CTT     C,CT,CTTT,CTTTT,CTTTTT  .       germline_risk;multiallelic
multiallelic splitted in multiple lines: 

     chr1    156842471       .       CTT     C       .       clustered_events;t_lod
     chr1    156842471       .       CTT     CT      .       clustered_events
     chr1    156842471       .       CTT     CTTT    .       clustered_events
     chr1    156842471       .       CTT     CTTTT   .       clustered_events
     chr2    234580453       .       ATT     A       .       germline_risk;t_lod
     chr2    234580453       .       ATT     AT      .       germline_risk
     chr21   39951749        .       CTT     C       .       PASS
     chr21   39951749        .       CTT     CT      .       PASS
     chr21   39951749        .       CTT     CTTT    .       PASS
     chr21   39951749        .       CTT     CTTTT   .       PASS
     chr21   39951749        .       CTT     CTTTTT  .       PASS

It seems those variants in STR region are more likely sequencing artifacts. FilterMutectCalls provides "multiallelics" for "Site filtered because too many alt alleles pass tumor LOD", it seems not an accurate description for homopolymer artifacts.

**Comment by davidbenjamin** [comment]
@RyanBio `FilterMutectCalls` is designed to be used directly with the output of `Mutect2` and I don't foresee ever recommending that users split an M2 vcf line before filtering.  I agree with you that these artifacts are related to the homopolymer and that "multiallelic" is not fully satisfactory.  A more precise thing to do would be to raise the prior rate of polymerase slippage when we see several alleles, so that the STR filter would be triggered.  But then again, this is basically what you should read the "multiallelic" filter as already.
