### ISSUE TITLE
CRAM Support in MarkDuplicates

### ISSUE THREAD

**Issue by marchoeppner** [broadinstitute/gatk#5218]
GATK Version: 4.0.9.0

The issue: 
The previously available "beta" tool MarkDuplicatesGATK introduced reliable support for CRAM formatted files into the GATK tool chain. 

Since that was removed again, I noticed that the default/picard-derived MarkDuplicates does not work reliably on CRAM formatted files. I am getting:

java.lang.IllegalStateException: A valid CRAM reference was not supplied and one cannot be acquired via the property settings reference_fasta or use_cram_ref_download

using this call:
gatk MarkDuplicates -I Sample_AS-230151.clean.cram -O test.cram -M metrics -R /ifs/data/nfs_share/ikmb_repository/references/gatk/bundle/2.8/b37/human_g1k_v37.clean.fasta

Files in folder: Sample_AS-230151.clean.cram  Sample_AS-230151.clean.cram.bai  Sample_AS-230151.clean.cram.crai

Since CRAM provides a *significant* storage saving over BAM, we would very much like use CRAM exclusively. But this still seems to be an issue, despite reports over at the Picard-side of things dating back to 2016 and beyond. 

Any chance of this ever getting fixed?

Cheers,
Marc

**Comment by droazen** [comment]
@marchoeppner `MarkDuplicatesGATK` was removed because it had fallen out-of-date with respect to the version in Picard, and as an unmaintained tool was in our view not safe for use, and was causing confusion for our users. The loss of CRAM support is an unfortunate side effect of its removal.

We've been doing a lot of work on our parallel version of `MarkDuplicates`, however, which is called `MarkDuplicatesSpark`. This version is fully up-to-date with respect to the Picard version, can run much faster than the Picard version when multiple cores or multiple machines are available, and will fully support CRAM in the future. CRAM support in that tool will come as a side effect of our migration to the new Disq library (https://github.com/disq-bio/disq), which is scheduled to happen within the next few months.

In the meantime, I'd suggest continuing to request the Picard community to add CRAM support to their version. It's likely not a lot of work, and may simply require passing the reference through to the reader class, which could be a ~1 line change!
