### ISSUE TITLE
Discussion question stemming from Mutect2 VCF handling

### ISSUE THREAD

**Issue by sooheelee** [broadinstitute/gatk#5391]
On behalf of a number of researchers over the years, here is a question.

Should GATK tools accept every valid VCF, discern PASS vs. FILTERED status and also skip `.` annotation sites as if they did not exist?

See case presented by a researcher at https://gatkforums.broadinstitute.org/gatk/discussion/comment/53533.

**Comment by sooheelee** [comment]
Assigning @vdauwera and @droazen for discussion.

**Comment by sooheelee** [comment]
Tagging @davidbenjamin since Mutect2 is what brings up this question.

**Comment by davidbenjamin** [comment]
IMO we probably should accept any valid VCFs but I can't say it's a high priority to me when our provided resource file works and the user has zero reason not to use it.  I mean, if users want to shoot themselves in the foot, and the GATK's downward aim is buggy, that's kind of a feature, isn't it?

**Comment by nurmians** [comment]
@davidbenjamin I think that is a bit of a cop out. I would of been happy to use a provided resource but there was none to be found for hg38. I had to do a liftover for the gnomAD data and that introduced changes to the VCF that invoked this bug in <20% of my samples after hours of processing without any sensible error message to lead me onto what was the cause of the problem. I have wasted many days on debugging this issue and creating a bug report and I was considering switching to GATK3 or some other variant caller because of it. I think someone else reported a very similar issue on the forum and went back to using GATK3 because of it. 

Maybe Mutect2 should, by default, run a filter on the pop resource VCF to get rid of unnecessary or erroneous lines. When users get more familiar with the algorithm, they could disable this filtering to save time and provide a pre-filtered VCF (--germline-resource or --germline-filtered-resource).

**Comment by droazen** [comment]
@davidbenjamin Perhaps we should just apply a variant filter upfront to the variants retrieved from the `--germline-resource` in `Mutect2Engine`? We already have a `PassesFiltersVariantFilter` that could be used...

**Comment by davidbenjamin** [comment]
@nurmians If we don't provide an hg38 resource then I would have to agree completely that my initial answer is a cop-out!  I think @droazen's idea ought to work.

**Comment by sooheelee** [comment]
@rcmajovski We should have a forum doc that illustrates the steps in the WDL that prepares the af-only resource.
