### ISSUE TITLE
implement median coverage by genotype

### ISSUE THREAD

**Issue by akiezun** [broadinstitute/gatk#540]
implement a tool that computes median coverage (AD) per genotype: homRef/het/homVar (actually, compute it for all possible genotypes at the site). For good variants, the coverage should be independent of genotype so it's a good check to perform.

**Comment by jbloom22** [comment]
@akiezun so my approach here is to stream through to build a histogram on bins 0, ..., 250.  I can spin my own median function on a histogram, but it seems that Tim has already written a histogram class below in htsjdk.samtools.util that computes percentiles, mean, etc... I think it'd make sense to use something like this in general rather than locally replicating methods for common statistics on histograms.  How to proceed?  His class expects the histogram as a sortedMap (I was just using an array from 0 to 250).

package htsjdk.samtools.util;

import htsjdk.samtools.util.Histogram.Bin;

/**
 * Class for computing and accessing histogram type data.  Stored internally in
 * a sorted Map so that keys can be iterated in order.
 *
 * @author Tim Fennell
 */
public class Histogram

**Comment by davidbenjamin** [comment]
We don't seem to care about this.
