### ISSUE TITLE
HaplotypeCaller amino acid output? 

### ISSUE THREAD

**Issue by lincoln-harris** [broadinstitute/gatk#5431]
Hi
I'm using HaplotypeCaller to do mutation calling in a large single-cell RNA-seq dataset. Im wondering if there is a way to get HaplotypeCaller to spit out _amino acid_ coordinates instead of _genome_? Can we maybe include a column such as 'Mutation.AA' that would contain entries like this? 
<img width="151" alt="screen shot 2018-11-16 at 5 51 52 pm" src="https://user-images.githubusercontent.com/33501625/48655137-54309080-e9c8-11e8-9431-6e83b5afd9d7.png">
 It would be very useful for downstream applications like searching for clinically relevant SNPs/indels. 
Thanks
Lincoln

**Comment by ldgauthier** [comment]
That would be a lot of extra infrastructure for HaplotypeCaller, but can Funcotator do that out of the box @jonn-smith ?

**Comment by jonn-smith** [comment]
Yes - Funcotator supports this out of the box right now (including for MT chromosomes).

Funcotator is still a beta tool, but will be out of beta _very_ soon.

There is some documentation on the [forums](https://gatkforums.broadinstitute.org/dsde/discussion/11193/funcotator-information-and-tutorial/) as well as in the GATK Docs.  All the documentation needs to be updated, but none of it should be wrong.

If you run the HaplotypeCaller output VCF through Funcotator, you'll get many annotations.  Protein position is one of them.  However, this is the position of the actual change in the protein sequence, rather than the variant locus.  The distinction is that there can be indels that change bases in position X and the protein sequence doesn't  differ until position X+Z (for example in short tandem repeats, if one repeat is deleted).

**Comment by lincoln-harris** [comment]
Excellent! Ill give Funcotator a try
