### ISSUE TITLE
GDB feature request: silence buffer resize logging

### ISSUE THREAD

**Issue by ldgauthier** [broadinstitute/gatk#5568]
@nalinigans I have some very long-running jobs that I'm trying to track, but my stderr is choked with buffer resize outputs.  Would it be possible to turn those off by default or add a flag to turn them off?  It makes for huge log files and it's hard to track if the log is still being updated for jobs that run >24hrs.

**Comment by ldgauthier** [comment]
Looks like Nalini already took care of this a while ago.

**Comment by ldgauthier** [comment]
I just ran GATK 4.1.7.0 with GDB 1.2.1 and I'm seeing these logging messages again.  Granted I've also built a few old jars lately, but after a clean build I'm still seeing it.  @nalinigans can you run the latest and confirm or deny?

**Comment by droazen** [comment]
@ldgauthier Did you try GATK 4.1.8.0 or later as well? 4.1.8 introduced a major new release of GenomicsDB.

**Comment by droazen** [comment]
@ldgauthier Also, try running with the prebuilt jars (https://github.com/broadinstitute/gatk/releases/download/4.1.8.1/gatk-4.1.8.1.zip) and/or the latest docker image to eliminate your local build environment as a variable.

**Comment by nalinigans** [comment]
I just tried with gatk 4.1.7.0 and 4.1.8.0 released zips and cannot reproduce the issue. I can only see buffer resize logging messages when I use a debug version of libtiledbgenomicsdb.so in my private builds. 

That said, `gatk 4.1.7.0` picks up  `libtiledbgenomicsdb.so`  from the LD_LIBRARY_PATH, otherwise it extracts from the genomicsdb.jar. @ldgauthier, do you have an older version of the native `libtiledbgenomicsdb.so` in your LD_LIBRARY_PATH env? That could be one cause.

Otherwise, if you move to using `gatk 4.1.8.1` as @droazen recommends, it will only pick up the native library packed with the genomicsdb 1.3.0 jar. To override the packed genomicsdb library, in versions 1.3.0+,  one has to explicitly the path specify via java options -Dgenomicsdb.library.path=<path_to_libtiledbgenomicsdb.so>.
