### ISSUE TITLE
Doubts on PreAdapterOrientationScorer

### ISSUE THREAD

**Issue by yodeng** [broadinstitute/gatk#5623]
Hi, GATK developers:

I just wonder that if absolute value should be used when calculating `baseScore` on <a href="https://github.com/broadinstitute/gatk/blob/67f0f0f2e59185b721398b17c24eba487a2ac76c/src/main/java/org/broadinstitute/hellbender/tools/exome/orientationbiasvariantfilter/PreAdapterOrientationScorer.java#L77" target="_blank">line 77 of PreAdapterOrientationScorer.java</a>. `MAX_BASE_SCORE` will always be chosen if `PRO` is less than `CON` 

Yong

**Comment by davidbenjamin** [comment]
@yodeng This is the intended behavior.  I think it's confusing because although there is a reverse complement symmetry in orientation bias artifacts in that a G->T mutation on the template strand will show up as G->T in some reads and C->A in other reads.  However, it is not fully symmetric because the G->T is always on read 1 and C->A is always on read 2.

When you tell `FilterByOrientationBias` to filter out the G->T artifact, you are more precisely asking it to filter out G->T and C->A artifacts caused by G->T on the template strand.  Therefore, an excess of G->T on read 2, which would be reflected by taking the absolute value of PRO - CON, does not support the artifact.
