### ISSUE TITLE
Newer Java Versions?

### ISSUE THREAD

**Issue by bbimber** [broadinstitute/gatk#5737]
Hello - is GATK4 considering supporting newer java versions?  I'm sure you know JDK8 is nearing end of life?

**Comment by lbergelson** [comment]
We'd really like to be able to move forward to newer java versions.  Unfortunately we have a pretty long list of dependencies which don't support any version newer than 8 yet. In particular, our dependency on Spark is problematic.

Spark is stuck on java 8 because of issues with scala on java 9+ as well as issues with their dependencies.  As I understand it, Java 9+ made changes to various methods which were widely used by libraries that do low level memory management.  It also deprecated some forms of cross package reflection.  Spark makes heavy use of both of those things so I think there having trouble updating.  

So... we'd like to update, I have no idea when will be able to.  Probably not for at least a year.

**Comment by davidbenjamin** [comment]
#6053 duplicates this.
