### ISSUE TITLE
OxoGReadCounts renamed to OrientationBiasReadCounts in 4.1.1.0

### ISSUE THREAD

**Issue by tfenne** [broadinstitute/gatk#5848]
### Affected tool(s) or class(es)
HaplotypeCaller 4.1.1.0

### Affected version(s)
- [x] Latest public release version
- [x] Latest master branch as of 3/31/2019

### Description 
It looks like PR #5840 did a lot of refactoring to the way F1R2/F2R1 annotations are computed.  Along the way it looks like `OxoGReadCounts` was renamed to `OrientationBiasReadCounts`.  This is, unfortunately for some, a non-backwards compatible change as any pipeline that uses `-A OxoGReadCounts` will now fail.

I'm not sure if there's a deprecation mechanism for annotations that would inform users of this, and I'm not sure there's a whole lot to be done at this point.  I'm logging this issue mainly so anyone else who runs into this will find the answer quickly.

Might be nice to add a line to the 4.1.1.0 release notes though noting this change.

**Comment by davidbenjamin** [comment]
PR #5840 created a few pipeline-breaking changes.  Since the orientation bias annotation and filter are only standard in Mutect2 we weren't expecting it to cause problems for HaplotypeCaller users.  And as far as Mutect2 is concerned the WDL is always in a working state and we hope users are running the pipeline that way.

While changing the annotation name was not absolutely necessary we felt it was important because the OxoG artifact is only one example of an artifact with orientation bias.  As of 2012 or so it was the best-known such artifact but the name is now misleading.  We don't want users to think that we don't handle other artifacts when in fact the new orientation bias model handles every orientation bias artifact.

By the way @tfenne, are you using this annotation in order to run the orientation bias filter?

**Comment by tfenne** [comment]
Thanks @davidbenjamin  - my thought here was that since it's an available annotation in HaplotypeCaller it would be nice to just add a line to the release notes in case anyone else had started emitting it.

To answer your question, we have been emitting it in a clinical pipeline, but haven't actually been using it for downstream filtering yet.

**Comment by davidbenjamin** [comment]
@droazen Can you add "OxoGReadCounts annotation renamed to OrientationBiasReadCounts" to the 4.1.1.0 release notes?

**Comment by droazen** [comment]
@davidbenjamin Sure, I've added that to the release notes
