### ISSUE TITLE
AFCalculationResult uses snpPseudocount for insertions and indelPseudocount for SNPs and deletions

### ISSUE THREAD

**Issue by DonFreed** [broadinstitute/gatk#5885]
### Affected tool(s) or class(es)
org.broadinstitute.hellbender.tools.walkers.genotyper.afcalc.AlleleFrequencyCalculator

### Affected version(s)
Latest master branch as of April 16, 2019

### Description 
At, https://github.com/broadinstitute/gatk/blob/master/src/main/java/org/broadinstitute/hellbender/tools/walkers/genotyper/afcalc/AlleleFrequencyCalculator.java#L66

For insertions, `priorPseudocount` is set to `snpPseudocount`. With SNPs and deletions, `priorPseudocount` is set to `indelPseudocount`.

SNPs should have the `priorPseudocount` set to `snpPseudocount`. Indels should have `priorPseudocount` set to `indelPseudocount`.

**Comment by ldgauthier** [comment]
@davidbenjamin after taking a look (now at https://github.com/broadinstitute/gatk/blob/3b72c2d9c74ae496d7d41a8eb341d0881974eb1c/src/main/java/org/broadinstitute/hellbender/tools/walkers/genotyper/afcalc/AlleleFrequencyCalculator.java#L72), I have to agree that this doesn't look right.  Rather than `(a.length() > 1 ? snpPseudocount : indelPseudocount)` shouldn't it be something like `(a.length() - ref.length == 0 ? snpPseudocount : indelPseudocount)'

**Comment by davidbenjamin** [comment]
Wow, that's really wrong.
