### ISSUE TITLE
Intended GenotypeGVCFs sharding behaviour

### ISSUE THREAD

**Issue by EvanTheB** [broadinstitute/gatk#5905]
I found that if an indel + snp combination straddles a shard boundary GenotypeGVCFs will produce different calls. More info:

https://gatkforums.broadinstitute.org/gatk/discussion/comment/58230

This is in GATK 3.7. I do not know how this issue is related, would it have been merged in 3.7? https://github.com/broadinstitute/gatk/issues/2735

What is the expected behaviour of sharding in this circumstance? I am unable to perform the test using gatk4+ as it would require immense amounts of recomputation, just to confirm a bug report. Hopefully the devs know if this is expected behaviour or has been fixed already.

**Comment by ldgauthier** [comment]
It's likely that this persists in GATK4, but this isn't high priority because in practice we've found that most of our users ignore the spanning deletion alleles or actively dislike them.  There are a variety of known issues surrounding spanning deletions, including filtering of * genotypes when the upstream deletion is filtered.

I've attached our b37/GRCh37 WGS interval list (no decoy contig), which is split at Ns in the reference.  There are 626 intervals. If recovering all the spanning deletion at shard boundaries is important to you, you can use that list to generate your shards and not subdivide further, though I can't guarantee they will be balanced.

[wgs_calling_regions.v1.interval_list.txt](https://github.com/broadinstitute/gatk/files/3116941/wgs_calling_regions.v1.interval_list.txt)

I had to add a .txt extension for Github, so you'll want to rename it.

**Comment by EvanTheB** [comment]
@ldgauthier thank you so much for your detailed answer!

I have also prepared a ~20k shard file here:

https://github.com/EvanTheB/joint_call_shards

I just avoided known gene regions. Maybe this is pointless but feels a bit safer than splitting any-old-ware.

Do you have any information about how the hg38 20k shards file was created?
