### ISSUE TITLE
Fix example command given for FilterVariantTranches

### ISSUE THREAD

**Issue by vdauwera** [broadinstitute/gatk#5964]
### Tool(s) or class(es) involved
FilterVariantTranches

### Description 
The example command line given in the tool doc (in javadoc) uses a `--tranche` argument that does not exist. Instead, the example should use the `--snp-tranche` and `--indel-tranche` arguments.

Would also be good to specify explicitly whether this tool can be used to apply VQSLOD filtering or whether it's CNN-specific.

**Comment by bhanugandham** [comment]
Thank you for catching this @vdauwera 
@lucidtronix would you like to fix this or should I?

**Comment by cmnbroad** [comment]
It would be great to also update the doc for https://github.com/broadinstitute/gatk/issues/5939 at the same time.

**Comment by lucidtronix** [comment]
@bhanugandham I have This PR makes this documentation fix: https://github.com/broadinstitute/gatk/pull/5837 But because of other changes in the PR it still requires a bit more work.  I will try to finish it up early next week, but if you want to just do the doc fixes in a separate PR I would be happy to review it.

**Comment by bhanugandham** [comment]
@lucidtronix I won't get to it until later next week myself so if this is already part of another PR then I think that should work and will be less complicated.

**Comment by ldgauthier** [comment]
Looks like this was closed via #5837
