### ISSUE TITLE
HaplotypeCaller emitting a MNP in GVCF mode when --max-mnp-distance is 0

### ISSUE THREAD

**Issue by bhanugandham** [broadinstitute/gatk#5994]
User report:
I used both GATK GenomicsdbImport and CombineGVCF, but has the same problem such as GenomicsDBImport does not support GVCFs with MNPs. MNP found at NC_035107.1:22003. Although I did not use the MNPs option in GVCF mode in HaplotypeCaller. Please any suggestions and help!!!!

This Issue was generated from your [forums] 
[forums]: https://gatkforums.broadinstitute.org/gatk/discussion/comment/58121#Comment_58121

**Comment by bhanugandham** [comment]
@davidbenjamin it seems to be an issue in `reverseTrimAlleles` at this particular site.

**Comment by droazen** [comment]
To clarify, none of our tools support GVCFs with MNPs, and this is by design. The problem here is that the HaplotypeCaller is emitting something that looks like a MNP, even though `--max-mnp-distance` is the default 0. It looks like a normal SNP whose alleles got inappropriately padded with additional reference bases.

**Comment by jamesemery** [comment]
Alright after some digging I have figured out exactly what is going on in this case. At that site (21225236) in the users sample the HaplotypeCaller has found 82 haplotypes. This is all fine and well, though might improve in the future... Anyway, among those haplotypes at position 21225236 there are 3 variants found by `untrimmedAssemblyResult.getVariationEvents()`: a spanning deletion (unintersting), a 230 base deletion, and a Snip. In `HaplotypeCallerGenotypingEngine.assignGenotypeLikelihoods()` we merge the three VariantContextObjects to create a variant context that looks like this:
```NC_035107.1 21225236    .   GGAGATTCTGTTCGAATCTCGAAAGAGATTCTGTTCGATTTTTGAAGAAGATTCTGTTCGAATCTCGAAGAAGATTCTGTTCGAATCTTGAAGAAGATTCTGTTCGAATGTTGAAAGAGATTCTGTTCGAATCTCGAAGGAGATTCTGTTCGTATCTCCAAGGAGATTCTGTTCAAATCATGAAGGAGATACTGATCGAATTTCAAAGAAGATTATGTTCGAATTTCAAATAGAG     *,ATTCTGTTCGAATCTCGAAAGAGATTCTGTTCGATTTTTGAAGAAGATTCTGTTCGAATCTCGAAGAAGATTCTGTTCGAATCTTGAAGAAGATTCTGTTCGAATGTTGAAAGAGATTCTGTTCGAATCTCGAAGGAGATTCTGTTCGTATCTCCAAGGAGATTCTGTTCAAATCATGAAGGAGATACTGATCGAATTTCAAAGAAGATTATGTTCGAATTTCAAAT,C ...```

So far so good, but then on line 181 we call `removeAltAllelesIfTooManyGenotypes();` which in turn calls `whichAllelesToKeepBasedonHapScores()`. This decides to trim the alleles down to just the two best alleles because `practicalAlleleCountForPloidy.get(100)` returns two. It just so happens the two best supported alleles based on haplotype scores are the reference allele and the G->A SNP, leaving us with a VariantContext that looks like this: 
```NC_035107.1 21225236    .   GGAGATTCTGTTCGAATCTCGAAAGAGATTCTGTTCGATTTTTGAAGAAGATTCTGTTCGAATCTCGAAGAAGATTCTGTTCGAATCTTGAAGAAGATTCTGTTCGAATGTTGAAAGAGATTCTGTTCGAATCTCGAAGGAGATTCTGTTCGTATCTCCAAGGAGATTCTGTTCAAATCATGAAGGAGATACTGATCGAATTTCAAAGAAGATTATGTTCGAATTTCAAATAGAG     ATTCTGTTCGAATCTCGAAAGAGATTCTGTTCGATTTTTGAAGAAGATTCTGTTCGAATCTCGAAGAAGATTCTGTTCGAATCTTGAAGAAGATTCTGTTCGAATGTTGAAAGAGATTCTGTTCGAATCTCGAAGGAGATTCTGTTCGTATCTCCAAGGAGATTCTGTTCAAATCATGAAGGAGATACTGATCGAATTTCAAAGAAGATTATGTTCGAATTTCAAAT ...```

Thus we have explained the users spurious MNP. There seem to be two bugs on display here, first that there should be some kind check post pruning that attempts to prune the alleles to their minimal representation, the second would seem to be the calculation `computeMaxAcceptableAlleleCount( 100, 1024 )` returned a value of 2. It doesn't seem entirely reasonable to restrict ourselves to two alleles like this. This seems like a serious limitation for mixed samples like the one the user was using, we should probably recommend as a quick workaround to the user that they increase their `--max-genotype-count` argument, by a couple of factors of 10 which would immediately alleviate the issue at this site (perhaps to 1,000,000) as well as make it possible to pick up more than two alleles for a given site. @davidbenjamin 

I will push a branch to fix the first bug but the second issue will probably beg a serious discussion about that method and why it returned the value it did.

**Comment by jamesemery** [comment]
Upon speaking with @davidbenjamin, it has become clear that perhaps changing `--max-genotype-count` is not the best solution, as that value is intended to bound our PL arrays from being excessively expanded. It is clear that instead if the user is looking to extract Allele Counts from their Pooled sample it would be best for the user to instead run Mutect, as that should sidestep the maximum of 2 Alleles per site problem that we observed. @bhanugandham

**Comment by ldgauthier** [comment]
Aha!  I think you finally found the root of a long standing issue.  Great sleuthing @jamesemery !!
