### ISSUE TITLE
Missing interval padding for HaplotypeCaller

### ISSUE THREAD

**Issue by gevro** [broadinstitute/gatk#6071]
Hi,
The HaplotypeCaller_GATK4_VCF task in the gatk4-exome-analysis-pipeline doesn't seem to add any interval padding. Shouldn't there be interval padding?

Unless the configured Broad intervals already have padding added, but it is not clear why that would be, since that same file is used for calculating HsMetrics, which should not have padding.

The question is, for my own implementation of this pipeline, should I add on interval padding to the interval list file? And if so, what size padding? Or should I add the interval padding option to the HaplotypeCaller itself in the wdl script.

Thanks for any advice on this.

**Comment by droazen** [comment]
@gevro The `HaplotypeCaller` adds padding to the intervals on its own. This is controlled by the `--assembly-region-padding` argument, which defaults to 100 bases on either side. Note that this controls both padding around user-provided intervals, as well as padding around each individual assembly region that the `HaplotypeCaller` discovers. Typically a single user interval will get divided into many assembly regions, depending on where variant activity is located.

**Comment by gevro** [comment]
Thanks, but I’m still not sure I understand.

Haplotypecaller has the following parameters:

 

Assembly-region-padding

Interval-padding

 

The differences and relationships between these are not well documented on the gatk website. From what you describe below, it would seem to suggest that assembly-region-padding is doing what interval-padding is doing. But then why would there be multiple settings for the same thing?

 

I just want to make sure that Assembly-region-padding is indeed adding intervals to the -L interval list itself, not just to the assembled regions.

**Comment by droazen** [comment]
@gevro The `--interval-padding` argument is a GATK-wide argument shared by all tools that simply adds the specified amount of padding to each `-L` interval. The `--assembly-region-padding` argument is a `HaplotypeCaller`-specific argument that adds padding to both the `-L` intervals and the assembly regions created within the intervals. It allows the `HaplotypeCaller` to keep track of which regions are part of the main intervals for calling and which are just padding regions. So with `--assembly-region-padding` you shouldn't get variant calls in your VCF that are entirely contained within the padding regions, whereas with `--interval-padding` you would, since `--interval-padding` transforms the intervals before the `HaplotypeCaller` even sees them.

**Comment by gevro** [comment]
Thanks, but I’m still not sure I understand.

What are the intervals that HaplotypeCaller “sees” at each given step:
Initial calling
Assembly
Final output
 

From what you wrote, HaplotypeCaller uses the assembly-region-adding regions for initial calling and assembly, but not final output.

But this does not make sense. Any exome calling should also include padded regions adjacent to the targeted exome regions in order to capture potential splice variants.

 

Another way to rephrase the question is this:

How precisely is the HaplotypeCaller output different when using only interval-padding vs only assembly-region-padding vs both?

 

Thanks.

**Comment by droazen** [comment]
@gevro If you want to get variant calls in your padded regions, then specify `--interval-padding`. `HaplotypeCaller` will internally add additional padding (the `--assembly-region-padding`) to the intervals during assembly to help assemble events that span off the edge of assembly regions, but it's the `-L` intervals that determine the bounds of the final callset, and these are transformed by `--interval-padding`.

**Comment by gevro** [comment]
Thank you, now I understand.

But then two more questions:
Why does the official broad gatk exome pipeline: it does not have --interval-padding set. Why is that?
 
I have tried adding --interval-padding in the past, but it causes the official broad gatk exome pipeline to crash due to resulting multiply called variants in different scatter intervals. See here for prior issue report: https://gatkforums.broadinstitute.org/gatk/discussion/11937/vcf2tiledbexception-incorrect-cell-order-found. So how can I add interval-padding to the broak gatk exome pipeline?
 

So per the above, there still seems to be some issues in the official broad gatk exome pipeline.

**Comment by droazen** [comment]
@ldgauthier As a maintainer of the exome pipeline, would you mind responding to @gevro 's question above? Thanks!

**Comment by gevro** [comment]
Thank you. @ldgauthier - do you have answers on the two questions above?

**Comment by ldgauthier** [comment]
@gevro our policy is to pad the calling intervals and not the tool arguments because there's only one interval list but multiple tool invocations.  As of today each exome target has 150bp padding on each site, which is pretty egregious, and it's on my list to trim that back to 50bp on each side.  If you add padding to HaplotypeCaller then you'll be padding the exome targets further.

If you really want more padding, the best way to do it is to add it to the calling intervals with IntervalListTools https://software.broadinstitute.org/gatk/documentation/tooldocs/current/picard_util_IntervalListTools.php (which can be called with the GATK jar).

**Comment by gevro** [comment]
Thanks very much, makes perfect sense now. I suggest this to be documented better in the GATK, exome, etc online help/tutorials/references.

**Comment by gevro** [comment]
One more question - Agilent and other exome capture kits generally provide two types of region files: Target (regions that were originally specified for the design) and Probes (what the final design actually included).
==> Which is the correct one to use for the calling_interval_list?

One could make arguments either way for Targets as opposed to Probes.
