### ISSUE TITLE
Fails to build with gradle-5.6

### ISSUE THREAD

**Issue by yurivict** [broadinstitute/gatk#6097]
See the log: https://people.freebsd.org/~pi/logs/gatk-4.1.2.0.43.log

The downstream bug report: https://bugs.freebsd.org/bugzilla/show_bug.cgi?id=239901

**Comment by lbergelson** [comment]
Gatk builds with whatever version of gradle it claims to build against, currently 5.4.1.  We don't generally support other versions.  However, I just tested locally using gradle 5.6 and it worked fine.  

I suspect there is probably some other issue with the way you are building it.  Are you trying to build it in an offline mode somehow?  It looks like maybe you're trying to use a tarball to provide the dependencies instead of letting gradle resolve them for you?  I would look into that as a possible cause of problems.

**Comment by lbergelson** [comment]
I'm submitting a pr to bump to 5.6 in case that will help.

**Comment by lbergelson** [comment]
@yurivict Gatk has now been updated to use gradle 5.6 as it's default build.

**Comment by lbergelson** [comment]
I'm going to close this since we've update to 5.6.  Feel free to reopen if you continue to have issues with it.
