### ISSUE TITLE
FilterMutectCalls stats file argument should be required

### ISSUE THREAD

**Issue by lbergelson** [broadinstitute/gatk#6124]
This [comment]( https://github.com/broadinstitute/gatk/issues/6102#issuecomment-525338908) pointed out that the the mutect stats file seems like it should be required in `FilterMutectCalls`, it's listed as optional though.

**Comment by davidbenjamin** [comment]
@lbergelson The stats file is not optional, but the *argument* is optional because by default `FilterMutectCalls` looks for the stats file produced automatically by `Mutect2` in the same directory as the output vcf.

@andrewrech The official best practices pipeline -- that is, mutect2.wdl in this repo and hosted on Terra (formerly Firecloud) -- handles this automatically.  We generally discourage users from writing their own pipelines because it takes very long and can easily yield inferior results.  Is the official pipeline missing a feature that you need?

As for backwards compatibility, while we can guarantee that `Mutect2` and `FilterMutectCalls` from the same GATK release will always work together we do not make any promises about the interoperability of different releases.

**Comment by andrewrech** [comment]
Hi David,

Thanks for your response and effort developing the best practices pipeline and GATK. I'm not certain, but I would suspect that a significant percentage of your users may also not use the best practices pipeline for one reason or another. In my particular case, I intersect calls from multiple variant callers and prefer to run this pipeline without the added abstraction of Terra (or WDL) for the sake of simplicity.

This was easy to fix on my end, thanks again.

Andrew

@davidbenjamin

**Comment by lbergelson** [comment]
@davidbenjamin Ah, that makes sense.  Thanks for clarifying
