### ISSUE TITLE
GATK docker image uses outdated samtools

### ISSUE THREAD

**Issue by michaelgatzen** [broadinstitute/gatk#6148]
The GATK docker image uses samtools version 0.1.19 instead of the current version 1.9 and can therefore not read `gs://` resources.

Samtools is installed in the gatkbase image via apt-get, the recent releases are not available there. Instead, it would have to be built manually (see http://www.htslib.org/download/).

**Comment by droazen** [comment]
@lbergelson Did we resolve this one?

**Comment by mwalker174** [comment]
I just built the base image locally and it installs samtools v1.7:
```
(base) markw@WMC9F-819:~/IdeaProjects/gatk/scripts/docker/gatkbase$ docker run 53df03aff4c5 samtools
Program: samtools (Tools for alignments in the SAM format)
Version: 1.7 (using htslib 1.7-2)
```
I'm not sure why then the latest gatk images are still on 0.9.19?

**Comment by droazen** [comment]
I believe this is fixed in the newest GATK base image, which will be included in the upcoming GATK 4.1.8.0 docker image.

**Comment by samuelklee** [comment]
I think the upgrade to samtools was simply a consequence of changing the base image from Ubuntu 16.04 -> 18.04 in #5026, since samtools is simply installed using apt-get. If we want to be more specific about which versions of samtools, bedtools, tabix, etc. are included in the Docker images, we may want to build these accordingly.

**Comment by droazen** [comment]
Fixed in https://github.com/broadinstitute/gatk/pull/5026 and GATK 4.1.8.0 -- closing.
