### ISSUE TITLE
 how to use --intervals in HaplotypeCaller？

### ISSUE THREAD

**Issue by ccartermices** [broadinstitute/gatk#6199]
Hi! I want to know how to use --intervals in HaplotypeCaller？Should i input a txt file? Or a vcf file?

**Comment by lbergelson** [comment]
Gatk tools accept a number of different options for the --intervals (-L) argument.  
You can pass an interval directly to the option or use an interval file, or a mixture of the two.  A vcf file works.

There's a pretty detailed explanation [here](https://software.broadinstitute.org/gatk/documentation/article?id=11009).  

For production work we recommend a picard style interval file as detailed there since it comes with a sequence dictionary and helps prevent mix ups.

For doing stuff interactively I typically use somethings like `-L chr2:1000:2000`
