### ISSUE TITLE
PR for GenotypeGVCFs and Non-variant Sites?

### ISSUE THREAD

**Issue by bbimber** [broadinstitute/gatk#6239]
Hello,

I'd like to see if your team would potentially be willing to accept a PR to add a feature to GenotypeGVCFs.  The general problem is this:

1) When running GenotypeGVCFs, the default is to output variant sites, and this will therefore vary based on the set of samples.  While there is an argument to include every site, calling against every position of the genome takes a very long time.
2) As you know, a VCF file generally only includes variable sites in the current samples.  Therefore, this doesnt differentiate between the situation where all samples have no data and when all samples are wild-type.
3) We want to merge VCFs with data from different cohorts, including WGS and WES.  It's just not practical to call 1000s of samples as one unit through GenotypeGVCFs (we're constantly adding new data and would need to keep re-calling).  When merging these VCFs, we see a problem that is especially acute at sites with relatively rare variants.  If the variant is only present in one or a few input VCFs, the other VCFs frequently lack that site (they are all wild-type).  On merge, this is interpreted as no-data, which can be misleading.  

The best solution I can devise is to force the input VCFs to output at a whitelist of sites, including if all samples are non-variant.  While GenotypeGVCFs can be made to output at every genomic position, outputting everything is a huge leap in computational time.  

I would propose to make a PR to augment GenotypeGVCFs to support an "--always-output-calls-whitelist" argument.  The user can provide a FeatureInput.  If provided, GenotypeGVCFs would output all variable sites (existing behavior), and also output any position spanning the intervals of this file, even if all samples at wild-type.  

I only just started to look at how to implement this - i can some back with a more specific proposal. However, my initial thought is that we need to hook into drivingVariants or LocusWalker.traverse.

Does your team have any thoughts on this, before we spend too much time on it?  Thanks.

**Comment by droazen** [comment]
@ldgauthier / @lbergelson What are your thoughts on this proposal?

**Comment by ldgauthier** [comment]
If I understand correctly, @bbimber, this sounds a lot like the `--genotype-given-alleles` change David B. made recently -- discover new sites in the provided samples, but _also_ output calls against the variants specified in the resource file.  This is a small change from what you propose because the resource file would specify a particular ALT allele, so if you were interested in positions where you haven't seen a variant yet we'd need to extend functionality to call against <NON_REF> and output or you could put some random placeholder allele, although the identity of that allele would affect your likelihoods.  On the other hand, having an ALT specified from a previous cohort would improve your likelihoods for all-reference cohorts compared to what you get now for non-variant site output.

**Comment by bbimber** [comment]
@ldgauthier - is this --genotype-given-alleles feature documented somewhere?  i dont see mention of it in the git repo - maybe there's a feature branch?  You write "so if you're interested in positions where you havent seen a variant yet" - are you referring to the situation where a position exists in the reference VCF, but there is no evidence of variation in any of the gVCFs/samples being called?  

To make sure I understand this new feature: what I am trying to accomplish is conceptually pretty similar to providing a dbSNP reference VCF and expecting that my output would contain a call for every site/allele in that reference, plus any non-variant above-and-beyond that baseline.  

I'm not sure if this is quite your question, but I could live with alleles being dropped in the output if they are not present in the gVCF data.  I'm assuming that any of these additionally output sites would probably be 100% reference.  An output that contains this site, shows only one allele, and lists all the samples as either reference or not callable would be adequate for downstream merging, unless I miss something.  If the VCF we create can contain the same list of alleles are the reference VCF, that's perfectly fine too.

**Comment by ldgauthier** [comment]
I should have been more specific.  `--genotype-given-alleles` is HaplotypeCaller functionality, which is very similar if not outputting GVCFs.

If providing dbSNP is similar to something you might want to do, then I think this approach will work.  My concern was that if you were interested in a particular locus, but had never seen a variant there in any sample (i.e. didn't have an ALT allele to compare to), that implementation could get tricky.  We should be able to output 100% reference sites with what I have in mind.

@davidbenjamin while you're waiting for the restoration of the TCGA data, would you be interested in extending GGA mode to GenotypeGVCFs?  (Obviously without the graph part.)

**Comment by davidbenjamin** [comment]
Let me paraphrase to see if I understand:

*  `GenotypeGVCFs` gets an `--alleles` argument just like HC and M2.
*  Pass this `FeatureInput` to the `GenotypeGVCFsEngine` so that the output VC has genotypes for all given alleles.

I'm hardly familiar with `GenotypeGVCFs` but it looks like we need to modify `regenotypeVCs`, for example the line 
```
if (GATKVariantContextUtils.isProperlyPolymorphic(regenotypedVC) || includeNonVariants)
```
We might also need to change something upstream in the walker's traversal so that we don't skip sites with nothing in the input VCFs.

If this is not too much of an underestimate then I can give this a try.

**Comment by bbimber** [comment]
@davidbenjamin : my read of the code is that yes, we would need to alter traversal.  It is worth pointing out that GenotypeGVCFs already supports the "--includeNonVariantSites" argument, which is similar.  The difference between what I propose and --includeNonVariantSites is that this new option would only output a site if present in the provided whitelist file.  

I briefly looked at the guts of traversal - my guess is that we could do one of two things: a) make GenotypeGVCFs use some kind of MultiVariantWalker logic (not impossible, but more invasive), or b) traverse every site, but only output the site if non-variant or if present in the whitelist FeatureInput.  The latter breaks some of the benefits of this over --includeNonVariantSites; however, at least it's not writing the output for most.

If you are willing to look at this great, though I'm also happy to take a stab at it.
