### ISSUE TITLE
GenomicsDBImport doesn't complete

### ISSUE THREAD

**Issue by mbrieuc** [broadinstitute/gatk#6321]
We have WGS for more than 800 samples of cod. We are trying to genotype them with GATK, but we cannot get GenomicsDBImport to complete. It seems to run fine but we get the following message at the end of our slurm output file: "slurmstepd: error: Exceeded step memory limit at some point." We're running it one chromosome at a time.
We're running it with:
#SBATCH --mem-per-cpu=100G
#SBATCH --partition=hugemem
#SBATCH --cpus-per-task=2

--java-options "-Xmx190g -Xms190g" 
--batch-size 50 --consolidate
   
Could you help us optimize it so it actually runs and completes?
Thanks a lot

**Comment by mlathara** [comment]
Hello,

GenomicsDB developer here - I'm not super familiar with SLURM...can you tell if your job was actually terminated or was that just a warning of sorts? Also, can you use `saact` command to find the memory usage of the job? Do your logs tell you how many batches have made progress before you see the error above?

Also, is this difference intentional or...?
> #SBATCH --mem-per-cpu=**100G**
vs
> --java-options "-Xmx190g -**Xms190g**"

Lastly, you could try reducing the batch size down (let's say something like 10, just to see if it makes the error go away) or splitting up into smaller intervals than chromosomes (say, split into intervals of size 50 million) and see if that makes a difference. The idea with each of these is to lower memory usage.

**Comment by droazen** [comment]
This should be resolved in GATK 4.1.8.0 with the new `--genomicsdb-shared-posixfs-optimizations` argument -- closing.
