### ISSUE TITLE
FilterAlignmentArtifacts Invalid Intervals and Segmentation Faults

### ISSUE THREAD

**Issue by bklein345** [broadinstitute/gatk#6344]
### Affected tool(s) or class(es)
_FilterAlignmentArtifacts_

### Affected version(s)
- [x] Latest public release version [4.1.4.1]

### Description 
FilterAlignmentArtifacts consistently errors out with segmentation faults or IllegalArgumentExceptions. I've attached the log files for each of these errors below.
[invalid_interval.log](https://github.com/broadinstitute/gatk/files/4017907/invalid_interval.log)
[seg_fault.log](https://github.com/broadinstitute/gatk/files/4017908/seg_fault.log)

#### Steps to reproduce
The command to reproduce both errors is the same, and I have attached it below.
[realignment_filter.txt](https://github.com/broadinstitute/gatk/files/4017918/realignment_filter.txt)
The BWA mem index I'm using is hg38, however the BAM that I am realigning from is hg19; thus, the reference argument is the hg19 fasta. I am happy to transfer zip files containing the other files need to reproduce this. Just let me know where to send them.

#### Expected behavior
_FilterAlignmentArtifacts_

#### Actual behavior
_Errors_

**Comment by lbergelson** [comment]
@bklein345 It looks like you're encountering 2 distinct bugs.  

1.  There seems to be a nasty off by 1 error which needs to be fixed in the code.
@davidbenjamin This method has at least 1 bug (and I think 2). https://github.com/broadinstitute/gatk/blob/9bca5119e996886ee85ef6c890eba79ec5d6cfb1/src/main/java/org/broadinstitute/hellbender/tools/walkers/realignmentfilter/RealignmentEngine.java#L135-L137
    1. It needs to convert from [0,1) coordinates to [1,1].
    2. There is no guarantee that the reference index corresponds to the contig with the same number, and I think in practice it probably won't ever, since the reference indexes start at 0 but contig naming starts at 1.  There may also be confusion between the realignment reference and the reference from the original file but I haven't looked closely enough. 



2.  It looks like you're also hitting a non-deterministic error in the accelerated smith waterman which should be able to be worked around by specifying `--smith-waterman JAVA` .

**Comment by davidbenjamin** [comment]
@lbergelson I agree with your point (i).  Point (ii) as well, but this doesn't make any difference because once we have the realignments we don't compare them to any reference -- neither the hg19  as in the original reads nor the hg38 of the BWA index.  Instead we check them amongst themselves for multi-mapping.

@bklein345 Where does your BWA mem index image come from?  The error `Contig:628 start:0 end:195` suggests that reads are realigned to an alt contig with a length of 195.  I don't think this should be happening in the most recent BWA mem index image we put in the best practices bucket, which was generated from an hg38 without the alt contigs.

**Comment by davidbenjamin** [comment]
(That said, it's still a bug because it should work with any index image).

**Comment by davidbenjamin** [comment]
Okay, there's the bug fix PR.  @bklein345 the PR will close this ticket but please re-open if the error persists.  Here's a jar to test: gs://broad-dsde-methods-davidben/gatk-builds/realignment_patch.jar
