### ISSUE TITLE
What's the meaning of the column REF and ALT in the VCF (Variant Call Format) file?

### ISSUE THREAD

**Issue by singletrips** [broadinstitute/gatk#6347]
Is the REF allele is the allele in the reference genome, and the ALT allele is the allele in the sample we are studying?

**Comment by davidbenjamin** [comment]
@singletrips Please see the bottom of p. 7 and top of p. 8 in this document: https://samtools.github.io/hts-specs/VCFv4.3.pdf

**Comment by ldgauthier** [comment]
The spec doesn't define very many requirements with respect to those fields http://samtools.github.io/hts-specs/VCFv4.2.pdf

In GATK, except in the case of the Germline Copy Number tools, the reference allele is populated from the input reference genome.  For GCNV all REFs are Ns because they span large intervals and the ALT alleles are <DEL> or <DUP>.  In the single-sample SNP and indel case ALT is usually the variant allele found in the input sample, but VCFs with ALT alleles that are not called in the genotypes are still valid.
