### ISSUE TITLE
NullPointerException from GenotypeGVCFs 

### ISSUE THREAD

**Issue by mlathara** [broadinstitute/gatk#6548]
This is based on some digging for a user query here: https://gatk.broadinstitute.org/hc/en-us/community/posts/360060283092-GenotypeGVCFs-java-lang-NullPointerException

The background here is that GenomicsDB added support for 64 bit INFO fields starting 4.1.5.0. When using bcf codec, GenomicsDB will pass a 64 bit type to GATK, which isn't supported by GATK. But instead of flagging that as a missing type, it seems like GATK still tries to decode the missing type hitting the NPE. We probably want to throw a better error so the user knows what the issue is.

**Comment by amizeranschi** [comment]
Hi! It would be great to see this issue addressed, as the error message that is generated is quite cryptic.

**Comment by droazen** [comment]
@amizeranschi Have you tried running with the `--genomicsdb-use-vcf-codec` argument as a workaround?

**Comment by amizeranschi** [comment]
@droazen I didn't get a chance to do this yet. Once I do (most likely during next week), I will post here about any progress. However, as per @mlathara's message (https://github.com/broadinstitute/gatk/issues/6667#issuecomment-646167430), I do expect this to fix the issue. This potential fix has already been implemented by the bcbio_nextgen guys, so I'm going to be testing that precisely  (https://github.com/bcbio/bcbio-nextgen/commit/336920a630d7f50b341eeeb4bad4ea6ab213f995).

For what it's worth, I do think that setting up the VCF codec as default (instead of BCF) makes sense, at least until this bug is fixed. https://github.com/broadinstitute/gatk/issues/6667#issuecomment-646232210

**Comment by droazen** [comment]
Resolved by https://github.com/broadinstitute/gatk/pull/6675
