### ISSUE TITLE
hg38 dbSNP has incorrect contig names

### ISSUE THREAD

**Issue by jonn-smith** [broadinstitute/gatk#6564]
The data source for dbSNP for hg38 has contig names numbered differently than our hg38 reference.

Specifically, the hg38 contigs in dbSnp for hg38 are named `1` ,`2`, `3`, ... `X`, but our reference is `chr1`, `chr2`, `chr3`... `chrX`

This manifests as no annotations for dbSNP being annotated on hg38 data.

**_This is an issue in dbSNP and not with funcotator._**  The raw data source in dbSNP has the differing contig names, so if it were downloaded directly this problem would persist.

It is not clear why our hg38 contig names are different from theirs, nor whose are correct.

We need to release new funcotator data sources that have a version of dbSNP for hg38 with the contig names changed to fit our reference.

**Comment by ldgauthier** [comment]
I do already have a chain file for this if that's helpful: https://github.com/broadinstitute/palantir/blob/master/Resources/restorehg38contigNames.chain

**Comment by lbergelson** [comment]
Which are the official hg38 names?

**Comment by droazen** [comment]
@lbergelson This was discussed recently in the methods slack channel. A lot of us were under the impression that with hg38 the world had standardized on the UCSC naming scheme (chr + N), but the reality is that even with hg38/GRCh38, UCSC continues to use the chr prefix, while NCBI and Ensembl don't.

**Comment by levinyi** [comment]
still  watching...

**Comment by jensenrichardson** [comment]
> I do already have a chain file for this if that's helpful: https://github.com/broadinstitute/palantir/blob/master/Resources/restorehg38contigNames.chain

@lbergelson I've been reading through this thread as I've tried to get dbSNP to work with Funcotator using GRCh38. I saw this chain file mentioned, but I was unable to access it. Are you able to share it with the public in the meantime, while you work on the more permanent solution, or should I look at trying another method?

**Comment by jonn-smith** [comment]
I have a candidate release of the Funcotator data sources which includes a fixed dbSNP that I'm testing now. I am hopeful it will be ready by the end of the week.  

When it is ready you'll be able to grab it and run off the latest nightly build / master and this problem will be fixed.

**Comment by jonn-smith** [comment]
@jensenrichardson I put a copy of the file in the same google bucket as the funcotator data sources here: 

`gs://broad-public-datasets/funcotator/restorehg38contigNames.chain`

It's public so you should have access.

**Comment by jensenrichardson** [comment]
@jonn-smith Thanks so much for the chain file! I was able to do the liftover successfully (it liftedover all of the variants in the database, except for the MT chromosome, but those aren't important to my analysis so I was okay with discarding them), but it still had no hits from dbSNP.

I think it was able to find the liftedover version because of this line in the log file:
`16:08:10.211 INFO  DataSourceUtils - Resolved data source file path: file:///scratch/07467/jwr2735/somaticPipeline/hg38_All_20170710.liftover.vcf -> file:///scratch/07467/jwr2735/somaticPipeline/./req-files/funcotator_dataSources.v1.6.20190124s/dbsnp/hg38/hg38_All_20170710.liftover.vcf`

But I think it was unable to match any of them up because of this line:
`17:02:30.691 INFO  VcfFuncotationFactory - dbSNP 9606_b150 cache hits/total: 0/490587`

If I grep for 'db' then these are the only line from the entire funcotator log file:
`16:08:10.156 INFO  DataSourceUtils - Resolved data source file path: file:///scratch/07467/jwr2735/somaticPipeline/Cosmic.db -> file:///scratch/07467/jwr2735/somaticPipeline/./req-files/funcotator_dataSources.v1.6.20190124s/cosmic/hg38/Cosmic.db
16:08:10.211 INFO  DataSourceUtils - Resolved data source file path: file:///scratch/07467/jwr2735/somaticPipeline/hg38_All_20170710.liftover.vcf -> file:///scratch/07467/jwr2735/somaticPipeline/./req-files/funcotator_dataSources.v1.6.20190124s/dbsnp/hg38/hg38_All_20170710.liftover.vcf
16:08:11.585 INFO  DataSourceUtils - Resolved data source file path: file:///scratch/07467/jwr2735/somaticPipeline/Cosmic.db -> file:///scratch/07467/jwr2735/somaticPipeline/./req-files/funcotator_dataSources.v1.6.20190124s/cosmic/hg38/Cosmic.db
16:08:18.498 INFO  DataSourceUtils - Resolved data source file path: file:///scratch/07467/jwr2735/somaticPipeline/hg38_All_20170710.liftover.vcf -> file:///scratch/07467/jwr2735/somaticPipeline/./req-files/funcotator_dataSources.v1.6.20190124s/dbsnp/hg38/hg38_All_20170710.liftover.vcf
16:08:18.498 INFO  DataSourceUtils - Setting lookahead cache for data source: dbSNP : 100000
16:08:23.057 INFO  FeatureManager - Using codec VCFCodec to read file file:///scratch/07467/jwr2735/somaticPipeline/./req-files/funcotator_dataSources.v1.6.20190124s/dbsnp/hg38/hg38_All_20170710.liftover.vcf
16:08:24.823 INFO  DataSourceUtils - Resolved data source file path: file:///scratch/07467/jwr2735/somaticPipeline/hg38_All_20170710.liftover.vcf -> file:///scratch/07467/jwr2735/somaticPipeline/./req-files/funcotator_dataSources.v1.6.20190124s/dbsnp/hg38/hg38_All_20170710.liftover.vcf
16:08:26.271 INFO  FeatureManager - Using codec VCFCodec to read file file:///scratch/07467/jwr2735/somaticPipeline/./req-files/funcotator_dataSources.v1.6.20190124s/dbsnp/hg38/hg38_All_20170710.liftover.vcf
17:02:30.691 INFO  VcfFuncotationFactory - dbSNP 9606_b150 cache hits/total: 0/490587`
Hope this is useful.

**Comment by droazen** [comment]
Closing -- this was fixed in GATK 4.1.9.0.

**Comment by matteocostacurta** [comment]
@jonn-smith 

Sorry to bother, how do I apply the chain file to fix the issue with annotating dbSNPs? I am having this same issue - when I generate .maf files and try to visualise them with maftools on RStudio I only see NAs in the dbSNP column.
