### ISSUE TITLE
How to go backwards from a multi-sample vcf to get raw files for joint calling

### ISSUE THREAD

**Issue by tmm211** [broadinstitute/gatk#6596]
# Feature request 

### Tool(s) or class(es) involved
HaplotypeCaller, CombineGVCFs, GenotypeGVCFs

### Description
New capability to go backward from a multi-sample vcf generated by CombineGVCFs or GenotypeGVCFs to individual gvcfs so that a user can joint-call again with another cohort.
This request came about because a [user posted on the forum](https://gatk.broadinstitute.org/hc/en-us/community/posts/360060957571-Empty-vcf-after-GenotypeVCFs-when-combining-already-genotyped-samples) the following scenario:

1. Cohort: VCF with SNPs called with HC per sample and CombineGVCFs, GATK 3.5 (older samples, no bams available.
2. Cohort: VCF/gVCF/BAM/fastq available (new samples). GATK 4.1.2.0.
Ideally, combine using joint genotype calling from genotype likelihoods (annotations are available in both VCFs - mixed ploidy.)

HOWEVER when using CombineGVCFs to combine the two files the result looked incorrect.
`gatk CombineGVCFs -R ref.fasta -V tetra.vcf.gz -V mixed.vcf.gz -O merged.vcf --tmp-dir $TMPDIR`
Result: For ALT alleles it removes the known allele and replaces it with <NON-REF>  for all loci. Even if I run CombineGVCFs with just one of the files `gatk CombineGVCFs -R ref.fasta -V tetra.vcf.gz -O foo.vcf`.
When I then run GenotypeGVCFs only the header of the new, called vcf but nothing below the #CHROM line.
`gatk GenotypeGVCFs -R ref.fasta -V merged.vcf -O merged_GT.vcf --tmp-dir $TMPDIR`

The user came up with this approach, but it is not ideal:

grep -vE "NON_REF" mixed.vcf > mixed.mod.vcf # removes all loci with NON_REF as ALT
grep -vE "NON_REF" tetra.vcf > tetra.mod.vcf
GATK 3.7 CombineVariants
SelectVariants -select 'set == "Intersection"'

----

**Comment by ldgauthier** [comment]
I'm pretty sure that GATK 3.5 is from when we were still using the median of MQ scores rather than summing up the squared MQs and then taking the square root of the average when we're all done, as we do now.  In that case, those GVCFs aren't truly compatible with GATK 3.7 and beyond.

I would never want to output individual GVCFs made from a cohort GVCF because the per-sample annotations will be invalid.  (We lose count of which reads belong to which sample when we sum the counts.). If we were to ever do this, we'd have to do it on the fly so that the per-sample GVCF-like representation is internal. But when we discussed this at the triage meeting, it seemed like it was low priority because the use case is not so prevalent.

**Comment by droazen** [comment]
Closing based on @ldgauthier 's comment above that there's no way to go backwards from cohort to individual GVCFs without producing invalid annotations.
