### ISSUE TITLE
[Mutect2] How to emit only one alt allele,not multi-allele?

### ISSUE THREAD

**Issue by xiucz** [broadinstitute/gatk#6603]
Hi ,
The parameter `--max-alternate-alleles` seems no longer in the new version gatk4.1.7.0...How can I get only one alt allele in the vcf, or how to filter it?

Thank you,
Xiucz

**Comment by davidbenjamin** [comment]
`FilterMutectCalls` has always and continues to filter multiallelics by default, except in mitochondria mode.  You may adjust this with the `max-alt-allele-count` argument.  `-max-alternate-alleles` is a `HaplotypeCaller` argument that appeared in `Mutect2` due to excess inheritance in the class hierarchy.  I don't believe it ever had any effect in `Mutect2`.

**Comment by xiucz** [comment]
I see the `max-alt-allele-count` argument in `FilterMutectCalls ` now. But maybe it is used to filter the multiallele sites. 

Sometimes, when I want to force call some cosmic hotspot sites in Mutect2 `GGA` mode,  this parameter may be helpful.

Thank you.

**Comment by davidbenjamin** [comment]
We're moving in a direction where `FilterMutectCalls` can decide which alleles in a multiallelic site to keep, but because multiple alleles are such a strong signal for filtering I don't think we would want `Mutect2` to silently drop alleles, except those that are obvious sequencing errors as in the current case.  This `HaplotypeCaller` argument isn't anything principled; rather it keeps down computational costs.
