### ISSUE TITLE
GenomicsDB Scatter/Subsetting

### ISSUE THREAD

**Issue by bbimber** [broadinstitute/gatk#6620]
Hello - I'm not sure if you want me using issues for feedback, but i thought I'd pass this along.  In another thread we discussed how to possibly do scatter/gather processing of GenomicsDB workspaces. The general idea is that we want to have long-lived workspaces to which we will repeatedly add more samples. Executing this append would be a lot more convenient to do scattered over intervals. Since GenomicsDB already has the data organized into folders by interval, I figured we might be back to manually split one workspace apart by copying each contig's folder out to make a new workspace, execute the merge over that interval, and then copy them back together. So far as I can tell this works.  It seems like it will significantly speed the process of creating new workspaces and also adding samples.  As I said on the other thread, since your docs recommend making a backup of a workspace before trying to append samples anyway, copying it out into new working folders to execute that append step isnt all that different.  I realize we're doing a non-supported thing here. I post simply to mention that this scheme seems like it will be quite useful and I hope you might keep it in mind as GenomicsDB evolves.

**Comment by droazen** [comment]
@nalinigans @mlathara Is this an approach we could officially test and endorse? Do you foresee any technical issues with this approach with the current release of GenomicsDB?

**Comment by mlathara** [comment]
@bbimber question for you - what is the primary motivation for wanting to merge the scattered workspaces back into a single workspace here? I'm assuming the scatter is because you have a large enough dataset that you need multiple nodes to run the import in parallel. (side note: we're planning on enabling reading vcfs through native htslib in GenomicsDBImport which should drive down memory usage for cases that are able to take advantage of that route. This might make it more feasible to use `--max-intervals-to-import-in-parallel` for multiple threads on a single node ).

If the large dataset is the primary reason, wouldn't you want the benefits of distributed processing on the query side as well? You mentioned in the previous thread that you saw the fact that a single workspace is a valid GenomicsDB workspace as a benefit...and that's certainly true - but if performance is the driving factor then it might be worth it to keep the workspace separate.

@droazen Could you elaborate on what you envision we should do here? This approach should work as long as the same command line is used for each import with a different/unique interval list each time. Are you asking for a test case to be run just for sanity? Or add test cases to GATK? Or add a tool to do this...?

**Comment by bbimber** [comment]
@mlathara Our primary use case involves calling variants on a constantly growing large dataset of WGS and WXS data. As you probably realize, the CombineGVCFs/GenomicsDBImport step is incredibly time consuming, and scatter/gather is pretty much essential to make these operations work in any halfway reasonable period of time. I have off-hand heard people from the broad mention large WXS datasets, and keep in mind we're working mostly w/ WGS.

Regarding processing: our main downstream use right now is GenotypeGVCFs, and yes we expect to run that scatter/gather as well.  I agree that in principle we could maintain these data as a folder of workspaces. In fact that was my original plan before I realized the GenomicsDB workspace already is essentially a folder of per-contig folders. The reason I like the solution of copying around the folders is b/c our end product is in an official file format that tools understand how to use.  

A related point, before we decided to try GenomicsDB, my plan was to create a scheme ("file format") that would allow our code to better operate on a folder of per-contig CombinedGVCF file.  I would probably have written out a top-level JSON file that served the same purpose as the JSON files in a GenomicsDB workspace. As noted above, GenomicsDB is essentially already doing this for me.

To the question about usage and support: perhaps that ways to think about this would be interval-based split and merge tools for GenomicsDB workspaces?  This would obscure the internal structure of the workspace from the user (even if they basically just to folder copying).  The split tool should be really simple and not have many caveats. The merge tool could have a lot of limits on what kind of workspaces can or cannot be merged. Perhaps it could do sanity checking on the JSON files to make sure they're compatible, and then copy the folders into this new merged workspace?

**Comment by mlathara** [comment]
Hi @bbimber -- just circling back here. We're considering if there's a useful addition to the tool that can be made here. 

Can you state again what you see as the benefits of a merged workspace? Said another way, if there's enough data to require multiple/distributed workspaces for import, how are you using the workspaces such that a merged workspace makes more sense than a distributed one?

**Comment by bbimber** [comment]
@mlathara :

1) I would argue there is value in leaving the ending data as a valid file format. In theory a growing number of tools will be able to interpret GenomicsDB data.  In contrast, if the end product is a random set of directories, there is basically no possibility any standard tools can operate on it, without custom work. 

2) In principle, one could want to create and process a workspace using a different set of intervals for the scatter/gather operation.  A valid reason for this difference could include usage of your cluster at the time you're trying to kick off that operation. If the end product is a valid GenomicsDB workspace, as opposed to random directories, it would not take an special coding to act on any valid combination of intervals.

**Comment by mlathara** [comment]
1. Why can't standard tools operate on the distributed workspaces? You could run `GenotypeGVCFs` on these workspaces in a distributed fashion and then concatenate the results together if you want. I think you were initially considering this route - and still think it would be more performant.

2. Again, you can process/query a whatever set of intervals you want -- in a distributed fashion, right?

**Comment by mlathara** [comment]
I should say the other reason I'm poking at this is because we are considering other ways to enable parallelized imports across nodes, which would write to a single workspace. You'd need a shared filesystem visible across all nodes, of course. That would remove the need to merge workspaces.

Since a lot of the discussion here has been around merging workspaces with different interval lists, I'm trying to specifically understand that use case and what you see as the benefits of this workflow. Does parallelizing import in a way that doesn't require multiple workspaces render the merging discussion moot for you?

**Comment by bbimber** [comment]
1) sure, different parallelization might change the thinking. As I pointed out in a different thread, if your recommendation is still to copy the workspace prior to merging/appending to it, then the distributed processing still means copying the original, and to my thinking copying each contig's folder into a new workspace, vs. copying each contig into the same workspace is basically the same overhead.  We also tend to keep the long-lived copy on our warm storage, with processing happening on our cluster's lustre filesystem. 

2) Again, i dont think it's necessarily right to assume every job will operate on the same set of intervals. We generally would use the same pattern, but there are legitimate cases in which different intervals/job would better match the cluster's availability.  If we're appending a limited number of samples and our cluster is busy, we might want to scatter using more intervals/job since each job would finish fairly quickly and the practical reality is fewer total jobs would complete quicker.  if we are performing an operation that requires a lot of time/job (like creating a new workspace or appending a lot of samples), we might do one job/contig.  It's also worth pointing out that macaque has 1000s of small unplaced contigs, and therefore we almost never do a simple 1:1 job:contig scheme.
 
3) When I was originally thinking about how to scatter/gather the creation of a combined gVCF, the overhead of re-merging was huge. There was zero point in taking the per-contig gVCFs and concat/bgzipping a new one, just to split it again.  When I started down this road, my idea was to make a folder holding each gVCF, and a top-level JSON file to map contig->filepath, so code could intelligently work with these.  The latter essentially describes the structure of a GenomicsDB workspace. Unlike concatenating gVCFS, the overhead of moving directories around is practically zero. Sure, I could make a folder of GenomicsDB workspaces, but if I'm already moving them, what's the point in not merging?  

I could understand that is the workspace lived on a shared filesystem and was always going to exist in that location (which I still have trouble squaring with the recommendation to back it up prior to appending), then the splitting/merging we've been doing does not make sense.  As it stands, however we store them we're going to need to make copies, so there doesnt seem to be much reason not to.

**Comment by mlathara** [comment]
We recommend backing up data just because it is the "cleanest" way to roll back. If backing up data is really such a pain point, you could skip doing that. Just back up the callset.json file, and don't turn on `--consolidate` when you're doing incremental import. If a failure happens, just roll back the callset.json and re-do the import. The downside is that the failed import will hang around and take up disk space, but hopefully it is a rare enough occurrence that it doesn't matter - and you will have saved yourself backing up the data.

In response to 2) - I guess you're implying that the overhead of cluster/job scheduling won't amortize any benefits from parallelism there? I suppose that could be true, but doesn't seem to be worth optimizing towards that.

What I'm asking is whether split and merge are purely an instrument to allow you to choose the granularity of parallelism you want to use? Or is there something else? As I said before, we are considering enabling other ways to do distributed import which would work for the former. It might go something like:
- Create a workspace/initialize configuration+intervals to be imported
- Actually do the import by kicking off (multiple) import(s). User can pick the number of intervals each import is responsible for. User must ensure that no interval gets specified in multiple import processes.

P.S: regarding 1000s of small contigs - the current GenomicsDBImport doesn't so so well with large number of contigs (unless you do concatenate the contigs into fewer groups). We hope to have some changes coming soon that will help with that by adding an option for the tool to merge multiple contigs into a single folder in the workspace.

**Comment by bbimber** [comment]
@mlathara I think we're talking a bit in circles.  The main use case I foresee for a generic split/merge tool would be to allow parallelized processing.  I cant say there wouldnt be other uses I'm not seeing now (in the VCF world, SelectVariants is an extremely useful tool), but i dont have a specific use-case for GenomicsDB subsetting today beyond this. 

I would point out this rapidly gets into specifics and quirks of any one user's infrastructure.  I dont actually mind copying the GenomicsDB workspace prior to appending to it, because processing occurs on shared lustre space, while our permanent data lives on other disk space.  Therefore we would probably do a copy no matter what.  I agree you dont want to develop our one person's infrastructure.  

The only aspect that gives me pause on your plan regarding split jobs is that GATK doesnt provide the scheduler.  Sure there used to be queue and I gather GATK pushes WIDL/Cromwell (unless this changed), but we never used these.  If GATK is not trying to provide the scheduler (which is better), does this really just look like: 

1) kick off X independent jobs for GenomicsDB/append
2) each job specifies the interval(s) on which to operate
3) Each job has no knowledge of the other jobs
4) each job writes it's output to the same workspace
5) Presumably there is something in place so jobs can run concurrently.  This must be the new feature?

I imagine this could work.  It does obligate one to have/use some kind of shared disk space, which we can handle, but could be a negative for some.

**Comment by mlathara** [comment]
Agreed that it would be nice if we abstract away the manner in which import tasks get distributed across multiple nodes. At this point, we're not considering adding a tool that supports that. Sure, we could probably look at Spark or something, but it 
a) is a heavier lift 
b) would probably involve assumptions about user infrastructure

I'm reluctant to support generic split/merge because then we'd be tied to this notion of a meta-workspace (or workspace of workspaces), and how to cleanly track/manipulate those. I'd like to avoid that potential can of worms. Of course, users are free to work with it themselves. 

The steps 1-5 you outline match roughly what we have in mind, though there would be a step 0 for initializing the workspace. We haven't decided yet if each independent import job would specify the intervals, or have all the intervals to be imported specified in the initialize phase and then the independent import jobs select intervals by specifying a range of indices/ranks corresponding to those intervals. 

Doing the latter would piggyback a bit on how incremental import is currently done. It would also better support the multiple contigs in a single folder mode I mentioned in the last comment.

**Comment by bbimber** [comment]
The proposal for a more officially support scatter/gather seems in theory OK to me.   I was not proposing GATK make a scheduler and was agreeing that is problematic/difficult for you to realistically do that. I would tend to strongly favor keeping those more separate

**Comment by bbimber** [comment]
I would appreciate if anyone could comment on the probable bug we're seeing with GenomicsDB input / GenotypeGVCFs and --force-outout-intervals, here: #7005 ; however, we can probably close this issue.
