### ISSUE TITLE
Add alternate/optional `sample-index` argument for PostProcessGermlineCNVCalls

### ISSUE THREAD

**Issue by ldgauthier** [broadinstitute/gatk#6659]
PostProcessGermlineCNVCalls is currently single-sample, using input calls and model for the whole cohort.  Specifying a sample index is not particularly user friendly.  Given that we already output calls as a directory of files, including a sample map could enable the user to specify a sample name rather than an index.  This would involve changes to GermlineCNVCaller as well.

Alternatively, extending PostProcessGermlineCNVCalls to process all the samples at the same time would eliminate this problem and allow us to avoid some irritating transposes by parallelizing by shard instead of by sample.

**Comment by samuelklee** [comment]
We can add this as an option, but I think there are a few arguments against outright replacement (which may have led to this design decision in the first place):

1) I don't believe any CNV tools take in sample name as input at the GATK command line, by design. We instead take the BAM basename as the entity ID during the CollectCounts task; this ID is then passed along at the WDL level and is only used to construct the filenames of output files. This obviates the need for tools like GetSampleName and avoids issues with parsing funky sample names at the command line, handling/passing special characters at all levels (WDL, Java, python), etc.

2) I would argue that specifying a sample index is relatively user friendly, especially if we are typically running on all samples. In that case, all you need to know is the total number of samples and that we use zero indexing, and then you simply iterate over all indices. (If you want to run on a single, particular sample, then perhaps using the sample name might be more friendly, but I'd argue that this use case is not typical.)

3) If you want to go ahead and add this option, I would probably keep the directory structure of the GermlineCNVCaller output the same (i.e., with folders named "SAMPLE_#"), and just check the sample_name.txt file contained within at the PostprocessGermlineCNVCalls step. I don't think this should require GermlineCNVCaller code changes, right?

4) We may require additional code at the WDL level if we want to switch over to primarily using sample names but also get rid of bundling (i.e., by passing only the calls for each sample when needed) on the cloud. Locally, you can always just search all output for directories containing the appropriate sample_name.txt. But on the cloud, you'd want to make sure that the postprocessing step for a particular sample gets only its corresponding directories, which would have to happen at the WDL level; the check against sample_name.txt at the tool level would just be a formality. I can foresee headaches with globbing and funky sample names.

I'm not sure I understand your point about extending PostprocessGermlineCNVCalls to run on all samples. The point of that tool is to take results from all genomic shards for a single sample and stitch them together, right? Even if we extend this to run on a batch of multiple samples (which would just be moving the loop over samples at the WDL level to some lower level, i.e., Java or python), we still need to see all shards for those samples. Perhaps I'm misunderstanding---can you clarify?

@mwalker174 can we once and for all clearly document the issue with the transpose? Perhaps by pointing to specific WGS runs that have issues with call caching? I think being able to pinpoint the exact issue will help us identify the right solution---whether that be choosing an appropriate bundling scheme, taking advantage of #5781 to reduce the number of shards, batching during the postprocessing step, removing unnecessary outputs, etc.

Recall that we'd like to be able to use the same WDL locally (when you have easy access to all GermlineCNVCaller results from all genomic shards) and in the cloud, with minimal duplication of output from bundling when running locally, if possible.

**Comment by ldgauthier** [comment]
I got through the debugging process with a long series of bash commands, so I guess that's good enough for now.
