### ISSUE TITLE
Use current billing project for requester pays buckets

### ISSUE THREAD

**Issue by joshua-gould** [broadinstitute/gatk#6669]
If --gcs-project-for-requester-pays is not specified, gatk should use the current billing project to access requester pays buckets.

**Comment by droazen** [comment]
@joshua-gould We deliberately require an explicit argument, as we want users to explicitly opt-in to requester pays before being charged. Sorry for the inconvenience!

**Comment by joshua-gould** [comment]
I think this makes gatk less user-friendly and is in contrast with
Cromwell's behavior, which does use the current billing project by default.

**Comment by mpetljak** [comment]
I agree with Joshua: there are several places where the billing project currently needs to be specified in the command line and such manual modifications are not very user-friendly. Another way to perhaps address this is to make sure that an input argument, which specifies the billing project, also addresses the issue throughout the script, so that the user does not need to make any additional changes

**Comment by droazen** [comment]
We feel that users potentially getting unexpected bills for requester-pays usage would be even more user-unfriendly than having to explicitly opt-in to such charges via a command line argument.

If you're running GATK via a WDL, it seems like the billing project could be a single unified input parameter in the accompanying JSON which then gets passed to all individual tasks, which doesn't seem too cumbersome.
