### ISSUE TITLE
Incorrect hyperlinks in tooldocs

### ISSUE THREAD

**Issue by bhanugandham** [broadinstitute/gatk#6699]
Incorrect hyperlinks from this tooldocs page: https://gatk.broadinstitute.org/hc/en-us/articles/360045680851--Tool-Documentation-Index

Examples:
[MappingQualityRankSumTest](https://gatk.broadinstitute.org/hc/en-us/articles/360045252192-MappingQuality)
[InbreedingCoeff](https://gatk.broadinstitute.org/hc/en-us/articles/360045682511-AS-InbreedingCoeff)
[GetPileupSummaries](https://gatk.broadinstitute.org/hc/en-us/articles/360045251732-Pileup)
[CountBasesSpark](https://gatk.broadinstitute.org/hc/en-us/articles/360045252052-CountBases)
[CountReadsSpark](https://gatk.broadinstitute.org/hc/en-us/articles/360045680631-CountReads)

I haven't checked all the links in the tooldocs page but I suspect there are more incorrect links in addition to the examples listed above.

**Comment by lbergelson** [comment]
is this a duplicate of #6505?  If someone from comms could open a PR to fix the ones you've identified that would be helpful?  We don't necessarily know how to find the correct links.

**Comment by bhanugandham** [comment]
I don't think this is the same issue @lbergelson. #6505 is about links that are broken because they still point to the old forum. This particular issue is happening because some tools in the tool docs are pointing to a different tool.
For example: CountBasesSpark is pointing to CountBases

**Comment by lbergelson** [comment]
Oh, weird... I didn't understand what you meant.

**Comment by cmnbroad** [comment]
It looks to me like this issue is introduced by the doc publishing/transformation process. The docs as generated locally by gradle appear to be correct (if you run gatkDoc locally, the index has the correct relative links):
```
<tr>
  | <td><a href="org_broadinstitute_hellbender_tools_CountBases.html">CountBases</a></td>
  | <td>Count bases in a SAM/BAM/CRAM file</td>
  | </tr>
  | <tr>
  | <td><a href="org_broadinstitute_hellbender_tools_spark_pipelines_CountBasesSpark.html">CountBasesSpark</a></td>
  | <td>Counts bases in the input SAM/BAM</td>
  | </tr>
```
The (incorrect) links embedded in the published index
(see view-source:https://gatk.broadinstitute.org/hc/en-us/articles/360045680851--Tool-Documentation-Index) are absolute, and appear to have been transformed from the generated ones:

```
<tr>
  | <td><a href="https://gatk.broadinstitute.org/hc/en-us/articles/360045252052-CountBases", id = "CountBases">CountBases</a></td>
  | <td>Count bases in a SAM/BAM/CRAM file</td>
  | </tr>
  | <tr>
  | <td><a href="https://gatk.broadinstitute.org/hc/en-us/articles/360045252052-CountBases", id = "CountBases">CountBasesSpark</a></td>
  | <td>Counts bases in the input SAM/BAM</td>
  | </tr>
```
 
The ones that are incorrect appear to be links that have a prefix that matches some other links (i.e., CountBases is a prefix of CountBasesSpark), so something seems to be going wrong with the transformations. I'm not sure who maintains that.

**Comment by cmnbroad** [comment]
@bhanugandham back to you - not sure who should handle this but it doesn't look to be gatk/build related.

**Comment by bhanugandham** [comment]
Thanks for looking into this @cmnbroad I see what you are saying. I will look into this.

**Comment by bhanugandham** [comment]
We resolved this issue. Thank you for helping us find the bug @cmnbroad . Closing out this issue.
