### ISSUE TITLE
DepthofCoverage not producing _gene_statistics output

### ISSUE THREAD

**Issue by GATKSupportTeam** [broadinstitute/gatk#6714]
We discussed this issue at the GATK office hours. First, the user ran with multiple bams and found this issue. They also ran with just one BAM input and the problem still existed. 

This request was created from a contribution made by marta r on July 01, 2020 09:23 UTC.

Link: [https://gatk.broadinstitute.org/hc/en-us/community/posts/360067324992-DepthofCoverage-GATK4-1-7-0-gene-list#community\_comment\_360011204472](https://gatk.broadinstitute.org/hc/en-us/community/posts/360067324992-DepthofCoverage-GATK4-1-7-0-gene-list#community_comment_360011204472)

\--

368513854251 thank you very much for the help. Now it works, but I have still another question about the output

This was my command:

gatk DepthOfCoverage -R /path/ucsc.hg19.fasta -O coverage\_name -I /input1.bam -I /input2.bam -I /input3.bam -gene-list /path/genome.refseq --summary-coverage-threshold 5 --summary-coverage-threshold 15 --summary-coverage-threshold 30 -L /path/mybed.bed

an these the outputs:

coverage\_name

coverage\_name.sample\_cumulative\_coverage\_counts

coverage\_name.sample\_cumulative\_coverage\_proportions

coverage\_name.sample\_gene\_summary

coverage\_name.sample\_interval\_statistics

coverage\_name.sample\_interval\_summary

coverage\_name.sample\_statistics

coverage\_name.sample\_summary

As you can see, I did't obtain the "\_gene\_statistics" output. Do you know why? Is there any option to add?

Thank you<br><br><i>(created from <a href='https://broadinstitute.zendesk.com/agent/tickets/6146'>Zendesk ticket #6146</a>)<br>gz#6146</i><br><br><i>(related to <a href='https://broadinstitute.zendesk.com/agent/tickets/79476'>Zendesk ticket #79476</a>)<br>gz#79476</i>

**Comment by jamesemery** [comment]
hey @gbrandt6 can you confirm whether upgrading to GATK 4.1.8.0 fixed the users issues? We recently fixed an error where some of the DepthOfCoverage files were blank in 4.1.8.0 and I noticed that the user is on 4.1.7.0. Its possible that there are more issues lurking but I want to confirm that it wasn't fixed by #6609.

**Comment by gbrandt6** [comment]
@jamesemery I haven't heard, so I'll check back in with the user.

**Comment by jaspez** [comment]
Dear all,

I’m trying to use the DepthOfCoverage tool with GATK 4.1.9.0. I used the "-gene-list" option but I have a problem obtaining the "_gene_statistics" output. I found this issue and [marta r issue](https://gatk.broadinstitute.org/hc/en-us/community/posts/360067324992-DepthofCoverage-GATK4-1-7-0-gene-list). I thought this problem was solved after GATK 4.1.8.0.

I hope you can help me, thanks in advance.

**Comment by gbrandt6** [comment]
Hi @jaspez, could you post on the [GATK forum](https://gatk.broadinstitute.org/hc/en-us/community/topics) with more details so we can look into this? The other user was able to solve the problem with GATK 4.1.8.0.

**Comment by jaspez** [comment]
Hi @gbrandt6, this is the [post ](https://gatk.broadinstitute.org/hc/en-us/community/posts/360075744271-DepthOfCoverage-in-GATK4-1-9-0-with-gene-list-option) on the GATK forum.

Thanks!
