### ISSUE TITLE
Clarify conda supported platforms in the README

### ISSUE THREAD

**Issue by droazen** [broadinstitute/gatk#6786]
If we don't officially support our conda environment on certain platforms (like OS X), we should mention this in the README.

**Comment by joshwilding4444** [comment]
I would be happy to add that documentation. Which conda environments are supported?

**Comment by lbergelson** [comment]
It seems like only linux works at the moment.  We support osx and linux x64 for most things but it turns out that our conda environments don't currently build on osx.

**Comment by cmnbroad** [comment]
@samuelklee The conda env used to work on MacOS - do we know why it broke, or where the limitation is ?

**Comment by samuelklee** [comment]
@cmnbroad I called for volunteers on Slack to test out the new environment in #5026 on a Mac (since I don’t use one), but didn’t get any takers. I’m not sure if it’s a particular package causing the conflict, but I won’t be able to test on my end.

In general, I don’t think conda can guarantee cross-platform environments. So we may have to do some further tweaking to the YML or have a separate (and hopefully equivalent) one for Macs.
