### ISSUE TITLE
MappingQualityReadFilter minimum mapping quality is a no-op

### ISSUE THREAD

**Issue by RWilton** [broadinstitute/gatk#6854]
### Affected tool(s) or class(es)
HaplotypeCaller / GenotypeGVCFs

### Affected version(s)
4.1.8.1

### Description 
Identical variant calls are generated with and without a minimum MAPQ parameter for the ```MappingQualityReadFilter``` filter.

#### Steps to reproduce
```
gatk HaplotypeCaller \
 --read-filter MappingQualityReadFilter \
 --minimum-mapping-quality 4
```

#### Expected behavior
Reads with MAPQ less than the specified value should be filtered out.

#### Actual behavior
Reads with MAPQ less than some constant value (20?) are filtered out.

#### Comments
Perhaps HaplotypeCaller is using a hard-coded literal value, ```READ_QUALITY_FILTER_THRESHOLD```, instead of (or subsequent to) filtering with the user-specified parameter value.  See line 729 in https://github.com/broadinstitute/gatk/blob/master/src/main/java/org/broadinstitute/hellbender/tools/walkers/haplotypecaller/HaplotypeCallerEngine.java.

**Comment by droazen** [comment]
@RWilton The `HaplotypeCaller` performs two separate filtering passes on the read mapping qualities:

The first is in the `MappingQualityReadFilter`, and occurs before the `HaplotypeCaller` even sees the reads. This filtering pass can be controlled via the `--minimum-mapping-quality` argument you're using (and I can confirm that this argument is hooked up and does work as intended).

The second pass is in `HaplotypeCallerEngine.filterNonPassingReads()`. This happens later (just before genotyping), and is hardcoded to filter out reads with mapping quality < 20. There is no way to control the mapping quality threshold in this second pass, as allowing reads with low mapping qualities into the genotyper would result in large numbers of false positive variant calls.

You can confirm that the `--minimum-mapping-quality` argument for `MappingQualityReadFilter` works as intended by setting it to a value higher than 20, and inspecting the differences in the output.

**Comment by jamesemery** [comment]
@RWilton We are adding into a future version of haplotype caller an argument that will allow you to independently change the genotyper level mapping quality filter as well as the active region mapping quality filter (the one you have already found). This should allow you to look at lower quality reads but it should be noted that it is unlikely the Haplotype Caller will produce good results at sites with many low mapping quality reads since it has not been designed to account for and properly penalize such reads.

**Comment by RWilton** [comment]
@droazen Thank you for the confirmation that HaplotypeCaller performs separate filtering passes on the read mapping qualities, and that the code on line 729 of HaplotypeCallerEngine.java (method ```filterNonPassingReads()``` ) is indeed executing subsequent to the ```MappingQualityReadFilter```.

May I suggest, however, that MAPQ values less than 20 might not necessarily lead to an increase in FP variant calls?  My understanding is that HaplotypeCaller uses MAPQ values only in a nonparametric rank sum test, in which case MAPQ is treated as an ordinal.  This seems appropriate since the magnitude of a MAPQ value depends both on the data and on the computational model the read aligner uses to calculate it.

With this in mind, a set of mappings with MAPQ in a lower range (```--minimum-mapping-quality 10``` and a correspondingly lower ```--maximum-mapping-quality``` as well) might very well be appropriate for variant calling.  So changing the semantics of ```MappingQualityReadFilter``` or parameterizing the currently-hardwired MAPQ range would enable additional control without affecting performance.

@jamesemery I will watch for the HaplotypeCaller update that implements that functionality.  And if you have a moment, could you please point me to the code that might be adversely affected by decreasing the low-end MAPQ threshold?  I might have some ideas about that (or not!)...

Thanks again!

**Comment by jamesemery** [comment]
@RWilton There is not particular code I can point to that specifically should fall over. We filter out low MQ reads in large part because they are very likely to cause false positives corresponding to sequence from other regions on the genome and the current behavior for adjusting genotyper confidences based on mapping quality (which is accomplished by lowering the Base Qualities based on the MQ prior to the HMM step) doesn't work well enough especially at sites where there are many low MQ reads piled-up. It should be noted that based on how many sequencers work low MQ reads appear piled up in the thousands at a some commonly repeated sites in the genome and can easily drown out all of the other evidence unless you are careful. Keep an eye out for #6634 as it will include the argument you are asking about as well as providing an explicit model in the genotyper for mapping quality as a source of errors which will likely better handle high coverage + low MQ sites explicitly.
