### ISSUE TITLE
GenomicsDBImport disk quota exceeded error

### ISSUE THREAD

**Issue by djb17** [broadinstitute/gatk#6950]
----

### Affected tool(s) or class(es)
GenomicsDBImport

### Affected version(s)
- [X] Latest public release version [4.1.9.0]
- [ ] Latest master branch as of [date of test?]

### Description 
[TileDB::FileSystem] Error: (write_to_file) Cannot write to file; File opening error; path=/storage/home/data/gendb/chr13/.__7a3cf8dc-ea9d-4bf9-9e33-c87b91d94b0546913384130304_1605025432087/RAW_MQandDP.tdb; errno=122(Disk quota exceede
d)
[TileDB::WriteState] Error: Cannot write segment to file.
[TileDB::FileSystem] Error: (write_to_file) Cannot write to file; File opening error; path=/storage/home/data/gendb/chr13/chr13$32310639$32310731/.__7a3cf8dc-ea9d-4bf9-9e33-c87b91d94b0546913384130304_1605025432087/__book_keeping.tdb.gz; errno=122(Disk quota e
xceeded)
[TileDB::utils] Error: (write_to_file_after_compression) Could not write compressed bytes to internal buffer; path=/storage/home/data/gendb/chr13/chr13$32310639$32310731/.__7a3cf8dc-ea9d-4bf9-9e33-c87b91d94b0546913384130304_1605025432087/__book_keeping.tdb.gz
; errno=122(Disk quota exceeded)
[TileDB::BookKeeping] Error: Cannot finalize book-keeping; Failure to write to file /storage/home/data/gendb/chr13/chr13$32310639$32310731/.__7a3cf8dc-ea9d-4bf9-9e33-c87b91d94b0546913384130304_1605025432087/__book_keeping.tdb.gz.
[TileDB::FileSystem] Error: (create_file) Failed to create file; path=/storage/home/data/gendb/chr13/chr13$32310639$32310731/__7a3cf8dc-ea9d-4bf9-9e33-c87b91d94b0546913384130304_1605025432087/__tiledb_fragment.tdb; errno=122(Disk quota exceeded)
[TileDB::utils] Error: (create_fragment_file) Failed to create fragment file; path=/storage/home/data/gendb/chr13/chr13$32310639$32310731/__7a3cf8dc-ea9d-4bf9-9e33-c87b91d94b0546913384130304_1605025432087; errno=122(Disk quota exceeded)
11:23:52.390 erro  NativeGenomicsDB - pid=57964 tid=57984 VariantStorageManagerException exception : Error while finalizing TileDB array chr13$32310639$32310731
TileDB error message : [TileDB::WriteState] Error: Cannot write segment to file
[TileDB::FileSystem] Error: (write_to_file) Cannot write to file; File opening error; path=/storage/home/data/gendb/chr13/chr13$32310639$32310731/.__7a3cf8dc-ea9d-4bf9-9e33-c87b91d94b0546913384130304_1605025432087/RAW_MQandDP.tdb; errno=122(Disk quota exceede
d)
#### Steps to reproduce
Below code ran on a cluster
```
gatk --java-options "-Xmx100g -Xms100g" GenomicsDBImport \
   -V sample1.g.vcf.gz -V sample2.g.vcf.gz -V sample3.g.vcf.gz -V sample4.g.vcf.gz \
   -L chr13.bed \
   --genomicsdb-workspace-path /storage/home/data/gendb/chr13\
   --tmp-dir /storage/home/scratch/tmp
```

#### Expected behavior
Over 1TB of scratch space available for temporary directory and around 500GB of storage space available to hold outputs of GenomicsDBImport outputs.

#### Actual behavior
Above error message indicating that disk quota has exceeded. I'm not exactly sure what's going on here as I am directing the outputs of the GenomicsDBImport runs to directories with more than enough storage space and yet it seems to fail. Any help will be greatly appreciated. Thanks!

**Comment by mlathara** [comment]
Are you sure that there is enough space? Could you run something like:

```
df -h /storage/home/data/gendb/
```
And check that available space is in line with your expectations? Also, is there any user specific quota being enforced on your system?

Not completely sure, but another possibility is that you have too many (fairly small) intervals in your `chr13.bed` file. Unless you are specifically trying to exclude intervals not in the bed file, you should get a lot better performance/efficiency by specifying fewer intervals (think <100 intervals, and in your case since you are doing a single chromosome, maybe much less than that). 

If you don't want to manually specify fewer intervals, you could try setting `--merge-input-intervals` to `true` which will return one interval for the contig spanning all the intervals you've specified.

Having many smaller intervals results in many small files created which will definitely be bad for performance, and may also cause quota issues.

**Comment by djb17** [comment]
I double checked the scratch space so I'm not sure if that was the issue unless the server is incorrectly displaying the storage information.

My `.bed` file had around 4,400 so I'm not sure if that would count as many, but I do observe a large number of files that are generated in the path I specify with `--genomicsdb-workspace-path` before `GenomicsDBImport` crashes.

What I was intending to do was to keep the regions to those that are specified in exome capture kit target intervals. Interestingly, running `GenomicsDBImport` with `--merge-input-intervals` changed the overall runtime from >60 minutes to <60 seconds.

**Comment by mlathara** [comment]
@droazen I think this can be closed since @djb17 indicated that he was able to import without error after merging intervals.

@djb17 if you absolutely need your analysis to reflect only the intervals your specify in your bed file, then you can either pre-process the gvcf files (VariantFiltration or bcftools or the like) to only leave those intervals in there or maybe specify the intervals argument to whatever tool will be reading from the genomicsdb workspace (for instance, `GenotypeGVCFs` has a `-L` argument)

**Comment by droazen** [comment]
Closing as resolved

**Comment by arumds** [comment]
I am having the same issue. I have the whole chromsome13 `-L chr13` instead of intervals. How do i overcome the issue in this case?
