### ISSUE TITLE
Expose HaplotypeCaller `READ_QUALITY_FILTER_THRESHOLD` on the command line

### ISSUE THREAD

**Issue by nh13** [broadinstitute/gatk#7034]
Would it be possible to expose the [`READ_QUALITY_FILTER_THRESHOLD`](https://github.com/broadinstitute/gatk/blob/9d5727df8db3a475b1ba5f9bff6bc92a322f5633/src/main/java/org/broadinstitute/hellbender/tools/walkers/haplotypecaller/HaplotypeCallerEngine.java#L729) on the command line for 4.9.0.1?  I know on the latest branch we have [`--mapping-quality-threshold`](https://github.com/broadinstitute/gatk/blob/7e3d8a1e0c56206345128e3a6125ecc30427deda/src/main/java/org/broadinstitute/hellbender/tools/walkers/haplotypecaller/HaplotypeCallerArgumentCollection.java#L153).  For data and regions where we get low mapping qualities (eg. PacBio), a hard-filter on mapq 20 is onerous.  I'd also echo the comment in the latter TODO that the interplay between `----mapping-quality-threshold` (new) and ` --minimum-mapping-quality` (old) is confusing upon first inspection.

**Comment by jamesemery** [comment]
@nh13 Thank you for your question. I agree that it is particularly onerous to lower the mapping quality currently since there are two seperate arguments `--mapping-quality-threshold` and '--minimum-mapping-quality' that are separate. In order to lower the threshold they must BOTH be set otherwise nothing will change and low MQ reads will not be handled. This is necessary due to the order in which Barclay parses fields and the way this interacts with the read filte. We either need flags to be able to fill multiple fields in different places or to use reflection to extract the mapping quality threshold to be used for the assembly engine based on the read filters used after the fact which runs into issues if the user has disabled the mapping quality filter. These both still fail to capture the case where you want to explicitly use a different threshold for active region detection and for calling. 

Would it be helpful if the new argument were renamed to something like `--mapping-quality-threshold-for-genotyping`?

**Comment by jamesemery** [comment]
It should also be noted that the current behavior of the HaplotypeCaller on low base quality reads could be better. Specifically in the PairHMM there is code that explicitly caps the base qualities for every base in every read to be at most the reads Mapping Quality. Empirically this doesn't seem to sufficiently penalize low MQ reads in the HMM scores which is part of the reason for the hard cuttoff. In the upcoming DRAGEN-GATK release code we disable this particular behavior and instead apply a secondary genotyping algorithm in the genotyper that attempts to partition the evidence by mapping quality and adjust the score if there is a significant difference in MQ between reads supporting the various alleles. No doubt there could be other approaches for capping MQ (possibly a reads HMM likelihoods contribution can be capped based on its MQ as well which is also a part of the DRAGEN-GATK).

**Comment by nh13** [comment]
@jamesemery totally get the technical limitation for command line parsing. I think the renaming you suggests helps, and in the documentation for both command line options they should mention each other, and describe where in the calling process they're applied (eg. prior to generating candidate haplotypes, and after haplotype generation but before final genotyping).  I think it's valid to have to options each controlling the different steps.
