### ISSUE TITLE
HC uses filtered (bad) reads in genotype (FORMAT) annotation even when these are not use to compute PL, GT, QUAL.

### ISSUE THREAD

**Issue by vruano** [broadinstitute/gatk#7144]
HaplotypeCaller discard reads in active regions that do not pass a small set QC criteria. These reads are then not used for assembly nor to calculate the likelihoods that we use for GT and QUAL  and other call quality annotations. However these reads are incorporated back into the data that is passed down to vcf record annotators. 

This might be ok under some circumstances but arguably most user would like to see consistency between 
PL and AD or DP,. 

Moreover there is an argument that seem that should be included in order to add those filtered reads:
```---use-filtered-reads-for-annotations```
However its doc line indicates that it means those reads excluded to correct for contamination.

The question here is whether should we revise this behavior and make it default to NOT include them instead.

**Comment by droazen** [comment]
@jamesemery Thoughts on this?

**Comment by jamesemery** [comment]
Just checked and this is not new behavior. I was afraid this would be an unintended consequence of the DRAGEN branch but that doesn't seem to be the case. Looking a little closer into the code I actually think the only difference this makes is explicitly for the contamination and nothing else. There are a few layers where we filter reads before the annotations are called (filtered by QC before active region determination, MQ/etc-filtered/un-softclipped/overlap-score-adjusted before assembly, filtered based on poor concordance with existing haplotypes, reads are realigned and re-filtered by position, and again filtered due to contamination downsampling). It seems to me that the two likelihoods arrays fed to the `prepareReadAlleleLikelihoodsForAnnotation()` have had all of the above steps applied to them EXCEPT for the contamination downsampling step applied to them looking thorough the code in the HaplotypeCaller. I guess the question is whether there is a strong reason to make the annotations with/without the contamination adjustment... I think the argument `--use-filtered-reads-for-annotations` is misleadingly labeled though the description looks correct to me since it really does only seem to make a difference for the contamination step. 

There is another wrinkle to all of this. For DRAGEN-GATK we evaluated calculating the overlaps/annotations exactly how they do it in DRAGEN and decided against it. In DRAGEN they retain the original reads from the bam (i.e. no realignment/no score adjustments/etc...) and use THOSE for annotation and for genotyping. I would have to pick through their debug output to tell just which subsets get used for genotyping (for example they still use non-haplotype-matching reads for FRD and BQD but I don't remember if those are also used for calculating annotations).

**Comment by vruano** [comment]
Actually there is a bug associated with this reported iin https://github.com/broadinstitute/gatk/issues/7153. Once fixed the AD, DP should not be affected by those "bad" reads.

**Comment by droazen** [comment]
Duplicate of https://github.com/broadinstitute/gatk/issues/7153

**Comment by vruano** [comment]
Is not a duplicate IMO. Regardless of the bug, make sense to pass down those filtered reads to annotators?

**Comment by ldgauthier** [comment]
@vruano given that you merged a fix for the duplicate issue, can this be closed?

**Comment by vruano** [comment]
Make sense.
