### ISSUE TITLE
DepthOfCoverage --intervals example required

### ISSUE THREAD

**Issue by humblescientist** [broadinstitute/gatk#7155]
### Tool(s) or class(es) involved
DepthOfCoverage --intervals parameter

### Description
Please supply an example of how intervals should be used. I just want to run DepthOfCoverage over the entire reference sequence (imho this should be the default and make --include optional), but cant work out how to do this.

I tried

DepthOfCoverage other_parameters --intervals 1-30000
DepthOfCoverage other_parameters --intervals 1:30000

Both gave errors.

**Comment by jamesemery** [comment]
Normally for most tools in order to traverse the entire reference you simply would not specify anything for --intervals (or -L which is equivalent) but currently DepthOfCoverage requires intervals be specified. The reason for this is that for several of the outputs of DepthOfCoverage we output rows where each row is one of the user supplied intervals which don't exist in the case where no intervals are supplied. This behavior could probably be changed to simply treat each chromosome separately as an "interval" though given the complexities of regions that are dropped/in gaps it might warrant a warning. 

@humblescientist If you would like to traverse over your entire reference in DepthOfCoverage the best way would be to provide an interval list file with -L/--intervals that covers the entire genome. If you would like more information on interval list files that GATK accepts you can find more information here https://gatk.broadinstitute.org/hc/en-us/articles/360035531852-Intervals-and-interval-lists. I would recommend directing further questions about this to the forums since this tracker is intended for bug reports and feature requests in GATK.
