### ISSUE TITLE
gatk 4 SplitNCigarReads is not splitting reads.

### ISSUE THREAD

**Issue by gokalpcelik** [broadinstitute/gatk#7323]
Hi. 

I opened a topic on GATK forums similarly however the issue is pretty big I guess. SplitNCigarReads functionality is probably lost during progress. 3.8-1 splits all N cigars properly however 4.1.9.0 and 4.2.0.0 cannot produce the same output. 4.x output looks as if reads are not split but just softclipped after N cigar directionally from left to right. 

![image](https://user-images.githubusercontent.com/37572619/122541195-096cce80-d032-11eb-8fea-2a90cb987a16.png)

Top : Unsplit
2nd from top gatk 3.8-1
3rd and 4th gatk 4.1.9.0 4.2.0.0

Gatk commands were used from wdls published at github pages by broad. 

Can you look into this matter?

Thanks.

**Comment by jamesemery** [comment]
Hey @gokalpcelik thanks for writing in. So there are a few important differences that could be confounding the results you see for SplitNCigarReads between GATK3 and GATK4. The big one is that in GATK 4 the reads get soft clipped instead of hard clipped and the subsequent splits for the reads are marked as Supplementary reads (which does not seem to have been the case in GATK3). Can you check that you aren't filtering non-primary alignments from your output/IGV sessions? Many downstream tools that might operate on split reads must be careful to handle these differences correctly which can easily cause confusion when comparing gatk3.8 results to gatk4+ results. A simple way to confirm is to slect one of those softclipped reads in IGV and to search the output BAM for GATK4 for reads sharing the same name. You should see the matched mates. If it really does appear that the right overhangs are getting dropped as appears from your screenshots then it would be helpful if you could clarify what arguments you ran for both versions of the tool as well as sharing with us an example file where this is happening.

**Comment by gokalpcelik** [comment]
Thanks @jamesemery 

The issue seems to be solved on my end. Sorry but this was my misunderstanding of the improvements made to the tool itself. 

https://gatk.broadinstitute.org/hc/en-us/community/posts/1260803956870-SplitNCigarReads-does-not-seem-to-split-reads-properly-as-it-was-before-3-8-1-?page=1#community_comment_4402553149467

BTW the bam file created after splitting by 4.2.0.0 is still not validated thoroughly by ValidateSamFile. Split Bam file needs its new NM MD and UQ tags regenerated by picard. 

So I am closing the issue.
