### ISSUE TITLE
Ref_depth didnot match

### ISSUE THREAD

**Issue by MMengrui** [broadinstitute/gatk#7367]
### Description 

hi 
I met the problem:
This is the bam file:
![image](https://user-images.githubusercontent.com/49903097/126967843-659767f9-5234-4d54-8a11-05631c1eb408.png)

but the vcf showed:
![image](https://user-images.githubusercontent.com/49903097/126967949-dc737504-2787-448f-b648-5ef19769f158.png)

The reference depth didnot match to the bam file. 

I want to know why this happens

**Comment by jamesemery** [comment]
Hello @MMengrui. I see that it appears the depth might not be reflective of the depth in the bam before running HaplotypeCaller (I can only assume based on the annotations that is the tool you ran). There are a lot of details that go into the AD annotation for depth that can change the annotation and lead to confusing results. Before computing the AD annotation for example we realign reads to their best haplotype, so the reads from the bam aren't necessarily in exactly the same place, we also exclude reads that were filtered/did not adequately match any haplotype well enough (this can also cause weirdness if assembly partially failed at that site since reads may have been assigned to Ref supporting haplotypes). I would recommend producing the bamout with the `--bamout` command so you can see the reads as they were used for genotyping and also what haplotypes were called at that site. Since this isn't a bug or a feature request per-se I would recommend directing future questions like this to our forums: https://gatk.broadinstitute.org/hc/en-us/community/topics where there already might be an answer to your question.
