### ISSUE TITLE
GetPileupSummaries Extraordinary Resource Usage and Lack of ProgressMeter Messages

### ISSUE THREAD

**Issue by DarioS** [broadinstitute/gatk#7606]
I am trying version 4.2.3.0. I set `--java-options "-Xmx128g"` and it gradually increased to consume all of the RAM.

```
    PID USER      PR  NI    VIRT    RES    SHR S  %CPU  %MEM     TIME+ COMMAND
3286969 dario     20   0  136.7g 133.2g  27012 S  1478  26.4 725:33.44 java
```

The input is a modest whole genome sequencing BAM file.

```
$ ls -lh CSCC_0163-B1.final*
-r-------- 1 dario stgrad 9.2M Dec 15 10:22 CSCC_0163-B1.final.bai
-r-------- 1 dario stgrad  86G Dec 15 10:21 CSCC_0163-B1.final.bam
```

After about one hour without any progress messages, the process shuts down due to running out of heap space.

```
12:03:07.666 INFO  ProgressMeter - Starting traversal
12:03:07.666 INFO  ProgressMeter -        Current Locus  Elapsed Minutes        Loci Processed      Loci/Minute
13:08:22.336 INFO  GetPileupSummaries - Shutting down engine
[December 15, 2021 at 1:08:22 PM AEDT] org.broadinstitute.hellbender.tools.walkers.contamination.GetPileupSummaries done. Elapsed time: 84.45 minutes.
Runtime.totalMemory()=30333206528
Exception in thread "main" java.lang.OutOfMemoryError: Java heap space
```

The two other key parameters were `-L af-only-gnomad.hg38.vcf.gz -V af-only-gnomad.hg38.vcf.gz`. I think this module is far too inefficient to be in production, if this is how it typically works.

**Comment by lbergelson** [comment]
@DarioS Thanks for reporting this.  It seems like there is an object in the tool which accumulates a record for every variant in the -V input.  Since you're using gnomad it's very large.  This is a design issue and seems like it should be fixed to stream the output instead of accumulating it all in memory and then dumping it at the end.

@davidbenjamin I aimed this at you since it seems like it's your tool.  From a lazy glance it seems like it should be doable to rewrite it to stream output instead of keeping it all in memory.

**Comment by davidbenjamin** [comment]
@lbergelson That looks easily fixable.

@DarioS You're right that this is needlessly inefficient.  However, our best practices recommend using gs://gatk-best-practices/somatic-b37/small_exac_common_3.vcf, a much smaller resource file containing only common variants.

**Comment by DarioS** [comment]
Ah, so `small_exac_common_3.vcf` is recommended even for whole genome sequencing data? Neither the core facility which implemented the pipeline nor I picked up on that previously.
