### ISSUE TITLE
Still having the same issues with version 4.2.5.0

### ISSUE THREAD

**Issue by Riad900** [broadinstitute/gatk#7729]
This is probably complicated by a bug in the htsjdk warning from previous versions, which should be fixed in the latest master now.  There's probably still a bug, but the error will be more informative now.

There may be a ploidy-related bug since the somatic genotypes are a little funky that way.  I don't like the fact that this is calling a biallelic method.

@fleharty if you still care about this, can you run it again with the latest master?

_Originally posted by @ldgauthier in https://github.com/broadinstitute/gatk/issues/6689#issuecomment-898580381_

**Comment by fleharty** [comment]
@Riad900 
Sorry I don't remember what triggered this to happen, and I've since deleted the tmp directory that contained the example that demonstrated this bug. :(

**Comment by droazen** [comment]
@ldgauthier Do you have any insight into this one? Do any of your recent changes to the `AlleleSubsettingUtils` have a bearing on this issue?

**Comment by ldgauthier** [comment]
I don't think so, but I'm still not sure what the issue is.  @Riad900 the warning should be more informative in the latest version -- is that the case?  Can you post the new warning?  I hope it outputs an allele that actually isn't in the set it reports.  And maybe I added a locus, but I'm not sure.  It's really hard to debug without a locus.

**Comment by droazen** [comment]
@ldgauthier Should this one be closed now that GATK 4.2.6 is out?
