### ISSUE TITLE
Add warning to SelectVariants about poor performance if the samples are not sorted in the VCF header

### ISSUE THREAD

**Issue by droazen** [broadinstitute/gatk#7732]
Apparently `SelectVariants` is ~10x slower when the samples in the VCF header are not sorted, due to the need to reorder the genotypes on output. We should at least warn the user when unsorted sample names are detected in the input.

(discovered by @epiercehoffman)

**Comment by epiercehoffman** [comment]
Thanks for opening this issue. I hope that this performance issue can be fixed in HTSJDK soon, but I agree a warning would be useful in the intervening time. 

To clarify, I believe this applies to any tool that loads a VCF but does not need to parse genotypes - not just SelectVariants. For instance, I saw a 5-10x slowdown in SVAnnotate with unsorted sample IDs.

**Comment by mwalker174** [comment]
A warning message would be helpful, although I doubt most Terra users read their logs unless there's an error. What are the chances this can get addressed in htsjdk?
