### ISSUE TITLE
Java version question for running GATK

### ISSUE THREAD

**Issue by tamuanand** [broadinstitute/gatk#7842]
Hi

I had a question on Java version to use for GATK/PIcard. 

https://gatk.broadinstitute.org/hc/en-us/articles/360035889531-What-are-the-requirements-for-running-GATK- 
states that `the Java runtime version should be at 1.8 exactly`

As you might be aware, Java 1.8 has reached its end of life - https://endoflife.date/java 

Given this , I tried running MarkDuplicates and some other tools using Amazon Corretto 17 and they seem to work fine. More importantly, I did not encounter the `Unsupported major.minor version` error as mentioned here: https://gatk.broadinstitute.org/hc/en-us/articles/360035532332

Also happened to see this - https://github.com/broadinstitute/gatk/issues/7436

Question: Am I OK using Amazon Corretto for GATK/Picard or do I need to absolutely stick on to Java 1.8 for GATK/Picard

```
java -version
openjdk version "17.0.2" 2022-01-18 LTS
OpenJDK Runtime Environment Corretto-17.0.2.8.1 (build 17.0.2+8-LTS)
OpenJDK 64-Bit Server VM Corretto-17.0.2.8.1 (build 17.0.2+8-LTS, mixed mode, sharing)
```

**Comment by lbergelson** [comment]
We test against 8 and 11 so I would expect either of those to work with out any weird issues.  

I can't guarantee that 17 is without problems, but I think if you're running it and the output looks reasonable than there's nothing I know of that would cause subtle errors.  You'll definitely have issues with things like building the documentation, but I suspect that if something runs without crashing it's probably ok.  It's not officially supported right now though, so it's a bit of use at your own risk.

**Comment by tamuanand** [comment]
Thanks @lbergelson  for your answer and explanation

**_Suggestion:_** It might be worthwhile to update the necessary pages with above info (about Java 8 and Java 11) so that it will help all.  I would suggest updating these pages

- _**Requirements section**_: https://github.com/broadinstitute/gatk#requirements
- https://gatk.broadinstitute.org/hc/en-us/articles/360035532332
- **_QuickStart section and Requirements section_**: https://gatk.broadinstitute.org/hc/en-us/articles/360036194592
- **_Section on Software/Java 8_**: https://gatk.broadinstitute.org/hc/en-us/articles/360035889531-What-are-the-requirements-for-running-GATK-

**Comment by tamuanand** [comment]
@lbergelson - Based on your answer, can I assume that GATK tools are supported on both Java 11 and Java 8
>We test against 8 and 11 so I would expect either of those to work with out any weird issues.

**Comment by lbergelson** [comment]
@tamuanand  I agree. It would be good to update those. Thanks for finding the various spots. It's slightly more complicated because we've hit a few issues with using gatk built on java 8 in a java 11 machine.  You sort of need to rebuild it using java 11 and a different scala if you want it to work flawlessly on 11.  

We haven't pushed on it because I keep planning to move us off of 8 entirely to a new version of java but it always gets delayed behind other priorities.

**Comment by tamuanand** [comment]
Thanks a lot @lbergelson 

Quick question: What would be a reasonable guesstimate timeline from your end (and GATK developers) to move off completely from Java 8.

**Comment by lbergelson** [comment]
Every time someone has asked that for the last 2 years I've said 3 months.  So... it's not exactly a helpful answer.  Sorry!  I know it's super annoying to have to use ancient versions, and I would really like to be able to use the new java features in 17.  I don't know when we will be able to prioritize it though.

**Comment by tamuanand** [comment]
If I can suggest something here: 

- instead of trying to move GATK from Java  8 to Java 11, probably better of to move to Java 17 or Java 18
- On Java 17/18,  choose Amazon corretto - https://aws.amazon.com/corretto/ 
- Why Corretto - Corretto is a distribution of Open JDK with patches included by Amazon **_that are not yet integrated in the corresponding OpenJDK update projects_**. 
- Quarterly updates/patches

**_Disclaimer_**: I am **_not_** from Amazon/AWS

**Comment by lbergelson** [comment]
Yes, I would like to move to 17 since it's the newest long term support release.  There are some changes between 8 and 17 though which will require additional work, particularly rewriting our documentation system.  I'm worried there are issue around restricted reflection which will be problematic or require rewriting to use SPI instead of direct reflection.  If it's working for you though thats' a good sign.  

I haven' really looked into the jvm variants much.  I think our goal would be to be compatible with all 17 jdks, but if Corretto is faster than other jdk variants it's very possible we could use it.  (Assuming it has a sane license).

**Comment by tamuanand** [comment]
> Assuming it has a sane license

https://aws.amazon.com/corretto/faqs/#Licensing_and_Open_Source
- Corretto is released under the same open source license as OpenJDK, which is licensed under the GNU Public License version 2 with the Class Path Exception ([GPLv2 with CPE](https://openjdk.java.net/legal/gplv2+ce.html)). You can use Corretto as you would use OpenJDK.
