### ISSUE TITLE
Incorrect AD values for Low VAF Samples

### ISSUE THREAD

**Issue by DarioS** [broadinstitute/gatk#7847]
I have three cell lines which all have the same deletion. I followed the HaplotypeCaller-CombineVCFs-GenotypeVCFs process. However, the final AD is incorrect for the two with low VAF. You can see below that one cell line has heaps of reads supporting the variant, but Fibro has two reads and Clone 4 only one read. However, the AD values are 43,0 and 32,0. The second value shouldn't be 0.

![image](https://user-images.githubusercontent.com/631218/167835368-8698de57-8b24-4bc7-99a3-7276e9fa19b7.png)

One of these tools should recalculate the AD values when combining the samples into a single VCF file. Perhaps the GT values should also change from 0/0 to 0/1 after confidence is gained in the variant call from the high VAF sample (AD is 25,28).

The Genome Analysis Toolkit (GATK) v4.2.5.0, HTSJDK Version: 2.24.1, Picard Version: 2.25.4

**Comment by droazen** [comment]
@DarioS There were a couple of known issues with `GenotypeGVCFs` in 4.2.5 -- could you try running with the latest release (4.2.6.1) and see if you get the same result?

@ldgauthier Any further insight into this one?

**Comment by DarioS** [comment]
I am also wondering what @ldgauthier thinks.

**Comment by ldgauthier** [comment]
@DarioS GATK doesn't have a tool that will add more variant alleles to a sample's genotype.  Low AC alleles can get dropped at multi-allelic sites resulting in the called GT having a different ALT or changing a low AC ALT to REF, but if any given sample is called homozygous reference on the basis of its own reads, it will always be homozygous reference.  For good (Q30) base qualities, under a diploid model in a non-repetitive reference context, a sample needs more than 10% ALT reads to be called het. In the event that a heterozygous sample with QD < 60 is called, then that site won't pass the default QUAL filter.  GQ0 homozygous reference samples, which likely have some ALT reads but not enough to merit a het genotype, can introduce enough "doubt" that the site can increase in quality sufficiently to pass the QUAL filter.  Even so, those homozygous reference genotypes won't change.

The AD reflects the count of *informative* reads for each allele, where informative means that the supported allele is at least 10X more likely than any other allele.  Because our likelihoods are based on a paired hidden Markov model alignment, the surrounding reference context will influence each read's likelihood of having been derived from any given allele.  It's possible that the sequence context around that large deletion is such that the ALT reads have other alignments that are nearly as likely, in which case they wouldn't be counted towards the AD.  Does the deletion appear in the GVCFs of the low VAF samples?  If not, the graph assembly could be failing, in which case adding the argument --linked-de-bruijn-graph may improve the situation.

**Comment by DarioS** [comment]
The deletion does not appear in the GVCFs of the low VAF samples, just the high-VAF sample. It also does not appear if `--linked-de-bruijn-graph` is used. I understand that joint genotyping will rescue variants in low coverage regions but not of low VAF.
