### ISSUE TITLE
Increased memory consumption by MarkDuplicatesSpark

### ISSUE THREAD

**Issue by ilyasoifer** [broadinstitute/gatk#8307]
### Affected tool(s) or class(es)
MarkDuplicatesSpark

### Affected version(s)
- [v ] Latest public release version [4.4.0.0]

### Description 
Since switching to 4.4.0.0 we are experiencing an increased memory consumption of MarkDuplicatesSpark. We see it on large BAM/CRAM files, not tested on small files

#### Steps to reproduce
This command: 
```
java -Xmx190g -jar /usr/gitc/GATK_ultima.jar MarkDuplicatesSpark \
--spark-master local[24] \
--input 019242_old.ua.aln.bam \
--output 019242_old.aligned.sorted.duplicates_marked.bam \
--create-output-bam-index true \
--spark-verbosity WARN \
--verbosity WARNING \
--flowbased
```
required 90GB memory on 4.3.0.0. The input BAM is large: 270GB
However on the 4.4.0.0 it requires >160GB RAM

#### Expected behavior
The memory requirement is not expected to change 
#### Actual behavior
Significantly increased memory requirement

**Comment by droazen** [comment]
This might be related to our upgrading to Spark/Hadoop 3.3.1 in the 4.4.0.0 release -- apart from that, I don't think there were any changes to this specific tool.

@lbergelson any thoughts/suggestions?

**Comment by droazen** [comment]
@ilyasoifer As an experiment, could you try running the task via `spark-submit`, passing in `--master local[24]`, and then adjusting `spark.driver.memory` and `spark.executor.memory` to try to control memory usage? We think these memory-related properties might not be respected unless you run using `spark-submit` explicitly. Worth a try, at least!

**Comment by ilyasoifer** [comment]
@droazen  - I am sorry, can you maybe specify the command in a bit more detail? I don't quite understand how to specify spark-runner to MarkDuplicatesSpark

The command that I run now is 
```
        java -Xmx190g -jar ~{gitc_path}GATK_ultima.jar MarkDuplicatesSpark \
        --spark-master local[24] \
        --input ~{sep=" --input " input_bams} \
        --output ~{output_bam_basename}.bam \
        --create-output-bam-index true \
        --spark-verbosity WARN \
        --verbosity WARNING \
```
but besides `--spark-master` and `--spark-verbosity` I don't see other spark-related parameters

**Comment by lbergelson** [comment]
@ilyasoifer I don't know why it's using so much more memory now than it used to.   I did notice you're not running with all of the options we usually specify for spark though.  There are a few options we set via the `gatk` wrapper script.  I'm not 100% sure if they're all still important but we set them for a reason in the distant past.  I would try adding them as --conf options

I think it's possible that they have significant impact on the memory usage.
```
    "spark.kryoserializer.buffer.max" : "512m",
    "spark.driver.maxResultSize" : "0",
    "spark.driver.userClassPathFirst" : "false",
    "spark.io.compression.codec" : "lzf",
    "spark.executor.memoryOverhead" : "600",
    "spark.driver.extraJavaOptions" : EXTRA_JAVA_OPTIONS_SPARK,
    "spark.executor.extraJavaOptions" : EXTRA_JAVA_OPTIONS_SPARK
```

EXTRA_JAVA_OPTIONS_SPARK is
```
"-DGATK_STACKTRACE_ON_USER_EXCEPTION=true " \
                   "-Dsamjdk.use_async_io_read_samtools=false " \
                   "-Dsamjdk.use_async_io_write_samtools=false " \
                   "-Dsamjdk.use_async_io_write_tribble=false " \
                   "-Dsamjdk.compression_level=2 "
```

Now, David was suggesting that you try running using spark-submit and specify explicit memory commands for the driver/executors.  I'm not convinced this will help, but it's worth trying. that this will help, but it's worth trying. 
If you have spark-submit on your path you can either call it directly with `--master local[24]` or use `gatk --spark-runner SPARK --spark-master local[24] ... [the rest of the arguments]` which will construct the appropriate call.  

```
 gatk \
          MarkDuplicatesSpark \
        --spark-runner SPARK  \
        --spark-master "local[24]" \
        --input in.bam \
        --output out.bam \
        --create-output-bam-index true \
        --spark-verbosity WARN \
        --verbosity WARNING
        --driver-memory 8G \
        --executor-memory 4G 
```

Something like that.  I'm honestly not sure how it will handle those memory requests in local mode though since it all runs in the same process.   I suspect it will just add them up and set xmx using the sum.  

The other thing to investigate would be if changes to the garbage collector are causing memory issues.  We've had issues in the past with highly parallel garbage collection using many threads causing things to blow up, and there were definitely changes from java 8 -> 17.

**Comment by ilyasoifer** [comment]
Hi @droazen  and @lbergelson 
Thanks for the helpful suggestions. Indeed, seems that adding just these --conf parameters:         `--conf spark.driver.memory=6g 
        --conf spark.executor.memory=5g`  solved it! 
Thanks for the help. For the others - this is the command that I ended up running
```
        java -Xmx190g -jar ~{gitc_path}GATK_ultima.jar MarkDuplicatesSpark \
        --spark-master local[24] \
        --conf spark.driver.memory=6g \
        --conf spark.executor.memory=5g \
        --spark-verbosity WARN \
        --input ~{sep=" --input " input_bams} \
        --output ~{output_bam_basename}.bam \
        --create-output-bam-index true \
        --verbosity WARNING \
```

**Comment by droazen** [comment]
Glad to hear that worked for you @ilyasoifer -- closing as resolved!
