### ISSUE TITLE
Get Hadoop reference loading code into htsjdk

### ISSUE THREAD

**Issue by davidadamsphd** [broadinstitute/gatk#831]
@tomwhite wrote code to read in the reference from hdfs. We need to move that logic into htsjdk (to avoid the two getting out of sync). Assigning to @droazen for now.

**Comment by tomwhite** [comment]
Rather than adding a Hadoop dependency into htsjdk, it would be sufficient (and more general) to add overloaded methods for InputStream/java.nio.file.Path etc, so that it's possible to use other filesystems with htsjdk.

For example, this is the change needed for the fasta code: https://github.com/samtools/htsjdk/compare/master...tomwhite:hadoop.

It's fairly straightforward to hook this up with Hadoop in hellbender (either directly - which worked when I mocked it up, or using something like https://github.com/damiencarol/jsr203-hadoop - although I haven't tried that one).

Does this approach look ok to you @droazen? I'd like to add a few tests and support for reading a sequence dictionary too, but otherwise that code is almost ready.

**Comment by tomwhite** [comment]
Forgot to say - the java.nio.file API is only available from Java 7 onwards, and htsjdk is currently based on Java 6. However, I noticed that it will support Java 8 from October, so maybe it's OK.

**Comment by tomwhite** [comment]
I've created a pull request for this here: https://github.com/samtools/htsjdk/pull/308. Please take a look when you have time, @droazen.

**Comment by droazen** [comment]
I've added a comment there -- basically I need more information on the advantages of this approach over the one in https://github.com/samtools/htsjdk/pull/211 (which could in theory be merged now rather than in October). Is the main advantage avoiding adding the hadoop dependency in htsjdk, or are there other benefits as well? Do you think it would be cleaner/less invasive, and generalize well to the rest of htsjdk (beyond the reference classes)?

**Comment by droazen** [comment]
This is done! Closing
