### ISSUE TITLE
SplitIntervals BALANCING_WITHOUT_INTERVAL_SUBDIVISION behavior

### ISSUE THREAD

**Issue by cademirch** [broadinstitute/gatk#8315]
### Affected tool(s) or class(es)
SplitIntervals using `-MODE BALANCING_WITHOUT_INTERVAL_SUBDIVISION`

### Affected version(s)
Tested on: 
```
The Genome Analysis Toolkit (GATK) v4.4.0.0
HTSJDK Version: 3.0.5
Picard Version: 3.0.0
```

### Description 
SplitIntervals does not produce the requested number of interval lists as specified by `--scatter-count`, even if it possible based on the input. It seems that SplitIntervals prioritizes equal interval list basepair size. See below for example.

#### Steps to reproduce
Toy example:
genome.fa:
```
>test
AGCTTTTCATTCTGACTGCAACGGGCAATATGTCTCTGTGTGGATTAAAAAAAGAGTCTCTGACAGCAGCTTCTGAACTG
GTTACCTGCCGTGAGTAAATTAAAATTTTATTGACTTAGGTCACTAAATACTTTAACCAATATAGGCATAGCGCACAGAC
AGATAAAAATTACAGAGTACACAACATCCATGAAACGCATTAGCACCACCATTACCACCACCATCACCACCACCATCACC
```
intervals.list:
```
test:1-5
test:7-10
test:15-20
test:25-30
test:30-35
test:40-45
test:50-55
test:60-65
test:70-75
test:76-80
test:82-88
test:90-96
test:98-102
test:105-130
test:136-139
test:145-159
test:160-220
```
Command:
```
gatk SplitIntervals -R genome.fa -L toy_intervals.list -O ./ --scatter-count 17 -mode BALANCING_WITHOUT_INTERVAL_SUBDIVISION --sequence-dictionary genome.dict --interval-merging-rule OVERLAPPING_ONLY
```
This only produces 3 interval list files. If this is expected behavior, its not entirely clear from the documentation.

#### Expected behavior
I have a list of 500 non-overlapping intervals (from ScatterIntervalsByNs) that I would like SplitIntervals to organize into 250 interval lists. I would expect that the tool would produce 250 list files. 

#### Actual behavior
The tool only produces 12 interval list files. 

----

**Comment by droazen** [comment]
Hi [cademirch](https://github.com/cademirch),

I believe the tool is working as intended in this case. The tool in this mode is designed to balance interval lists evenly by the amount of genomic territory covered, without splitting any individual interval. The documentation for `BALANCING_WITHOUT_INTERVAL_SUBDIVISION` mode mentions this:

"Scatter the interval list into similarly sized interval lists (**_by base count_**), but without breaking up intervals."

Since the tool is not allowed to split individual intervals in this mode, it may use the number of bases in the largest interval (`test:160-220` in your toy example) as the target number of bases per file:

"The "target width" of each scatter list may be wider than what is computed for INTERVAL_SUBDIVISION. Specifically, if the widest interval in the source interval list is larger than what would otherwise be the target width, that interval's width is used."

This likely explains why you're only getting 3 files -- the tool is trying to ensure that each file covers ~60 bases.

If you just want to divide by number of intervals, rather than base count, you should be using `INTERVAL_COUNT` mode instead.

**Comment by cademirch** [comment]
Thanks @droazen, thats what I had suspected. I didn't know about the `INTERVAL_COUNT` option, I must've been looking at older documentation. Thanks.
