### ISSUE TITLE
Docker image (broadinstitute/gatk) has too many unnecessary layers potentially causing throttling issues

### ISSUE THREAD

**Issue by MattMcL4475** [broadinstitute/gatk#8684]
### Affected tool(s) or class(es)
The docker image: `broadinstitute/gatk`

### Affected version(s)
`latest`

### Description 
- The current GATK image has 44 layers
- In [the Azure Container Registry standard service tier](https://learn.microsoft.com/en-us/azure/container-registry/container-registry-skus#registry-throughput-and-throttling), "ReadOps per minute" is limited to 3000
- "A `docker pull` translates to multiple read operations based on the number of layers in the image, plus the manifest retrieval."
- 3000 / 45 = 66.  That means that the image can only be pulled 66 times per minute.  This is problematic for running many concurrent workflows that also have many shards.  Once that limit is exceeded, the task can fail, which can cause the entire workflow to fail. 
- Layers can be viewed here:  `docker history --no-trunc broadinstitute/gatk > gatk-image-layers.txt`
[gatk-image-layers.txt](https://github.com/broadinstitute/gatk/files/14212774/gatk-image-layers.txt)

#### Steps to reproduce
 `docker history --no-trunc broadinstitute/gatk > gatk-image-layers.txt`

#### Expected behavior
`--squash` shall be added to `build_docker_base_cloud.sh`, like has been added to `build_docker_base_locally.sh` already: https://github.com/broadinstitute/gatk/blob/a353e49f218e675f331abf629f0bb46df1d5151d/scripts/docker/gatkbase/build_docker_base_locally.sh#L24

#### Workaround
Users can pull the existing image, and [use `docker-squash` to squash the image to a single layer](https://github.com/goldmann/docker-squash), then push it into their private ACR, then update their WDLs to reference the new image.

**Comment by lbergelson** [comment]
Oof, that's a nasty problem.  We can definitely do something about it.  It feels more like a Microsoft bug than a GATK one though.  It seems crazy that each layer pull has to be a separate web request and there's no batch api for it?  Multi layer docker builds are pretty standard from what I understand.  

It sounds like your suggestions are talking about 2 slightly different issues to me.

1. Too many layers:

We typically have squashed the GATK docker images, but we recently switched to building our release images with google cloud build.  Since squash is *STILL* an experimental feature in docker we've had trouble getting it to work there.  Since the size reduction was pretty minimal from squashing we figured it would be ok to not prioritize it.

It's definitely possible for us to consolidate various layers in the build.   Or manually squash the images. We can take a look for our next release.  Wide workflows on azure are something we need to support.

2.  Docker size reduction:
 I've spend a lot of time looking at this in the past.  Our docker image is huge, but it's mostly due to the massive size of our python and R dependencies.  I've done a bunch of work reducing temporary files in independent layers and using multiple stages to reduce the size.  There's not much low hanging fruit left there.

Similarly, moving to alpine is tricky an has limited benefit.  GATK packages a number of C libraries which do not work out of the box on alpine due to the different C runtime.  (At least that was the case the last time I investigated it a few years ago. ) I suspect there's a way to port things so they work on it, but it's not something we can do now.  It also wouldn't be much of a help, the base image is completely dwarfed by piles of python and R dependencies which are very difficult to safely trim.

Anyway, that's the state of things.  We've considered a java only image for a while which would be much smaller than the current one.  (although still fat by most docker standards...).  We've never released one publicly because it seemed like it might cause confusion, but it's a reasonable possibility.  

If you have any secret methods to reduce the size of python or R installations we're happy to take PRs!

**Comment by lbergelson** [comment]
@droazen Sound's like we need to revisit squashing the docker...

**Comment by MattMcL4475** [comment]
Thanks @lbergelson for looking into this.  Users can definitely squash the image after pulling, and then push it to their private registries - that's the best workaround here, so this is likely a low-priority issue.  Docker images can only be pulled by layers currently; there's no way to pull an image with one HTTP request.  In the [TES runner](https://github.com/microsoft/ga4gh-tes), we are also increasing the docker pull retry count to help.

Is the current `broadinstitute/gatk` image being built by a `dockerfile` in the current repo?  Happy to review it and write a PR.  Thank you!

**Comment by lbergelson** [comment]
@MattMcL4475 There is a `Dockerfile` in the root of the gatk repo that is used for the docker build.  The base image dockerfile is in `scripts/docker/gatkbase`.  I'm not a docker expert but I've spent a bunch of time looking around with [Dive](https://github.com/wagoodman/dive) to try and remove extraneous stuff.

**Comment by MattMcL4475** [comment]
Thanks @lbergelson , I took a first pass at writing a [draft PR](https://github.com/broadinstitute/gatk/pull/8686), but after thinking about what you said, it's likely easiest to just wait until `--squash` is added to `build_docker_base_cloud.sh`, like has been added to `build_docker_base_locally.sh`: https://github.com/broadinstitute/gatk/blob/a353e49f218e675f331abf629f0bb46df1d5151d/scripts/docker/gatkbase/build_docker_base_locally.sh#L24 .  Thanks for your help thinking this through!  Matt

**Comment by lbergelson** [comment]
If you have any thoughts about HOW to get it to work on google cloud build we'd love your input.  We haven't figured out how to enable experimental docker features on cloud build.

**Comment by VJalili** [comment]
We build GATK-SV docker images on GitHub runners. We use the following to set up the environment to use `--squash` flag.

https://github.com/broadinstitute/gatk-sv/blob/52813222b64bf2d15fb9a1aae068590bee184511/.github/workflows/sv_pipeline_docker.yml#L199-L204

I am unsure if you can configure the runtime env on Google Cloud build, but if you can, hopefully, the above can hint some directions.

**Comment by droazen** [comment]
@MattMcL4475 We've merged a PR that reduces the number of layers in our docker image from 44 down to 16: https://github.com/broadinstitute/gatk/pull/8808

See comments on that PR for reasons why this approach might be preferable to a full squash. If there are still too many layers for your use case, please feel free to reopen this ticket.
