### ISSUE TITLE
several genes are reported in "PREDICTED_LOF" for a balanced translocation

### ISSUE THREAD

**Issue by Nehir291** [broadinstitute/gatk#8852]
**bug report**

I have a balanced translocation (CTX) case and it has several genes (475 genes) under PREDICTED_LOF. However, one CTX breakpoint hits an intron of a gene, whereas the other breakpoint is intergenic. How this CTX is calculated as PREDICTED_LOF?

Thanks.

**Comment by Nehir291** [comment]
Thanks for the response and clarifying that. 
The breakpoints are not overlapping at any exon (one bp is intergenic, the other is in intronic site). 
I still don't see how so many genes have been computed under PREDCITED_LOF.

**Comment by epiercehoffman** [comment]
Hi @Nehir291, please refer to the SVAnnotate tool documentation for definitions of each annotation: https://gatk.broadinstitute.org/hc/en-us/articles/21905053774363-SVAnnotate. For translocations, PREDICTED_LOF is assigned if a breakpoint falls at any point in the transcript, so an intronic breakpoint would still be annotated as PREDICTED_LOF for any impacted genes. This is because only part of the gene exists on each chromosome after the translocation, which is likely to result in a truncated transcript subject to nonsense-mediated decay. 

Perhaps in some cases this definition is overly permissive, such as if only the UTR or one shorter exon is removed by the translocation - those cases could be worth revisiting. 

I hope this helps explain the behavior you are seeing. If this does not fully explain all the PREDICTED_LOF annotations you are observing, please share the CTX breakpoints, the annotations, and the GTF used so we can investigate further.
