### ISSUE TITLE
[question] Are large files only required for tests, or also required at build and run-time ?

### ISSUE THREAD

**Issue by yurivict** [broadinstitute/gatk#8912]
At one point the README says:
> [...] large files used to build GATK, and test files required to run the test suite [...]

Does this mean that all production builds should contain large files?
Are they used by some gatk commands?

The README is just not clear about this.

**Comment by droazen** [comment]
@yurivict The large files under `src/main/resources/large/` are required to build GATK, since they are packaged inside the GATK jar and used by tools at runtime. These are things like ML models and native C/C++ libraries used for acceleration of certain tools.

The large files under `src/test/resources/large/`, on the other hand, are only required by the test suite when running tests.

Hope this clears things up!

**Comment by droazen** [comment]
@yurivict There is a note in the README about this in the "Building GATK4" section:

```
Note that you must have a full git clone in order to build GATK, including the git-lfs files in src/main/resources. The zipped source code alone is not buildable.
```

**Comment by SaarGirl** [comment]
.
