### ISSUE TITLE
Document how to access spark master page when running hellbender on GCE/dataproc

### ISSUE THREAD

**Issue by droazen** [broadinstitute/gatk#975]

**Comment by davidadamsphd** [comment]
I've gotten this to work with an internal GCE project (I haven't successfully tested with broad-dsde-dev because of firewall rules). However, it should look like this using bdutil.

```
./bdutil -P cluster-1 -z us-central1-a -p broad-dsde-dev -b dataproc-8cbe9d51-94fb-4ad4-9c34-a283212c2ae6-us  -e hadoop2 socksproxy 12340
```
which is just a wrapper around
```
gcloud --project=broad-dsde-dev --quiet --verbosity=info compute ssh cluster-1-m --command= --ssh-flag=-N --ssh-flag=-D12340 --ssh-flag=-oServerAliveInterval=60 --ssh-flag=-oServerAliveCountMax=3 --ssh-flag=-oConnectTimeout=30 --zone=us-central1-a
```
and a few other commands.

After the proxy has started, you need to open up Chrome with the proxy:
```
/Applications/Google\ Chrome.app/Contents/MacOS/Google\ Chrome  --proxy-server='socks5://localhost:12340' --host-resolver-rules='MAP * 0.0.0.0, EXCLUDE localhost' --user-data-dir=/tmp/bdutil-socksproxy/cluster-1-m http://cluster-1-m:8088 http://cluster-1-m:50070
```
That'll open up the master page.

If you have any funky IP address/proxy extensions (like I do), you'll need to turn those off.

@droazen and @lbergelson, where do you want this documented?

**Comment by droazen** [comment]
Completely and utterly gross, but I guess it's the best we've got for now. How about adding a page to the github wiki, and linking to it from the README?

**Comment by droazen** [comment]
Would also be good to identify what changes we'd need to make to the `broad-dsde-dev` firewall config to make this work there so that we can file a request with IT.

**Comment by davidadamsphd** [comment]
Will do (for all points).

As an FYI: here is the main doc page for this feature (it's not what I used though)
https://cloud.google.com/dataproc/cluster-web-interfaces

**Comment by droazen** [comment]
This one is done!
